### PR TITLE
Add GRMS

### PR DESCRIPTION
**Pull request by Miner113**
I want to add my own coin

### CODE REVIEW

**Comment by Miner113** [comment]
what other information is needed to add my coin?

**Review by smk762 — DISMISSED** [review]
image

**Comment by Miner113** [comment]
Do you need any information from us to add a coin

**Comment by smk762** [comment]
Reviewed and approved. Will probably be merged this week.

**Comment by Milerius** [comment]
(0.5.0 doesn't exist anymore, it's 0.5.1 now, please sync with last dev branch)

**Comment by Milerius** [comment]
i think he need your help to fix the conflict @smk762

**Comment by smk762** [comment]
Recreated here - https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1259
@Miner113  Once built in CI actions, you can check if it looks ok by downloading from here - https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/1208313753
I'll check too (might need to rest assets config from settings to clear the old coins.json)

**Pull request closed without merging**
