### PR TITLE
enhancement(chart_space): set trading information fill empty space

### PR DESCRIPTION
**Pull request by ssakone**

### CODE REVIEW

**Comment by tonymorony** [comment]
as discussed in DMs let's make resize arrows not disappear and work like a:

`<>` - enlarge
then this icon became `><` to make the widget small again on click

**Review by cipig — APPROVED** [review]
LGTM
image

**Review by smk762 — APPROVED** [review]

**Comment by ssakone** [comment]
New Checklist: 

- [ ] Check Dex layout expand & collapse
- [ ] Check Dex widget visibility state is saved
- [ ] Check User menu logout button have icon.

**Review by tonymorony — APPROVED** [review]

**Comment by smk762** [comment]
- logout button visible and functional
- layout state not preserved when switching tab and switching back.
- dex layout expand / collapse mostly works but -
 - place order eyeball icon always has line over it like David Bowie.
 - other panel eyeball icons always open.
 - some combinations of visible / hidden / expanded states can still leave whitespace. To replicate, close orderbook visibility by clicking on eye, then click on best orders expand arrows. Similar effect can happen with chart and trading info panels when chart is hidden. If an adjoining panel is hidden, the remaining panels in that area should automatically expand to fill available space.

https://user-images.githubusercontent.com/35845239/122027113-67fd3700-cdfd-11eb-83dc-177048687b7b.mp4

**Pull request merged**
