### PR TITLE
Changes asks list order

### LINKED ISSUE #2116: [BUG]: Orderbook entries are reversed
Right now top (red) part of the orderbook is suboptimal - best orders are on the bottom and worst are on top what makes interface inconsistent, and in case of orderbook update user have to scroll from top to the bottom to see best order / loses focus from best order what a) just not good in terms of UX b) can cause not best order matching

We should reverse it's content and show best orders on top (same as in green part) and ensure that best order is always on top on orderbook refresh without the need to scroll anything 

https://user-images.githubusercontent.com/24797699/204137086-4cc37b47-3553-469c-812f-f3efc6311651.mov

### PR DESCRIPTION
**Pull request by SylEze**
Closes #2116

### CODE REVIEW

**Review by SirSevenG — DISMISSED** [review]
lgtm

**Review by tonymorony — CHANGES_REQUESTED** [review]
asks list jumping somewhere to the middle when I select bid and I have to scroll back:

https://user-images.githubusercontent.com/24797699/204336345-c1ff3283-df5b-4e7f-bba1-39229f510e92.mov

**Comment by smk762** [comment]
> asks list jumping somewhere to the middle when I select bid and I have to scroll back:

replicated here

**Comment by smk762** [comment]
After switching tickers seems the scroll is not where it should be.

https://user-images.githubusercontent.com/35845239/204824319-880e623d-c0ea-4eaa-b591-2660dba2030b.mp4

**Comment by SylEze** [comment]
Let's discuss on how the orderbook can be improved in another issue, this PR just aims to change the orderbook sorting order and has no effet on what has been mentioned

**Comment by cipig** [comment]
i disagree, see https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2116#issuecomment-1333126923
the sorting was correct

**Pull request closed without merging**
