### PR TITLE
0.5.4

### PR DESCRIPTION
**Pull request by ca333**
### Release Notes 

**Features:** 

* New protocols (and over a hundred tokens on these protocols) added: Polygon, Arbitrum (wallet-only), Optimism (wallet-only), Fantom, Harmony, Avax, HecoChain, Moonriver, Kucoin Chain, Ubiq, SmartBCH
* Added nomics price provider

**Enhancements:**

* Dark theme update
* Interface visual improvements and partial re-work 
* API update
 
**Fixes:**

* Multiple minor interface fixes

### CODE REVIEW

**Comment by cipig** [comment]
works fine, the only remaining bug that is a bit annoying for me personally is https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1315
should that be fixed for 0.5.4? if postponed, i will approve...

**Comment by SylEze** [comment]
> works fine, the only remaining bug that is a bit annoying for me personally is #1315 should that be fixed for 0.5.4? if postponed, i will approve...

I'm aware of that one but I could not find a fix atm.
This is the code we use to update the chart (event based), and switching coins from Best Orders tab is triggering this event

```qml
Connections
{
    target: app
    function onPairChanged(base, rel)
    {
        root.loadChart(base, rel)
    }
}
```

**Comment by smk762** [comment]
On first load after tabswitch to dex > orders, half of the right side coin is cut off. Issue also present if hovering over sidebar and it is expanded, but gets gets auto-fixed after hovering off once sidebar retracts.

On history page, scrollbar makes it always partially cut off, and almost completely hidden when sidebar expanded.

https://user-images.githubusercontent.com/35845239/146180534-e2299733-0e68-4a36-9d6d-ece7a76fe5d3.mp4

**Comment by cipig** [comment]
> I'm aware of that one but I could not find a fix atm.
> This is the code we use to update the chart (event based), and switching coins from Best Orders tab is triggering this event

looked at it again and found a new info that may help: when i switch through the pairs with sell mode from best_orders, the problem is not there... and switching in buy mode always loads wrong chart, eg when switching from LTC/USDT to LTC/USDC, it shows no chart at all (likely tries USDT/USDC)... i guess the problem is some inverted base/rel thingy because of buy/sell mode, wrong variable is changed (base/rel), something like this

**Review by smk762 — DISMISSED** [review]
Comprehensive multiOS tests completed last week, follow up tests of most recent changes passed today.
Thanks to all contributors! 
It's looking real nice now @SylEze @ssakone 
Hat's off to @Milerius for the bonus protocols
:dragon: :christmas_tree: :gift_heart:

**Review by tonymorony — DISMISSED** [review]

**Review by Milerius — APPROVED** [review]

**Review by SylEze — DISMISSED** [review]

**Review by cipig — APPROVED** [review]

**Review by smk762 — APPROVED** [review]

**Review by tonymorony — DISMISSED** [review]

**Review by Milerius — APPROVED** [review]

**Review by cipig — DISMISSED** [review]

**Review by smk762 — APPROVED** [review]
Loads on all OS with all artefacts, basic functionality since last review still working as expected.

**Review by Milerius — DISMISSED** [review]

**Comment by tonymorony** [comment]
Waiting for API patch release with latest fixes as was discussed in our last call [ @ca333 @artemii235 ]

**Comment by tonymorony** [comment]
Updated adex-api to the fresh release with hotfixes, now this PR is ready for the final smoke-testing [ CC @smk762 ]

**Review by Milerius — APPROVED** [review]

**Review by smk762 — APPROVED** [review]
Local builds for Windows and Linux launch ok, swaps completed and rewards claims done. Maker order between devices also created and matched without issue.
Unable to properly test mac at the moment.

**Review by tonymorony — APPROVED** [review]
built on mac locally, basic tests passed

**Review by cipig — APPROVED** [review]

**Pull request merged**
