### PR TITLE
enhancement(various_fix2): Fix notification persistence & Make order ID copyable.

### PR DESCRIPTION
**Pull request by ssakone**

### CODE REVIEW

**Comment by smk762** [comment]
notifications fixed :heavy_check_mark: 
Copy works, but the only indication uuid is active is cursor change when you hover over it - might be better to use a copy symbol like how it is on wallet retrieve to copy address (and highlighting uuid when clicked)

Also, the "uuid" copied message is also popping up under the swaps detail panel so it is mostly obscured
image

**Comment by smk762** [comment]
Copy icon working as expected :heavy_check_mark: 
Pop up message still buried :crossed_flags: 
image

**Comment by ssakone** [comment]
@smk762  need review

**Review by smk762 — APPROVED** [review]
Working as expected

**Review by tonymorony — APPROVED** [review]

**Pull request merged**
