### PR TITLE
feat(macos_custom_header): Add adaptative custom header for macos

### PR DESCRIPTION
**Pull request by ssakone**

### CODE REVIEW

**Comment by smk762** [comment]
Latest build does not load for me on mac.
```
[17:36:07] [info] [qt.settings.page.cpp:115] [12891]: Locale after parsing AtomicDEX settings: en_US
[17:36:07] [warning] [main.prerequisites.hpp:124] [12982]: Populating font family aliases took 341 ms. Replace uses of missing font family "Segoe UI" with one that exists to avoid this cost. 
[17:36:07] [info] [internet.checker.service.cpp:131] [12979]: Connectivity is true for the endpoint: https://api.coinpaprika.com/
[17:36:08] [warning] [main.prerequisites.hpp:124] [12891]: QQmlApplicationEngine failed to load component
[17:36:08] [warning] [main.prerequisites.hpp:124] [12891]: qrc:/atomic_defi_design/qml/main.qml:72:9: DexWindowHeaderControl is not a type
[17:36:08] [error] [main.prerequisites.hpp:138] [12891]: sigabort received, cleaning mm2
No matching processes belonging to you were found
[17:36:08] [error] [main.prerequisites.hpp:144] [12891]: stacktrace:  0# mm2::api::tx_history_answer atomic_dex::mm2_client::rpc_process_answer<mm2::api::tx_history_answer>(web::http::http_response const&, std::1::basic_string<char, std::1::char_traits<char>, std::__1::allocator<char> > const&) in /Applications/atomicdex-desktop.app/Contents/MacOS/atomicdex-desktop
 1# _sigtramp in /usr/lib/system/libsystem_platform.dylib
 2# QWindow::winId() const in /Applications/atomicdex-desktop.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
 3# main in /Applications/atomicdex-desktop.app/Contents/MacOS/atomicdex-desktop
 4# main in /Applications/atomicdex-desktop.app/Contents/MacOS/atomicdex-desktop

```

**Comment by Milerius** [comment]
@smk762 please chcek on mac os this pr and confirm you have the same button over effect than other mac application and everything work as expected, fullscreen should be maximized and not fullscreen.

**Comment by ssakone** [comment]
> @smk762 please chcek on mac os this pr and confirm you have the same button over effect than other mac application and everything work as expected, fullscreen should be maximized and not fullscreen.

FullScreen button make fullscreen, when user double click on on toolbar it will be maximized, so i can the action of fullscreen buttton to maximize not put it fullscreen

**Comment by Milerius** [comment]
> > @smk762 please chcek on mac os this pr and confirm you have the same button over effect than other mac application and everything work as expected, fullscreen should be maximized and not fullscreen.
> 
> FullScreen button make fullscreen, when user double click on on toolbar it will be maximized, so i can the action of fullscreen buttton to maximize not put it fullscreen

Well i thought it's was difficult to quit full screen state in custom title bar but if it's possible and works it's even better, let's keep it like that, i'm waiting for feedback from @smk762 on macos

**Review by smk762 — DISMISSED** [review]
No problem here on Mac - Double click maximises, minimise button works, and I can quit from fullscreen without issue.

**Comment by Milerius** [comment]
> No problem here on Mac - Double click maximises, minimise button works, and I can quit from fullscreen without issue.

@smk762 i have 2 minor issue, do you have the same ? 

https://user-images.githubusercontent.com/21139416/117451609-01097a00-af43-11eb-9423-d8e20cd18a2b.mov

size of the button: 

Capture d’écran 2021-05-07 à 14 41 07

**Comment by ssakone** [comment]
I have not find any documentation or guide line about these button size est structure, i watch picture and i reproduice.

**Pull request merged**
