### PR TITLE
better min vol logic

### PR DESCRIPTION
**Pull request by smk762**
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2153

To test:
- Try to place order for/with KMD vs Smartchain at lowest amount possible.
- Check orders tab, one side will be 0.0001, and the other side larger than 0.0001 (as below)
image

- Look for a pair orderbook where maker has set custom minimum, and confirm can not start swap if setting volume lower
- Test other coin like DOGE or BTC, default minimum will be 0.1 or 0.00777 instead of 0.0001

### CODE REVIEW

**Comment by Canialon** [comment]
>Test other coin like DOGE or BTC, default minimum will be 0.1 or 0.00777 instead of 0.0001

take a look, default minimum volume is 0.0001, and it change  to 0.1 or 0.00777 only after clicking on the custom checkbox


https://user-images.githubusercontent.com/77272165/206301983-5720aaf7-937f-405e-b83e-e300c533979a.mov

**Comment by smk762** [comment]
Thanks. It should also change when selecting an order from orderbook or setting price input (until selected price is known, it does not call https://developers.komodoplatform.com/basic-docs/atomicdex-api-legacy/min_trading_vol.html yet)

I'll see if I can add an earlier `min_trading_vol` call using market price to get a better approximation instead of using a static default value.

**Review by cipig — APPROVED** [review]

**Review by SylEze — DISMISSED** [review]

**Comment by SylEze** [comment]
Please test carefully and try with many different swaps with different pairs 

cc. @Canialon @SirSevenG

**Comment by smk762** [comment]
> > Test other coin like DOGE or BTC, default minimum will be 0.1 or 0.00777 instead of 0.0001
> 
> take a look, default minimum volume is 0.0001, and it change to 0.1 or 0.00777 only after clicking on the custom checkbox

I've pushed this into a separate issue as I wont be able to fix that today and the PR is otherwise ready to review/merge.

**Comment by SirSevenG** [comment]
Hmm

>Look for a pair orderbook where maker has set custom minimum, and confirm can not start swap if setting volume lower

Generally, it works. You can't start trade with Volume < maker min_volume
Yet, there's an issue:

image

If you use exact trade volume == maker min_volume, where maker's min volume has more than 6 decimals, order will likely not match due to rounding:

image


@smk762 this PR seems to fix initial issue/report, we can also fix my problem as separate issue. What do you think?

**Comment by SirSevenG** [comment]
```
Make Error at D:/a/atomicDEX-Desktop/atomicDEX-Desktop/cmake/install/windows/windows_post_install.cmake:81 (file):
  file COPY cannot find
  "D:/a/atomicDEX-Desktop/atomicDEX-Desktop/b/bin/atomicdex-desktop.7z": File
  exists.
Call Stack (most recent call first):
  src/cmake_install.cmake:41 (include)
  cmake_install.cmake:67 (include)


 project...
FAILED: CMakeFiles/install.util 
cmd.exe /C "cd /D D:\a\atomicDEX-Desktop\atomicDEX-Desktop\b && C:\ProgramData\scoop\apps\cmake\3.22.0\bin\cmake.exe -P cmake_install.cmake"
ninja: build stopped: subcommand failed.
```
@smk762 @SylEze I think we've fixed same CI error previously

**Comment by smk762** [comment]
> ```
> Make Error at D:/a/atomicDEX-Desktop/atomicDEX-Desktop/cmake/install/windows/windows_post_install.cmake:81 (file):
>   file COPY cannot find
>   "D:/a/atomicDEX-Desktop/atomicDEX-Desktop/b/bin/atomicdex-desktop.7z": File
>   exists.
> Call Stack (most recent call first):
>   src/cmake_install.cmake:41 (include)
>   cmake_install.cmake:67 (include)
> 
> 
>  project...
> FAILED: CMakeFiles/install.util 
> cmd.exe /C "cd /D D:\a\atomicDEX-Desktop\atomicDEX-Desktop\b && C:\ProgramData\scoop\apps\cmake\3.22.0\bin\cmake.exe -P cmake_install.cmake"
> ninja: build stopped: subcommand failed.
> ```
> 
> @smk762 @SylEze I think we've fixed same CI error previously

This one should fix it https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/2182

**Comment by cipig** [comment]
> If you use exact trade volume == maker min_volume, where maker's min volume has more than 6 decimals, order will likely not match due to rounding:

it does match, i did a lot of swaps with those orders
this is because GUI switched to using rational/fractional numbers for the volume instead of decimals some time ago, so there are no rounding errors

**Comment by smk762** [comment]
We'll need to test this more in other PR for https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2183
Sometimes rounding wont be a problem depending on which way it rounds so will have to try multiple trades / valuse to make sure we have it covered

**Review by cipig — APPROVED** [review]

**Review by SirSevenG — APPROVED** [review]

**Review by Canialon — APPROVED** [review]

**Pull request merged**
