### PR TITLE
remove nomics and replace chart

### PR DESCRIPTION
**Pull request by smk762**
Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2238

To test: 
- check dex pro view chart. resize / maximise window. change pair. there should be no flicker or overflow.

We dont have i or this widget yet, though it uses tickers by default so it the ticker is supported a chart will display.
This has some known issues:
- The ticker may link to the wrong coin
image
- the ticker may not be supported
image

Until we can compile a list of correct/working tickers, I'll add an exclusion list for coins known to be no good. Please list any you encounter in this PR.

### CODE REVIEW

**Comment by cipig** [comment]
we could add a new file to https://github.com/KomodoPlatform/coins/tree/master/api_ids for livecoinwatch
if there is an id for the coin, it takes that (useful for duplicate tickers like TRC for https://www.livecoinwatch.com/price/Terracoin-TRC and https://www.livecoinwatch.com/price/TRACERToken-_TRC... for the other one they use `_TRC` as ticker, which we can define like that in the file)
and the cases where the ticker is there but points to a wrong coin, we can use "" in the new api_ids file, to tell ADEX to not load a chart at all... https://www.livecoinwatch.com/price/McLarenF1FanToken-MCL would be such a candidate... it uses MCL, but is not Marmarachain

can we also please use 7d charts, instead of 1d? just set `lcw-period="w"`

**Comment by smk762** [comment]
> can we also please use 7d charts, instead of 1d? just set `lcw-period="w"`

Done. I've not implemented an exclusion list yet, but will populate it from review feedback.

**Comment by cipig** [comment]
looks good, thanks
we need to remove the chain from the ticker though, eg `-BEP20` and also `-segwit` because:
image
image

**Review by cipig — APPROVED** [review]
works fine now, thanks
this error shows up when i switch pairs, but looks like it has no negative effect, and idk if it's even related
`[12:42:53] [error] [main.prerequisites.hpp:96] [304992]: Error: <svg> attribute viewBox: Unexpected end of attribute. Expected number, "".`

**Review by Canialon — COMMENTED** [review]
- looks like it can be a scrollbar if it is no chart, i guess it is not very good, will be nice to not cause it.
image

- in pair of fiat and not fiat coin: with some test coins, it is no data but with (screenshot 1) but with some test coins the chart displays with $ (screenshot 2)
image
image


-sometimes size broken 
image


- the resizing looks weird and slow, also can just freeze with "loading data"

https://user-images.githubusercontent.com/77272165/230104854-8b4db08b-a7dd-4d8c-85ef-4c4efa982d73.mov


https://user-images.githubusercontent.com/77272165/230105951-fd5de32c-c13c-4143-ab7c-29f0960d0ad5.mov

UPD: tested on MacOS

**Comment by cipig** [comment]
strange, i don't have those problems with the sidebar, the chart is not reloaded... the only thing is that everything is moved to the right, even if it doesn't fit into the window, like this:
image

when i resize, the loading is indeed somewhat slow, but i don't care, i don't resize all the time
btw, saving the window size would be nice, then i wouldn't have to resize at all, see https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2207

**Comment by endrilickollari** [comment]
Sidebar loading happening in Windows 10 also, sometimes it loads faster sometimes it gets stuck also during resizing it does the same thing. 

Video: 


https://user-images.githubusercontent.com/32954585/230185992-d264056e-9b7a-44fd-8bd6-6326bc2983e5.mp4

Also when trying to trade test coins message appears: 

image


OS: Windows 10 
Resolution: 1920 x 1080

**Review by endrilickollari — COMMENTED** [review]
Sidebar loading happening in Windows 10 also, sometimes it loads faster sometimes it gets stuck also during resizing it does the same thing.

Video:


https://user-images.githubusercontent.com/32954585/230187321-d0fd0972-3917-410a-b8cb-53d806b81153.mp4



Also when trying to trade test coins message appears:

image


OS: Windows 10
Resolution: 1920 x 1080

**Comment by smk762** [comment]
> works fine now, thanks this error shows up when i switch pairs, but looks like it has no negative effect, and idk if it's even related `[12:42:53] [error] [main.prerequisites.hpp:96] [304992]: Error: <svg> attribute viewBox: Unexpected end of attribute. Expected number, "".`

This error is thrown from the widget's own script. It also comes up in the console on https://www.livecoinwatch.com/widgets

**Comment by smk762** [comment]
> -sometimes size broken image
> 
> * the resizing looks weird and slow, also can just freeze with "loading data"
> 
> UPD: tested on MacOS

I've now set it to use a fixed width, which should resolve the resizing issues.
Testcoins should also now be filtered out (if either ticker is a testcoin, there will be no chart)

**Comment by smk762** [comment]
> Also when trying to trade test coins message appears:

This is expected, though I might tweak the wording, because `yet` implies there will be a chart in future (but for test coins this is unlikely)

**Comment by smk762** [comment]
Ready for re-review. **You will have to reset assets config for the latest changes in coins repo (https://github.com/KomodoPlatform/coins/pull/689) to apply** 

https://user-images.githubusercontent.com/35845239/230337523-8c63cd81-9e55-41fb-a457-1de5bf6ffcc6.mp4

**Comment by smk762** [comment]
It seems for some minor coins which are supported by livecoinwatch may not be supported as a pair. I can't think of a method to filter these out without using a pair exclusion list.

https://user-images.githubusercontent.com/35845239/230338626-9a359d94-dd1d-4208-a2f7-38fe9302f09b.mp4

As it is only affecting less common pairs, I'll make this an issue for future (so not a blocker for this PR)

**Review by cipig — APPROVED** [review]

**Review by endrilickollari — COMMENTED** [review]
Chart looks very good now

video: 


https://user-images.githubusercontent.com/32954585/230459312-6035d9f9-7786-43ec-afe3-e78b911a0820.mp4


OS: Windows 10

**Review by Canialon — APPROVED** [review]
looks good now:D

**Pull request merged**
