### PR TITLE
Add wallet only label

### PR DESCRIPTION
**Pull request by smk762**
Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1343

Tag has been added in enable modal
image

Disabled swap button with tooltip when coin is wallet only
image

Do we want this tagging alongside the ticker on portfolio? Or in wallet header section? Not really sure where to slot it in.

### CODE REVIEW

**Review by tonymorony — APPROVED** [review]

**Comment by tonymorony** [comment]
if maximise window buttons resizing:

image

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by smk762** [comment]
> ^^

fixed, thanks.

https://user-images.githubusercontent.com/35845239/155321129-424561e2-83af-4114-ad4e-342e3140e077.mp4

**Review by tonymorony — APPROVED** [review]
thank you, lgtm now

**Review by SylEze — APPROVED** [review]

**Pull request merged**
