### PR TITLE
Refactor addressbook backend code

### PR DESCRIPTION
**Pull request by ghost**
This PR attempts to remove the presence of spaghetti code in the backend side.

This PR only affects addressbook part of the application.

Update:
This PR also affects frontend because some symbol names were changed and qt models have changed.

Addendum:
Could you please check if #1978 still persists

### CODE REVIEW

**Comment by SirSevenG** [comment]
@SylEze there are issues with coins file and mm2 version, can you merge actual dev to backend_refactoring/addressbook to solve it?
```
[19:34:11] [debug] [mm2.service.cpp:1663] [2656]: spawn_mm2_instance l1663 f[mm2.service.cpp]
[19:34:11] [error] [mm2.service.cpp:232] [2656]: exception caught: [json.exception.type_error.302] type must be array, but is string
```

**Review by SirSevenG — CHANGES_REQUESTED** [review]
Can't add tags to addreess book items.
```
[14:57:33] [warning] [main.prerequisites.hpp:93] [5909]: qrc:/Dex/Addressbook/AddTagPopup.qml:53: TypeError: Property 'addCategory' of object test is not a function
```
There 'test' is actual tag text

**Comment by smk762** [comment]
Unable to add new addresses. Error seen in logs:
`[15:14:19] [warning] [main.prerequisites.hpp:93] [711443]: qrc:/Dex/Addressbook/AddAddressForm.qml:247: TypeError: Type error`

**Review by SirSevenG — CHANGES_REQUESTED** [review]
> Unable to add new addresses

Same here

**Comment by SylEze** [comment]
@SirSevenG @smk762 please retest whenever you can

**Review by Canialon — DISMISSED** [review]

**Comment by Canialon** [comment]
The issue above looks just like this one https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1868 but a little different, it's back XD

**Comment by Canialon** [comment]
I believe it makes sense to remember the state of this checkbox. I don't think that users create new contacts very often, but it can be helpful  if it is so 

image

**Comment by SylEze** [comment]
Should be fixed @Canialon

**Review by SirSevenG — COMMENTED** [review]
Could not reproduce https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1978

Couple issues:

1. Can't add multiple addresses to a single adressbook entry in a row:

- Create new contact
- Add coin/address A to it
- Try to add coin/address B to contact without closing contact view first
- On pressing Add button nothing happens

Log errors:
```
[17:21:57] [warning] [main.prerequisites.hpp:93] [4950]: qrc:/Dex/Addressbook/EditContactModal.qml:225: TypeError: Cannot read property 'tags' of null
[17:21:57] [warning] [main.prerequisites.hpp:93] [4950]: qrc:/Dex/Addressbook/EditContactModal.qml:48: TypeError: Cannot read property 'addressListModel' of null
[17:21:57] [warning] [main.prerequisites.hpp:93] [4950]: qrc:/Dex/Addressbook/EditContactModal.qml:28: TypeError: Cannot read property 'name' of null
[17:22:07] [warning] [main.prerequisites.hpp:93] [4950]: qrc:/Dex/Addressbook/AddAddressForm.qml:253: TypeError: Cannot read property 'addressListModel' of null
[17:22:11] [warning] [main.prerequisites.hpp:93] [4950]: qrc:/Dex/Addressbook/AddAddressForm.qml:253: TypeError: Cannot read property 'addressListModel' of null
```

2. Contact not always saved after ap prestart (Reproduced on Linux/Fedora, Win11)

- Add multiple new contacts to addressbook
- Close App, while still on Adressbook view in app
- Start application anew
- There are no new contacts on addressbook

Leaving adressbook page, changing wallet or any other action before closing app prevents this issue

**Review by SirSevenG — CHANGES_REQUESTED** [review]
^^

**Pull request closed without merging**
