### PR TITLE
Copy linking

### PR DESCRIPTION
**Pull request by smk762**
added link and copy components, applied to swap details modal

### CODE REVIEW

**Comment by tonymorony** [comment]
does it need review @smk762 ? might be worth to set draft state if not yet

**Comment by smk762** [comment]
Should be ready for review, though perhaps will await merge of https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1616/files first as it has modified a lot of files and might be easier for me to handle the conflicts in my PR than for syl to do it in that one.

**Comment by tonymorony** [comment]
there is problem with scrolling it seems (it flickering on my side, especially when scroll from bottom to top):

https://user-images.githubusercontent.com/24797699/155135895-ddaf8d85-1c2b-4c34-9583-4813dff9b6fa.mov

also could you please set the same font for txids part as for other text on this modal?

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by smk762** [comment]
set back to draft - I'd like to expand this to addresses in send modal etc also before further review.

**Comment by smk762** [comment]
closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1607

**Comment by smk762** [comment]
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1409

**Comment by SylEze** [comment]
Some modals are being fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1616 due to recent modal component changes, please wait for https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1616 to be merged: I'll take care of conflcts

(cc. @smk762)

**Pull request closed without merging**
