### PR TITLE
Various error fix

### PR DESCRIPTION
**Pull request by Milerius**
@smk762 please test change currency / fiat on all platform for this pr, let us know the result

### CODE REVIEW

**Comment by smk762** [comment]
Can't get past "enabling coins" on Linux


https://user-images.githubusercontent.com/35845239/118362273-74556080-b5c1-11eb-8c21-9c0375adc069.mp4


Eventually it says "not responding, force quit ?" but there's no console logs past whats in video.

**Comment by smk762** [comment]
also becomes unresponsive on windows. Log ends with
```
[21:20:08] [debug] [app.cpp:343] [14556]: on_coin_fully_initialized_event
[21:20:09] [info] [coingecko.provider.cpp:130] [1800]: nb of parsed market infos is 157 coins
[21:20:09] [info] [qt.portfolio.page.cpp:102] [1800]: Updating portfolio values with model: true
[21:20:09] [debug] [app.cpp:521] [1800]: on_fiat_rate_updated
[21:20:09] [info] [qt.portfolio.model.cpp:102] [1800]: update_currency_values
[21:20:09] [info] [qt.portfolio.model.cpp:152] [1800]: executor done
[21:20:09] [info] [qt.portfolio.model.cpp:149] [1800]: waiting for the executor```

**Comment by smk762** [comment]
Mac also becoming unresponsive.

**Comment by Milerius** [comment]
converted back to a draft for later work

**Pull request closed without merging**
