### PR TITLE
fix(addressbook): Hot fixes

### PR DESCRIPTION
**Pull request by SylEze**
- [ ] Use [QtQuick 2.15 TableView](https://doc.qt.io/qt-5/qml-qtquick-tableview.html) instead of QtQuick.Controls 1.4 TableView (for Qt 6 migration)
- [ ] Add support for BEP-20 addresses
- [x] No more text overflow handled
- [ ] Use validate/convert address from wallet page directly in addressbook frontend
- [ ] Add a fix button for address that need a conversion (same as wallet approach)

### CODE REVIEW

**Comment by smk762** [comment]
Still not seeing BEP-20 as an option in addressbook
image

**Comment by Milerius** [comment]
> Still not seeing BEP-20 as an option in addressbook
> image

@smk762 syl do not use the same approach, the task list he have is the task left before you can start a review

**Comment by smk762** [comment]
There is no overflow in coin type selection, but all languages return English for that selector now.
image

**Comment by Milerius** [comment]
> There is no overflow in coin type selection, but all languages return English for that selector now.
> image

Its normal he changed the text so need you translation, unrelated to the pr

**Pull request merged**
