### PR TITLE
no console logs for release builds

### PR DESCRIPTION
**Pull request by smk762**
Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2171
To test:
- Launch on linux from file manager.
- In console, do `tail -f /var/log/syslog`.
- You should not see any Atomicdex related logs in syslog.
- Confirm launch on Mac and Windows works as expected.

cc: @himu007

### CODE REVIEW

**Comment by tonymorony** [comment]
I believe the problem mentioned in issue was not the logs itself but the fact that logs writing into `syslog` file

what is the QT feature introduced in 0.5.6

https://www.ics.com/blog/whats-new-qt-560-logging-syslog-and-journald

```
To enable the syslog or journald logging support in Qt 5.6.0 or later, you need to configure it into Qt. They default to being disabled, so you need to explicitly use the -journald or -syslog options when running the configure script. If successfully enabled, you should see the relevant output of the configure script indicate it as being enabled, as shown below:

  Logging backends:
    journald ............... yes
    syslog   ............... yes
```

so just logging backend removal is needed

why do we need temp.txt log file?

**Comment by smk762** [comment]
I saw that article when investigating the problem.

>  you need to configure it into Qt. They default to being disabled
App is not configured to write to syslog. 

> you need to explicitly use the -journald or -syslog options when running the configure script.
The strings `syslog` & `journald` do not exist anywhere in the source code, workflows or build scripts.

> why do we need temp.txt log file?
This is a way to get the response returned from https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/core/atomicdex/utilities/kill.cpp#L29 so that `mm2: no process found` wont show up in console / syslog when app tries to kill existing instances of `mm2`. 

More context: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2171#issuecomment-1399162497

**Review by cipig — APPROVED** [review]
this disables console log completely
if that is the intention, then it works
can't tell anything about syslog though, it didn't had that problem on linux myself

**Comment by smk762** [comment]
> can't tell anything about syslog though, it didn't had that problem on linux myself

Did you launch from file manager? If so do you know which one?

**Comment by cipig** [comment]
> Did you launch from file manager? If so do you know which one?

Oh... no, i didn't... just unpacked and started `AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop` from console

**Comment by himu007** [comment]
@smk762 do you have a build file that i can test?

**Comment by cipig** [comment]
Ok, i unzipped on CLI and started with FileManager (which doesn't make that much sense, since it's more work to switch to file manager and click me through till i get to the place where the binary is located... but ok, just to test)
seeing this in syslog
```
Jan 23 17:50:59 Flow-PC systemd[1202]: Started Dolphin - File Manager.
Jan 23 17:51:23 Flow-PC systemd[1202]: Started /home/florian/Tools/AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop.
```
but that's it, nothing more in syslog
btw, you need to do `sudo tail -f /var/log/syslog`, because syslog can't be read by random users, only root can do that

**Comment by himu007** [comment]
@cipig 
> btw, you need to do sudo tail -f /var/log/syslog, because syslog can't be read by random users, only root can do that
my Ubuntu 20.04 Desktop is installed with one 1 user (non-root) account and i can tail the syslog file without `sudo`. It's just the default installation using the desktop ISO file from Ubuntu website without any extra setup/steps.

though it is not possible in my server running Debian, where user setup is same. i am guessing it varies depending on OS/flavor.

**Comment by himu007** [comment]
@smk762 it appears the issue i was seeing is fixed with builds from this PR
only entry in syslog i found after i started the AppImage file is:
```
Jan 23 18:11:48 x org.gnome.Nautilus[209740]: [2023-01-23 18:11:48.306] [info] [global.utilities.cpp:65] creating directory /home/user/.atomic_qt/logs
```
i no longer see the full logs being shown in syslog file.

**Review by SirSevenG — APPROVED** [review]
Haven't seen app logs in syslog here

**Comment by smk762** [comment]
@tonymorony please merge if you are happy with this PR in its current state.

**Review by tonymorony — APPROVED** [review]

**Pull request merged**
