### PR TITLE
Decimal alignment

### PR DESCRIPTION
**Pull request by smk762**
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1665
implemented in:
- simple/pro bestorders lists
- simple "from" coin selection list
- portfolio list
- transactions list.
- orderbook lists

Applied to percentages, fiat amounts and crypto amounts.

### CODE REVIEW

**Comment by Canialon** [comment]
@cipig @smk762   I'm a little unsure about these changes. I think it looks pretty crooked. And my first impression was pretty bad.
Screenshot 2022-04-21 at 15 10 09

**Comment by cipig** [comment]
i like how "Portfolio" looks now:
image

but "Best Orders" tab does not expand any more, so i can't make it to use only one line per entry when coin names are long (like NVC-QRC20):
image

can you place "CEX rate" and "Fiat price" to the right and make "You get" column expand his width in line?

**Comment by cipig** [comment]
found another problem: the sorting in "Portfolio" does not work any more, i can't sort by "Change 24h", this worked before, now it looks like this:
image
same with the other columns, only sorting by "Fiat Balance" works fine

**Comment by smk762** [comment]
should be solved now @cipig

**Comment by cipig** [comment]
thanks, sorting is fixed in "Portfolio"

but:
image
- if width is not big enough, text can overlap in "Best Orders"
- "Price" in "Order Book" is now left-aligned, it was right-aligned before the change

**Comment by smk762** [comment]
image
howzat?

**Review by cipig — APPROVED** [review]

**Review by Canialon — APPROVED** [review]

**Pull request merged**
