### PR TITLE
feat(security): identity verification before sending coins

### PR DESCRIPTION
**Pull request by SylEze**
MacOS: Identity is verified via TouchID or Password authentication

Solves partially https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/544

### CODE REVIEW

**Comment by smk762** [comment]
Confirm password required to send funds - unable to test TouchID as I dont have that on mac mini.

**Comment by Milerius** [comment]
would be nice to sync this one with dev @SylEze

**Comment by Milerius** [comment]
@smk762 please can you test both windows and osx and approve if everything work as expected

**Comment by smk762** [comment]
Working on Mac.
Windows does not accept password, and crashes if clicking outside the password messagebox.
not implemented in linux.

**Comment by smk762** [comment]
No longer crashing in windows when clicking outside modal, but still not accepting my password.

**Comment by smk762** [comment]
Confirm windows is now accepting password and sending funds as expected.
If clicking away from password prompt, no crash, but it goes to background and screen is locked until restoring password prompt and clicking cancel or entering valid password.

**Review by smk762 — APPROVED** [review]

**Pull request merged**
