### PR TITLE
Fix combobox was changing when list changes at 5.15.1

### PR DESCRIPTION
**Pull request by naezith**
Qt changed ComboBox functionality at 5.15.1, however value changes when list is updated and the index stays the same.

Fixing this:
image

If index changes, we know it's user input. 

So,
- if index changes, then value changes, we allow this change.
- if index does not change, but value changes, then we change the index to the old ticker, because we don't want value to change.

### CODE REVIEW

**Review by smk762 — APPROVED** [review]
Confirmed working as expected

**Comment by Milerius** [comment]
Don't merge until the bundle is fixed, @smk762 can you investigate a bit ? the problem seems to come from the CI

**Review by Milerius — CHANGES_REQUESTED** [review]
due to https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-86759

**Comment by naezith** [comment]
Please test the PR at 5.15.0 before reverting.

**Comment by Milerius** [comment]
https://wiki.qt.io/Qt_5.15_Release 5.15.2 release tommorow, let's cross the finger :crossed_fingers: @naezith

**Comment by naezith** [comment]
Qt gods help us.

**Pull request merged**
