### PR TITLE
Confirm modal translations

### PR DESCRIPTION
**Pull request by smk762**
Closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2131

### CODE REVIEW

**Comment by smk762** [comment]
cc: PTYX @SylEze @SirSevenG @ozkanonur can you please assist with native translations for the fee details labels and error warning in the attached issue?

```
Taker tx fee
Dex tx fee
Dex fee
Maker tx fee
Total COIN fees
dPoW protected
Trade price is more than 50% different to CEX! Confirm?
```

**Comment by ozkanonur** [comment]
`%` comes before the number in Turkish standards. So not `value %` but `% value`. Rather than that looks correct.

**Comment by smk762** [comment]
Thanks! There's still a couple of English bits, can you please assist with those?
```
dPoW protected
Trade price is more than 50% different to CEX! Confirm?
```

**Comment by ozkanonur** [comment]
> Thanks! There's still a couple of English bits, can you please assist with those?
> 
> ```
> dPoW protected
> Trade price is more than 50% different to CEX! Confirm?
> ```

- `dPoW korumalı`
- `Takas ücreti CEX ile karşılaştırıldığında %50'den daha fazla sahip. Onaylıyor musunuz?`

**Comment by smk762** [comment]
@SirSevenG Please assist with the required translations to complete the window below:
image

**Comment by smk762** [comment]
@SylEze Please assist with completion of the translations in the window below
image

**Comment by SirSevenG** [comment]
> @SirSevenG Please assist with the required translations to complete the window below:

I would suggest to leave fees as is,

Total COIN fees
`Суммарная коммисия COIN` -- can also leave as is

dPoW protected
`dPoW защита`

Trade price is more than 50% different to CEX! Confirm?
`Стоимость обмена в сравнении с CEX дороже более чем на 50%, вы подтверждаете сделку? `

**Comment by smk762** [comment]
Russian :heavy_check_mark: 
image

German :heavy_check_mark: 
image

Spanish :heavy_check_mark:  
image

Turkish :heavy_check_mark: 
image

English :heavy_check_mark: 
image

French :hourglass_flowing_sand:
image

**Comment by smk762** [comment]
cc: @SylEze ^

**Review by Canialon — APPROVED** [review]

**Review by cipig — APPROVED** [review]

**Pull request merged**
