### PR TITLE
build libwally

### PR DESCRIPTION
**Pull request by smk762**
Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1905

To test: confirm windows binaries work as expected
- create wallet
- addresses/pubkeys/private keys display as expected.
- address validation works as expected.

### CODE REVIEW

**Review by SirSevenG — CHANGES_REQUESTED** [review]
Can't build app on this branch on Windows 11.
Have no issues building from dev branch in the same env.

Fails on command `cmake -DCMAKE_BUILD_TYPE=Release ../ -GNinja`
Logs:
https://pastebin.mozilla.org/Agbja0JY
https://pastebin.mozilla.org/hLSQvMsb
https://pastebin.mozilla.org/aPmSxjRE

Main issue seems to be with pthread:
`/CheckIncludeFile.cxx:1:10: fatal error: 'pthread.h' file not found`

**Comment by tonymorony** [comment]
> https://pastebin.mozilla.org/Agbja0JY

`CMake Error: File D:/WorkDir/atomicDEX-Desktop/wally/wally.dll does not exist.` wally needs to be compiled first

@smk762 I wonder it's compilation needs to be added into `make` process, otherwise app is technically not building now on windows outside of the CI

**Comment by smk762** [comment]
> Can't build app on this branch on Windows 11. Have no issues building from dev branch in the same env.
> 
> Fails on command `cmake -DCMAKE_BUILD_TYPE=Release ../ -GNinja` Logs: https://pastebin.mozilla.org/Agbja0JY https://pastebin.mozilla.org/hLSQvMsb https://pastebin.mozilla.org/aPmSxjRE
> 
> Main issue seems to be with pthread: `/CheckIncludeFile.cxx:1:10: fatal error: 'pthread.h' file not found`

Unfortunately I am currently unable to test building in Win 11 here - both my VM and my physical windows machine are unable to install or update to Windows 11.

In trying to research this problem, I'm not sure it is libwally related - looks like something from the vcpkg submdules
image

Both this branch and dev use the same submodule commits tho, so not sure why one might work and the other won't.

@SirSevenG do the CI binaries work in Windows 11?

**Comment by SirSevenG** [comment]
> do the CI binaries work in Windows 11?
@smk762 They work fine for me.

**Comment by smk762** [comment]
Cheers. Looks like build docs need an update.

**Comment by smk762** [comment]
I think we can merge this one for 0.5.7 RC - it works for CI builds. Build docs still might need a slight update, but we can put that in a different issue.

Please test by confirming launch on Windows from CI binaries (installer & portable) and a basic smoke test (send funds, do swap) + create wallet (it touches on the BIP39 generation). 

This task is lower priority until current airdex sprint is complete.

**Review by SirSevenG — APPROVED** [review]
CI build works with no issues here
Will continue with win11 build and build docs laer.

**Review by Canialon — APPROVED** [review]
lgtm

**Pull request merged**
