### PR TITLE
Addressbook restyle

### LINKED ISSUE #1464: [FEATURE REQUEST]: Addressbook enhancement
Issue placeholder, the goal is to make it closer to figma design

### LINKED ISSUE #1770: Addressbook restyle tweaks 🎉
**Crashing:**
- [x] Found on Windows 10:
1. create any contact 
2. edit this contact -> delete the name, like "", nothing
3. press the "confirm" button
4. edit this contact -> enter any name
6. press the "confirm" button
==> application crashed D':
logs: [2022-05-13-16-08-26.log](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/8689337/2022-05-13-16-08-26.log)

- [x]  When clicking "send" button for smartchain, app crashes. In this case, user should be given a pop-up list of smartchains to complete the selection.

https://user-images.githubusercontent.com/35845239/168439634-e48e4d3c-6301-4e84-91f5-7e51462f786c.mp4

https://user-images.githubusercontent.com/35845239/168439631-58889c80-0f57-4774-97a9-088731b25ef4.mp4

```
[22:16:06] [error] [mm2.service.cpp:501] [35910]: error answer for tx or my_balance: {
    "error": "rpc:211] dispatcher_legacy:160] lp_coins:1419] No such coin: Smart Chain"
}
[22:16:06] [error] [main.prerequisites.hpp:112] [35899]: stacktrace:  0# signal_handler(int) at main.cpp:?
 1# 0x00007F30EB7D50C0 in /lib/x86_64-linux-gnu/libc.so.6
 2# atomic_dex::wallet_page::get_ticker_infos() const in ./atomicdex-desktop
 3# atomic_dex::wallet_page::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) in ./atomicdex-desktop
 4# 0x00007F30EE2719CE in /home/smk762/Downloads/atomicdex-desktop-ubuntu-qt-5-15-2-abook.zip/atomicdex-desktop-linux-0603cb0/AntaraAtomicDexAppDir/usr/bin/../lib/libQt5Qml.so.5
 5# 0x00007F307022DFBF
```

### PR DESCRIPTION
**Pull request by SylEze**
Closes #1464 
Closes #1770

### CODE REVIEW

**Comment by tonymorony** [comment]
@smk762 @Canialon please give this PR one more testing session :)

**Comment by Canialon** [comment]
Wohooo it is Addressbook restyle 🎉 
*****************************

First of all, about the "contact name" field

- I can't start typing immediately after pressing the "+new contact" button
- there is no blinking "|" symbol if you are locating in this field and are able to start typing 

image

And I am a little bit unsure about this way to create a new contact. I mean when I press the "+new contact" button, I expect to see a big window where I can add the name of the contact, and add some address and tags. But now to do that I must create a contact name -> find this contact among other contacts -> press the "edit" button -> and only then I can add some addresses. It's really annoying to do so many steps.
So, is it possible to show the "edit contact" window after pressing the "+new contact" button to avoid unnecessary actions?
*********************************

There is too much empty space, under the contacts with addresses
image
**************************************

Would be cool to add a confirmation window to the "delete" button. Because sometimes users can mix up the "edit" and "delete" buttons. It will be very unpleasant D:
Or just move it to the "edit contact" window
**************************************

1. open the "edit contact" window
2. add any address
3. press confirm
4. look at the contact to which you added a new address -> there is no that address -> you need to reopen the Addressbook tab for the new address to appear

It is worth making it so that the newly created contact immediately appears in the address list
**************************************

There is no problem to remove contact name
image
******************************************

### !!!!!!!
Found on Windows 10:
1. create any contact 
2. edit this contact -> delete the name, like "", nothing
3. press the "confirm" button
4. edit this contact -> enter any name
5. press the "confirm" button
==> application crashed D':

logs:
[2022-05-13-16-08-26.log](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/8689337/2022-05-13-16-08-26.log)


******************************************

1. open the "edit contact" window for any contact 
2. press the "+Add" button -> opened the window to add a new address
3. do not close the "add address" window, just leave it
4. close the "edit contact" window in any way
5. open the "edit contact" window for any other contact 
==> it doesn't matter which contact you want to edit. It will still open a window for the first contact where you have not completed the process of creating a new address
image

**Comment by Canialon** [comment]
- remove assets key
- make tags colorful 
- remove the "no tags" test
- add a background for the "edit address" button
- update the "edit contact" window as it is on Figma
- add horizontal center alignment to elements 

image


image
image

**Comment by smk762** [comment]
- tags background is difficult to see in dark mode
image

- no icon for "smartchain"
image

- When clicking "send" button for smartchain, app crashes. In this case, user should be given a pop-up list of smartchains to complete the selection.

https://user-images.githubusercontent.com/35845239/168429548-27a460e2-921c-42ab-8d17-833c8254e692.mp4

https://user-images.githubusercontent.com/35845239/168430492-a71ac456-24e1-455e-962c-47c1a12eb9eb.mp4

```
[22:16:06] [error] [mm2.service.cpp:501] [35910]: error answer for tx or my_balance: {
    "error": "rpc:211] dispatcher_legacy:160] lp_coins:1419] No such coin: Smart Chain"
}
[22:16:06] [error] [main.prerequisites.hpp:112] [35899]: stacktrace:  0# signal_handler(int) at main.cpp:?
 1# 0x00007F30EB7D50C0 in /lib/x86_64-linux-gnu/libc.so.6
 2# atomic_dex::wallet_page::get_ticker_infos() const in ./atomicdex-desktop
 3# atomic_dex::wallet_page::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) in ./atomicdex-desktop
 4# 0x00007F30EE2719CE in /home/smk762/Downloads/atomicdex-desktop-ubuntu-qt-5-15-2-abook.zip/atomicdex-desktop-linux-0603cb0/AntaraAtomicDexAppDir/usr/bin/../lib/libQt5Qml.so.5
 5# 0x00007F307022DFBF
```
- Smartchain / BEP20 / ERC20 etc options not visible in address selection drop down. If editing a "smart address" entry, the dropdown reverts to LTC.

https://user-images.githubusercontent.com/35845239/168433329-8a5139f9-4cb4-481a-8d30-c35d8d3bdf5d.mp4

- Spacing between addressbook entries could be reduced (see above video and space between hovered backgrounds)

- Unexpected behaviour when using send button on coins which are not enabled. In this case, I would expect a pop up to enable the coin, and if cancelling the enable, it should not appear as the selected coin in wallet screen afterwards.

https://user-images.githubusercontent.com/35845239/168429703-5c9fe088-287f-44c2-b2b3-164d780b97f3.mp4

- No "do you confirm" pop up when clicking "delete"" for a contact.

https://user-images.githubusercontent.com/35845239/168429779-96d42905-53c8-4af4-a60f-fc9517c6490a.mp4

- Button text too short - we should have this say "add address"
image

- Add "tag button" should have same  styling color as add/close buttons (incl on hover)

**General impression of layout:**
      -  There is dead space which could be freed up to make the scrollable address list area taller.
image

- Contact name input would be nice to use similar to the notes input on sent transactions:
image

- Rather than an "+ Add" button below the scrollable, address list, we could make a small `+` button to the right of the `Address list` title. Same applies for the `Tags` title. These changes would almost double the available space for the scrollable address list area. 

- A slight change to background color of address list area like below might be a good idea, along with a "There are no saved addresses for this contact" message if no addresses in list. Same for tags area, along with a `no tags for this contact` message if no tags are set. Similar to below:

image

- it would be cool to be able to add addresses to the addressbook via a button next to addresses on transaction details modal (see above).

- This input gives no indicator when focused (i.e. blinking cursor or slight background / border change)

image

- Error message would be good to be centered between buttons and inputs, and perhaps center aligned.

image

- Edit state is not reset when switching contacts
image

- coin selection dropdown might benefit from slightly different background and adding a search field.
image

- contact address list not shown in main screen after adding (If switching tabs to wallet and back, they are seen)

https://user-images.githubusercontent.com/35845239/168432044-3df6a61f-d15a-4d8c-8d4a-8b34c9d1338b.mp4

- Address input fields should be renamed to `Label` and `Address`. using "field" and "key" might confuse grandma.

- The `Label: Address` format used on main age could also be used on the edit contact page. This would allow for more addresses visible in the scrolling area. A space should be added after the `:` to allow for wordwrap if long label/address needing extra line.

image
image

- Do we need the extra space below the addresses here?
image

**Comment by SylEze** [comment]
> * coin selection dropdown might benefit from slightly different background and adding a search field.
>       image

https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1770#issuecomment-1127269654

**Comment by smk762** [comment]
A bit of a clash here
image
Would be good to add some spacing between buttons and form (or include buttons in the darker background area).

Error in logs when click "add" button for new address input
`[19:21:00] [warning] [main.prerequisites.hpp:92] [550098]: qrc:/Dex/Addressbook/AddAddressForm.qml:36: ReferenceError: API is not defined`

**Comment by smk762** [comment]
Need  little more spacing under the combobox. too much spacing under address input
image

expanded box perhaps too big when only a few coins to select. smaller font for "use standard network address" so it fits on 2 lines.
image

Error message could be reduced to omit the bits before the second `]`. When error is 2 lines, buttons almost outside box.
Error text persists when adding second address after successful entry.
image

Unable to select coins that are not enabled (optional fr: make like bestorders with fade and option to enable on click). If QTUM not enabled, I can still attempt to add a QRC-20 address, but will get a validation error.
image

After confirming entries, main screen shows "no registered addresses". This does not update until going to other tab (e.g. wallet) and then back.
https://user-images.githubusercontent.com/35845239/172281479-8c5a1938-5327-4147-bd5e-06ce202e32a8.mp4

Might be good to have sight different background for the contact address list area (example below):
image

Addressbook entries not visible after restarting app. Seems cause of this was wallet name existing as folder (from previous builds, folder was datestamped almost 1 year ago). Not a problem for this PR, but noting for potential future support queries.
```[10:22:52] [warning] [main.prerequisites.hpp:92] [2565789]: QIODevice::read (QFile, "/home/smk762/.atomic_qt/addressbook/jobb"): device not open
[10:22:52] [warning] [addressbook.cfg.cpp:48] [2565789]: Addressbook config file was invalid, use empty configuration: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal. Content was: 
```
After deleting folder, everything fine - new file created, entries visibile on subsequent starts.

**Comment by SylEze** [comment]
> Error message could be reduced to omit the bits before the second `]`. When error is 2 lines, buttons almost outside box.
> Error text persists when adding second address after successful entry.
> image

I'm sure this one also occurs in the send modal or in every other part where we need to validate an address: we should make an issue to sanitize those error messages

**Comment by smk762** [comment]
- Spacing of form elements looks ok now.

- Search bar would be good here
image

- unable to select saved smart address from send modal
https://user-images.githubusercontent.com/35845239/172769590-df8d8f0b-d2ff-4b80-94b0-488459b87762.mp4




l

**Comment by SylEze** [comment]
> * unable to select saved smart address from send modal
>       https://user-images.githubusercontent.com/35845239/172769590-df8d8f0b-d2ff-4b80-94b0-488459b87762.mp4

By just looking at the code, this bug was already present in the previous addressbook version... Unfortunately the current backend design do not allow to filter contact addresses linked to a network standard, it will require models reworking

This brings us to something we will need to implement in next versions: some models (e.g. coins model) in the backend are poorly designed for our current needs and some are still missing (e.g. network standard model), they will need a new implementation. 
A lot of stuff related to asset network standards have been hardcoded in the frontend in several places. When we will add a new one it will not be so trivial.

**Comment by SylEze** [comment]
A lot of stuff related to asset network standards have been hardcoded in the frontend in several places. When we will add a new one it will not be so trivial.

This brings us to something we will need to implement in next patches: some models (e.g. coins model) in the backend are poorly designed for our current needs and some are still missing (e.g. network standard model)

**Comment by smk762** [comment]
Seen when clicking "edit" for a contact.
`[19:51:29] [warning] [main.prerequisites.hpp:92] [2083955]: qrc:/Dex/Addressbook/AddAddressForm.qml:114:13: QML AddressTypeSelector: Binding loop detected for property "implicitHeight"`

When adding coin/address entry, there is no "default selection" in dropdown (is blank)
image

A little overlap detected here 
image

"Use custom fees" text seems to have gone missing. Also happens when sending from wallet page.
image

**Review by smk762 — APPROVED** [review]
Looking good thanks :)

**Pull request merged**
