### PR TITLE
feat(matic): add matic support - spare task

### PR DESCRIPTION
**Pull request by Milerius**
test wallet functionality for:

- Matic (history should work for this one)
- Optimism Testnet
- Arbitrum Testnet

test swaps for:

- Matic against BEP20
- Matic against UTXO
- Matic against Matic
- Matic against QRC20
- Matic against SmartChain

Swaps doesn't work for arbitrum/optimism right now

todo:

- All the front end filtering for those 3 new protocols, addressbook etc @SylEze only if you have time
- @smk762 you can dm me your matic address and I can send you one matic for the testing.

### CODE REVIEW

**Comment by smk762** [comment]
- Received to wallet :heavy_check_mark: 
- Send from wallet works, but view in explorer button leads to bad url for the tx (missing 0x prefix). :orange_circle: 
- Link to view tx from history operates as expected. :heavy_check_mark: 
- tx history displays correctly on wallet page

Swaps:
- Matic against BEP20 swap fails if trying to swap max, swap successful with less than max `taker_swap:745] !check_balance_for_taker_swap check_balance:76] Not enough MATIC for swap: available 0.5, required at least 0.5001599, locked by swaps Some(BigDecimal("0"))` Not enough for fees :orange_circle: 
- Matic against Matic unable to buy MATICTEST for MATIC if no MATICTEST balance. Swap completed ok once balance for fees present.
- Matic against QRC20 - Unable to swap when attempting to buy QTUM (no balance for fees error). I switched over to 0.5.1 and could swap QTUM with no balance. Suspect issue or bug with the MM2 version used in this build. After sending funds into wallet, swap failed to match :-1: 
- Matic against SmartChain failed to match :-1: 
- Matic against UTXO failed to match :-1:

**Comment by smk762** [comment]
Matic against AVAX - swap successful :heavy_check_mark:

**Comment by smk762** [comment]
Matic against FTMT - swap successful :heavy_check_mark:
RICK against FTMT - swap successful :heavy_check_mark:
BEP20 against FTMT - swap successful :heavy_check_mark:
MATIC against AVAX - swap successful :heavy_check_mark:
RICK against AVAX - swap successful :heavy_check_mark:

**Comment by smk762** [comment]
Avax tx url when clicking on "swap details > show in explorer" is broken

**Comment by Milerius** [comment]
I think we can merge this one @tonymorony - we can do the front-end into a separate pr.

**Review by tonymorony — CHANGES_REQUESTED** [review]
> I think we can merge this one @tonymorony - we can do the front-end into a separate pr.

result of our testing session: 
HECO works fine
moonriver doesn't work on my side


also, I think it's better to use links only to GH releases build in secure env in dev/master branches of GUI to avoid problems (rn it changes API bins links to dev env)

**Comment by Milerius** [comment]
Capture d’écran 2021-09-29 à 09 25 41

**Pull request merged**
