### PR TITLE
Fix notif not updated on lang change

### LINKED ISSUE #2086: [enhancement]: Notifications do not change language on locale switch
**Describe the bug**
Notifications received keep the locale/language they were generated with.
notifications_locale_same

1. Login to wallet, select locale A
2. make a swap/a few transactions to generate notifications
3. switch to a different locale
4. Open notifications dropdown
5. Dropdown button has new locale, yet notification themselves keep the previous language

### PR DESCRIPTION
**Pull request by SylEze**
Closes #2086 

Please test every events handled by the NotificationsManager:
Capture d’écran 2022-11-24 à 4 33 00 PM

Please note that `onBatchFailed` and `onMismatchCustomCoinConfiguration` are never triggered from the backend (we should remove them?) and are therefore not testable atm.

### CODE REVIEW

**Comment by smk762** [comment]
Unless we have need for them, cleaning it out is probably a good idea.
`onMismatchCustomCoinConfiguration` shouldn't happen anyway and if/when we implement https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2103 it won't.

**Comment by smk762** [comment]
updateSwapStatus
balanceUpdateStatus
enablingZcoinStatus
enablingCoinFailedStatus

**Comment by smk762** [comment]
- [ ] updateSwapStatus
- [ ] balanceUpdateStatus
- [ ] enablingZcoinStatus
- [ ] enablingCoinFailedStatus
- [ ] disablingCoinFailedStatus
- [ ] endpointNonReachableStatus

**Comment by SylEze** [comment]
> `enablingZcoinStatus` and `disablingCoinFailedStatus` seems to be in English regardless of chosen language, probably it needs translations file updates.

Yeah translations are unfinished

**Review by smk762 — APPROVED** [review]
I checked the code and indeed we are missing translations for the title of those notifications (for zhtlc body text like `ActivatingCoin` this is direct from API so it is not in the .ts files).

These translation fixes can be addressed in a separate PR

**Review by Canialon — APPROVED** [review]

**Pull request merged**
