### PR TITLE
Add LightningCash (LNC)

### PR DESCRIPTION
**Pull request by MerlinMagic2018**
LightningCash has been launched on March 6th 2019

I would be very happy if my coin would be integrated !

It is fully compatible.

https://bitcointalk.org/index.php?topic=5117428

### CODE REVIEW

**Comment by smk762** [comment]
coins repo ref: https://github.com/KomodoPlatform/coins/pull/487 
await merge of above before review here

**Comment by MerlinMagic2018** [comment]
I have done the swap
Ready to merge :
https://github.com/KomodoPlatform/coins/pull/487

**Comment by MerlinMagic2018** [comment]
I also synced to KomodoPlatform:dev branch and added a second electrumx server

**Comment by smk762** [comment]
Testing the second electrum returns `connection refused` at the moment. Please confirm port is correct and allowed thru firewall.

You can test it with 
`(echo '{ "id": 1, "method": "blockchain.headers.subscribe", "params": [] }'; sleep 0.5) | ncat 74.56.11.23 50001 | jq`
from a different machine to confirm.

**Comment by MerlinMagic2018** [comment]
Its down, Im on my cellphone but hey...

Termius ---> ssh

It wont take long

**Comment by MerlinMagic2018** [comment]
(echo '{ "id": 1, "method": "blockchain.headers.subscribe", "params": [] }'; sleep 0.5) | ncat 74.208.95.26 50001 | jq && (echo '{ "id": 1, "method": "blockchain.headers.subscribe", "params": [] }'; sleep 0.5) | ncat 74.56.11.23 50001 | jq


They are both up right now.

**Pull request merged**
