### PR TITLE
fix(fix_chart_line): set to chart line default color

### PR DESCRIPTION
**Pull request by ssakone**

### CODE REVIEW

**Comment by tonymorony** [comment]
image

the dot does not on the graph mostly - could you please try to fix that?

Screenshot 2021-04-20 at 15 33 05

also, grey axes labels (numbers and dates) not well visible on a dark background - could you please try to make it white and in white theme keep it the same color as now?

**Comment by ssakone** [comment]
ok

> 
> 
> image
> 
> the dot does not on the graph mostly - could you please try to fix that?
> 
> Screenshot 2021-04-20 at 15 33 05
> 
> also, grey axes labels (numbers and dates) not well visible on a dark background - could you please try to make it white and in white theme keep it the same color as now?

ok

**Comment by smk762** [comment]
also noticed some weirdness with the dot and date. dot seems to drop below line on todays date, and tooltip date reverts to jan1 outside chart 

https://user-images.githubusercontent.com/35845239/115394091-fcd81f80-a214-11eb-98ee-738356a1a58a.mp4

**Comment by smk762** [comment]
found some value overflow when in minimized mode with a large balance on dex screen
image

**Comment by tonymorony** [comment]
> found some value overflow when in minimized mode with a large balance on dex screen
> image

good catch, @smk762 could you please create a separate issue for this one?

**Comment by tonymorony** [comment]
outstanding things related to the graph at the moment [ CC @ssakone ]: 

1) values pointing not limited on the left edge

Screenshot 2021-04-20 at 22 13 22

2) would be great to ensure that vertical line is inside the graph borders:
Screenshot 2021-04-20 at 22 15 47

**Comment by ssakone** [comment]
ok

**Review by Milerius — APPROVED** [review]

**Pull request merged**
