### PR TITLE
Translations tweaks

### PR DESCRIPTION
**Pull request by smk762**
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2089

I also filled in a few other missing translations (mostly Spanish) for items added since old translations were done - though there is still around 600 translations missing total between French, German, Russian and Turkish.

@ozkanonur @SirSevenG can you please check the "I understand" validation on wallet import works correctly for Turkish/Russian? 

Seems ok here, but I'm not 100% sure because not familiar enough with different alphabet etc. 

https://user-images.githubusercontent.com/35845239/202374239-dfbeb66c-e977-4bb2-b365-c74bbcded160.mp4

### CODE REVIEW

**Comment by ozkanonur** [comment]
I think 'Anladım' suits better than 'Anlıyorum'.

'Anlıyorum' means more like 'I see', where 'Anladım' declares if you understand the stuff or not.

**Comment by smk762** [comment]
> I think 'Anladım' suits better than 'Anlıyorum'.
> 
> 'Anlıyorum' means more like 'I see', where 'Anladım' declares if you understand the stuff or not.

Thanks, updated. Will be in https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/3486546663

**Comment by SirSevenG** [comment]
> can you please check the "I understand" validation on wallet import works correctly for Turkish/Russian?

"Я понимаю" is the literal translation to "I understand", i'd choose a different wording and maybe "I accept [this]" - "Я согласен" would be better. But it's fine as is.

**Comment by smk762** [comment]
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2089 also

**Review by SirSevenG — APPROVED** [review]
lgtm

**Review by Canialon — APPROVED** [review]

**Pull request merged**
