### PR TITLE
Slp tokens

### LINKED ISSUE #1168: SLP tokens integration.
Coins PR with corresponding configs: https://github.com/KomodoPlatform/coins/pull/298
MM2 branch: https://github.com/KomodoPlatform/atomicDEX-API/tree/mm2.1-slp-swap
Activation commands examples are in this diff: https://github.com/KomodoPlatform/atomicDEX-API/commit/b9a4c28ca77a1458012d72f49262418a969d11f1

Important notes:
1. Tx history is not implemented for SLP tokens yet. Enable request will return an error if it contains `tx_history:true`.
2. The platform coin (tBCH) must be activated before the SLP tokens enabling attempt. If tBCH is not activated MM2 will return an error.
3. Please ensure that tBCH has `BCH` protocol type as per https://github.com/KomodoPlatform/coins/pull/298/files#diff-62f014cb316258f89133bb263f1fa74f85b308430765a403fbc87e20b367c959R5620. If it doesn't MM2 may burn SLP tokens belonging to the users' address.

### PR DESCRIPTION
**Pull request by SylEze**
Closes #1168 
Should help with the resolution of #1897

Only tBCH and sTST are available for the moment

**Don't forget to reset your assets config**

Things that should be tested (tick/untick if something is not working properly, edit if something is missing):
- [x] Enabling tBCH
- [x] Enabling sTST when tBCH is enabled
- [x] Enabling sTST when tBCH is not enabled should enable tBCH
- [x] Enabling tBCH after disabling it
- [x] Enabling sTST after disabling it
- [x] Disabling tBCH
- [x] Disabling sTST
- [x] Disabling tBCH when sTST is not enabled should disable sTST
- [x] Send tBCH
- [x] Send sTST
- [x] Receive tBCH
- [x] Receive sTST
- [x] sTST and tBCH transactions history
- [x] Other coins transactions history
- [ ] Swaps between tBCH and other coins
- [ ] Swaps between sTST and other coins
- [ ] Swaps between tBCH and sTST
- [x] Swaps between USDF and tBCH
- [ ] Swaps between USDF and other coins
- [x] Enable USDF
- [x] Disable USDF

### CODE REVIEW

**Comment by smk762** [comment]
- ASLP/HONK not enabling.
- No tx history for tBCH or USDF
- Balance and send/recieve ok for tBCH and USDF
 - Disabling is weird. I can't disable USDF most of the time. Somehow tBCH acts like a default coin (reappears after disable and logout). Also got this weird error message a couple of times.
 
image

The only log errors I can see are below - 
```
[00:42:34] [info] [mm2.service.cpp:123] [1651064]: Update coins status to: true - field_name: active - tickers: tBCH
[00:42:34] [error] [mm2.client.cpp:180] [1651096]: [json.exception.type_error.302] type must be string, but is object
[00:42:34] [info] [mm2.service.cpp:160] [1651064]: ticker: tBCH status active: true
```

and I saw this once when trying to disable tBCH, but couldn't see it later
`[00:27:20] [error] [mm2.service.cpp:893] [1642306]: exception in batch_balance_and_tx: [json.exception.out_of_range.403] key 'coin' not found`

@SylEze if you have spare test coins or links to faucets pls post in this thread. I got enough tBCH, and a little USDF dust but no sTST

**Comment by tonymorony** [comment]
@SylEze I've merged in ARRR PR so now there are conflicts

**Comment by cipig** [comment]
getting this crash when i start ADEX from this branch:
```
[14:16:41] [info] [mm2.service.cpp:216] [3586283]: Retrieving Wallet information of /home/florian/.atomic_qt/config/0.5.6-coins.cipinew.json
[14:16:41] [error] [mm2.service.cpp:232] [3586283]: exception caught: Undefined given coin type.
[14:16:41] [info] [qt.global.coins.cfg.model.cpp:210] [3586283]: Initializing global coin cfg model with size 1
[14:16:41] [info] [global.provider.cpp:443] [3586283]: Forcing update providers
[14:16:41] [info] [qt.addressbook.page.cpp:66] [3586283]: post_login: filling addressbook from cfg
[14:16:41] [info] [addressbook.cfg.cpp:44] [3586283]: Addressbook configuration file read.
[14:16:41] [warning] [qt.addressbook.proxy.filter.model.cpp:79] [3586283]: No filter behavior on role 259
[14:16:41] [info] [main.prerequisites.hpp:90] [3586283]: Success: Login
[14:16:41] [info] [global.provider.cpp:105] [3586316]: refresh_other_coins_rates - try 1
[14:16:41] [info] [global.provider.cpp:105] [3586316]: refresh_other_coins_rates - try 1
[14:16:41] [info] [global.provider.cpp:105] [3586316]: refresh_other_coins_rates - try 1
[14:16:41] [info] [global.provider.cpp:482] [3586316]: Successfully retrieving rate after 1 try
[14:16:41] [warning] [coinpaprika.hpp:103] [3586313]: rpc answer code is 400 (Bad Parameters), body: {"error":"invalid parameters"}

[14:16:41] [info] [global.provider.cpp:140] [3586313]: Successfully get the coinpaprika::api::async_price_converter answer after 1 try
[14:16:41] [warning] [coinpaprika.hpp:103] [3586318]: rpc answer code is 400 (Bad Parameters), body: {"error":"invalid parameters"}

[14:16:41] [info] [global.provider.cpp:140] [3586318]: Successfully get the coinpaprika::api::async_price_converter answer after 1 try
[14:16:41] [warning] [coinpaprika.hpp:103] [3586321]: rpc answer code is 400 (Bad Parameters), body: {"error":"invalid parameters"}

[14:16:41] [info] [global.provider.cpp:140] [3586321]: Successfully get the coinpaprika::api::async_price_converter answer after 1 try
[14:16:42] [info] [mm2.service.cpp:1582] [3586375]: mm2 is initialized
[14:16:42] [debug] [app.cpp:541] [3586375]: on_mm2_initialized_event l541
[14:16:42] [info] [qt.wallet.manager.cpp:343] [3586375]: Set status: enabling_coins
[14:16:42] [error] [mm2.service.cpp:720] [3586375]: BCH is not present in the config. Cannot enable SLP tokens.
[14:16:42] [error] [main.prerequisites.hpp:107] [3586375]: sigabort received, cleaning mm2
[14:16:42] [info] [main.prerequisites.hpp:90] [3586283]: Current font changed to Ubuntu.
[14:16:43] [error] [main.prerequisites.hpp:113] [3586375]: stacktrace:  0# signal_handler(int) at main.cpp:?
 1# 0x00007FF323607D60 in /lib/x86_64-linux-gnu/libc.so.6
 2# void entt::dispatcher::pool_handler<atomic_dex::enabling_coin_failed>::trigger<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const* const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const* const&) in AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop
 3# atomic_dex::mm2_service::enable_slp_coins(std::vector<atomic_dex::coin_config, std::allocator<atomic_dex::coin_config> > const&) in AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop
 4# atomic_dex::mm2_service::enable_coins(std::vector<atomic_dex::coin_config, std::allocator<atomic_dex::coin_config> > const&) in AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop
 5# atomic_dex::mm2_service::enable_default_coins() in AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop
 6# std::thread::_State_impl<std::thread::_Invoker<std::tuple<atomic_dex::mm2_service::spawn_mm2_instance(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)::$_21> > >::_M_run() at mm2.service.cpp:?
 7# 0x00007FF3239BDED0 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 8# 0x00007FF32FBAFEA7 in /lib/x86_64-linux-gnu/libpthread.so.0
 9# clone in /lib/x86_64-linux-gnu/libc.so.6

[14:16:43] [warning] [main.prerequisites.hpp:93] [3586375]: QObject::~QObject: Timers cannot be stopped from another thread
[14:16:43] [warning] [main.prerequisites.hpp:93] [3586375]: QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by SylEze** [comment]
> getting this crash when i start ADEX from this branch:
> 
> ```
> [14:16:41] [info] [mm2.service.cpp:216] [3586283]: Retrieving Wallet information of /home/florian/.atomic_qt/config/0.5.6-coins.cipinew.json
> [14:16:41] [error] [mm2.service.cpp:232] [3586283]: exception caught: Undefined given coin type.
> [14:16:41] [info] [qt.global.coins.cfg.model.cpp:210] [3586283]: Initializing global coin cfg model with size 1
> [14:16:41] [info] [global.provider.cpp:443] [3586283]: Forcing update providers
> [14:16:41] [info] [qt.addressbook.page.cpp:66] [3586283]: post_login: filling addressbook from cfg
> [14:16:41] [info] [addressbook.cfg.cpp:44] [3586283]: Addressbook configuration file read.
> [14:16:41] [warning] [qt.addressbook.proxy.filter.model.cpp:79] [3586283]: No filter behavior on role 259
> [14:16:41] [info] [main.prerequisites.hpp:90] [3586283]: Success: Login
> [14:16:41] [info] [global.provider.cpp:105] [3586316]: refresh_other_coins_rates - try 1
> [14:16:41] [info] [global.provider.cpp:105] [3586316]: refresh_other_coins_rates - try 1
> [14:16:41] [info] [global.provider.cpp:105] [3586316]: refresh_other_coins_rates - try 1
> [14:16:41] [info] [global.provider.cpp:482] [3586316]: Successfully retrieving rate after 1 try
> [14:16:41] [warning] [coinpaprika.hpp:103] [3586313]: rpc answer code is 400 (Bad Parameters), body: {"error":"invalid parameters"}
> 
> [14:16:41] [info] [global.provider.cpp:140] [3586313]: Successfully get the coinpaprika::api::async_price_converter answer after 1 try
> [14:16:41] [warning] [coinpaprika.hpp:103] [3586318]: rpc answer code is 400 (Bad Parameters), body: {"error":"invalid parameters"}
> 
> [14:16:41] [info] [global.provider.cpp:140] [3586318]: Successfully get the coinpaprika::api::async_price_converter answer after 1 try
> [14:16:41] [warning] [coinpaprika.hpp:103] [3586321]: rpc answer code is 400 (Bad Parameters), body: {"error":"invalid parameters"}
> 
> [14:16:41] [info] [global.provider.cpp:140] [3586321]: Successfully get the coinpaprika::api::async_price_converter answer after 1 try
> [14:16:42] [info] [mm2.service.cpp:1582] [3586375]: mm2 is initialized
> [14:16:42] [debug] [app.cpp:541] [3586375]: on_mm2_initialized_event l541
> [14:16:42] [info] [qt.wallet.manager.cpp:343] [3586375]: Set status: enabling_coins
> [14:16:42] [error] [mm2.service.cpp:720] [3586375]: BCH is not present in the config. Cannot enable SLP tokens.
> [14:16:42] [error] [main.prerequisites.hpp:107] [3586375]: sigabort received, cleaning mm2
> [14:16:42] [info] [main.prerequisites.hpp:90] [3586283]: Current font changed to Ubuntu.
> [14:16:43] [error] [main.prerequisites.hpp:113] [3586375]: stacktrace:  0# signal_handler(int) at main.cpp:?
>  1# 0x00007FF323607D60 in /lib/x86_64-linux-gnu/libc.so.6
>  2# void entt::dispatcher::pool_handler<atomic_dex::enabling_coin_failed>::trigger<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const* const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const* const&) in AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop
>  3# atomic_dex::mm2_service::enable_slp_coins(std::vector<atomic_dex::coin_config, std::allocator<atomic_dex::coin_config> > const&) in AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop
>  4# atomic_dex::mm2_service::enable_coins(std::vector<atomic_dex::coin_config, std::allocator<atomic_dex::coin_config> > const&) in AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop
>  5# atomic_dex::mm2_service::enable_default_coins() in AntaraAtomicDexAppDir/usr/bin/atomicdex-desktop
>  6# std::thread::_State_impl<std::thread::_Invoker<std::tuple<atomic_dex::mm2_service::spawn_mm2_instance(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)::$_21> > >::_M_run() at mm2.service.cpp:?
>  7# 0x00007FF3239BDED0 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
>  8# 0x00007FF32FBAFEA7 in /lib/x86_64-linux-gnu/libpthread.so.0
>  9# clone in /lib/x86_64-linux-gnu/libc.so.6
> 
> [14:16:43] [warning] [main.prerequisites.hpp:93] [3586375]: QObject::~QObject: Timers cannot be stopped from another thread
> [14:16:43] [warning] [main.prerequisites.hpp:93] [3586375]: QObject::~QObject: Timers cannot be stopped from another thread
> ```

The coins cfg had wrong entries for asset's type. When it does not recognize an asset type it just throws an exception. You got a crash because the file parsing did not return anything. 
Please manually reset your cfg inside your folders

Sorry for the inconvenience

@cipig

**Comment by smk762** [comment]
- enabling coins ok (BCH /tBCH / SLP)
- send/receive ok for USDF
- explorer link ok from history and after tx
- SLP coins in addressbook, and can filter to see only SLP. 
- no related entry in "use standard network address" option for SLP
- addressbook address validation fails for `slptest:` addresses, and error overflows visible area
image

- USDF still strangely wont disable. Nothing stand out in logs to indicate why.

@Canialon @SirSevenG ping me to test swapping when you are online.

**Comment by smk762** [comment]
Activation looks rock solid now (except eth/erc20 but that's a network infra issue). thanks!
Disabling USDF now works again.
Addressbook issues from last comment still exist.

**Review by smk762 — APPROVED** [review]
Working as expected here, congrats @syl :)
Addressbook error text persistence is in dev too, will move that to a new issue.

**Review by Canialon — APPROVED** [review]
image

**Review by SirSevenG — APPROVED** [review]

**Pull request merged**
