### PR TITLE
Add ILNSW

### PR DESCRIPTION
**Pull request by smk762**
merged other relates PRs into here

### CODE REVIEW

**Comment by smk762** [comment]
Awaiting merge of https://github.com/KomodoPlatform/coins/pull/479 before this can be merged.

**Comment by tonymorony** [comment]
> 

merged https://github.com/KomodoPlatform/coins/pull/479

**Comment by smk762** [comment]
> > Awaiting merge of [KomodoPlatform/coins#479](https://github.com/KomodoPlatform/coins/pull/479) before this can be merged.
> 
> merged [KomodoPlatform/coins#479](https://github.com/KomodoPlatform/coins/pull/479)

thanks, I kicked off a rerun of the CI so it will grab latest coins file

**Comment by tonymorony** [comment]
@smk762 was you manage to activate this asset? (I've tried latest artefact and also built locally)

image

**Comment by cipig** [comment]
this line is wrong: https://github.com/KomodoPlatform/coins/blob/master/coins#L4510
ILSW, but should be ILNSW, or not?

**Pull request merged**
