### PR TITLE
0.5.6

### PR DESCRIPTION
**Pull request by ca333**
### Release Notes 

**Features:** 

* 📖  Updated Address Book Management https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1741
* 🎨  Updated Calendar Style https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1780
* 🔑  Show Public Key (MCL/TOKEL) https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1714
* 🔐  Added refund countdown timer https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1716
* 🐺  Improved update checking https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1777
* :moneybag:  Add the following utxo coins: `PND`, `RUNES`
* :moneybag:  Add the following BEP-20 tokens: `BLK`, `GMT`, `GST`, `ILN`, `SAND`, `VET`, `WAVES`, `MANA`
* :moneybag:  Add the following ERC-20 tokens: `APE`, `EILN`, `PPC`, `SAND`
* :moneybag:  Add the following PLG-20 tokens: `PPC`, `ILN`, `SAND`

**Enhancements:**

* 📈  Add [Nomics](https://nomics.com/exchanges/atomicdex) charts https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1789
* 🆙  Misc design updates https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1561
* :magnet: Autofocus on search and other primary inputs https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1806
* 🤑  Show which protocol is being traded in order form https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1788
* 🇫🇷  Updated translations approach https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1783
* 🔐  Improved QRC compilation https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1734
* 🧑‍🏫  Change Support page to a modal https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1751
* 🔣  Improved error messaging https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1723 https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1705 https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1676
* 🧹  General code cleaning
* 🖥️  Misc visual improvements
 

**Fixes:**

* :rescue_worker_helmet:  Trim header spaces in CSV exports https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1689
* :rescue_worker_helmet:  Update dependancies for CI (libtool, ifw)
* 📸 Optimize coin icon image profiles

### CODE REVIEW

**Comment by tonymorony** [comment]
@smk762 @SirSevenG please perform the full regression testing session on this RC

**Review by SirSevenG — DISMISSED** [review]
We've found a few minor visual bugs, like text overflows and stuff.
Yet no big issues or bugs that affect core functions of the app.
So i'd say it's good enough for release.

**Review by tonymorony — CHANGES_REQUESTED** [review]
version needs to be bumped to 0.5.6
e.g.
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/assets/config/0.5.5.1-coins.json
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/CMakeLists.txt#L14
and etc.

**Review by SirSevenG — APPROVED** [review]
lgtm

**Review by tonymorony — APPROVED** [review]

**Pull request merged**
