### PR TITLE
Remove boost::filesystem references

### PR DESCRIPTION
**Pull request by SylEze**
boost::filesystem is not needed anymore since filesystem features are now implemented in every common c++ compiler std library

This PR gives some changes to the CI to use 10.15 macOS SDK

### CODE REVIEW

**Review by SirSevenG — DISMISSED** [review]

**Comment by smk762** [comment]
I still see some build errors actions logs

https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/3549793097/jobs/5962556831#step:20:1483
`usr/include/c++/10/bits/fs_fwd.:39: Parse error at "std"`
&
```
2022-11-25T17:41:21.2682009Z AutoMoc subprocess error
2022-11-25T17:41:21.2682559Z ------------------------
2022-11-25T17:41:21.2682869Z The moc process failed to compile
2022-11-25T17:41:21.2683276Z   "SRC:/src/core/atomicdex/services/update/zcash.params.service.hpp"
2022-11-25T17:41:21.2683634Z into
2022-11-25T17:41:21.2684602Z   "SRC:/ci_tools_atomic_dex/build-Debug/src/atomicdex-desktop_autogen/NVWMQ4ZM6I/moc_zcash.params.service.cpp"
```

https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/3549793097/jobs/5962556905#step:19:1251 and other places
```
2022-11-25T18:03:02.5687170Z /Users/runner/work/atomicDEX-Desktop/atomicDEX-Desktop/src/core/atomicdex/utilities/global.utilities.hpp:39:63: fatal error: 'path' is unavailable: introduced in macOS 10.15
2022-11-25T18:03:02.5688380Z     bool        create_if_doesnt_exist(const std::filesystem::path& path);
2022-11-25T18:03:02.5689120Z                                                               ^
2022-11-25T18:03:02.5690270Z /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:738:24: note: 'path' has been explicitly marked unavailable here
2022-11-25T18:03:02.5691280Z class _LIBCPP_TYPE_VIS path {
```

**Comment by SylEze** [comment]
> I still see some build errors actions logs
> 
> https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/3549793097/jobs/5962556831#step:20:1483 `usr/include/c++/10/bits/fs_fwd.:39: Parse error at "std"` &
> 
> ```
> 2022-11-25T17:41:21.2682009Z AutoMoc subprocess error
> 2022-11-25T17:41:21.2682559Z ------------------------
> 2022-11-25T17:41:21.2682869Z The moc process failed to compile
> 2022-11-25T17:41:21.2683276Z   "SRC:/src/core/atomicdex/services/update/zcash.params.service.hpp"
> 2022-11-25T17:41:21.2683634Z into
> 2022-11-25T17:41:21.2684602Z   "SRC:/ci_tools_atomic_dex/build-Debug/src/atomicdex-desktop_autogen/NVWMQ4ZM6I/moc_zcash.params.service.cpp"
> ```
> 
> https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/3549793097/jobs/5962556905#step:19:1251 and other places
> 
> ```
> 2022-11-25T18:03:02.5687170Z /Users/runner/work/atomicDEX-Desktop/atomicDEX-Desktop/src/core/atomicdex/utilities/global.utilities.hpp:39:63: fatal error: 'path' is unavailable: introduced in macOS 10.15
> 2022-11-25T18:03:02.5688380Z     bool        create_if_doesnt_exist(const std::filesystem::path& path);
> 2022-11-25T18:03:02.5689120Z                                                               ^
> 2022-11-25T18:03:02.5690270Z /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:738:24: note: 'path' has been explicitly marked unavailable here
> 2022-11-25T18:03:02.5691280Z class _LIBCPP_TYPE_VIS path {
> ```

Is it possible to use clang for CI builds instead of AppleClang ?

**Comment by smk762** [comment]
> Is it possible to use clang for CI builds instead of AppleClang ? 

`Nothing is is possible, not if you can imagine it. That's what being a scientist is all about.`

Yeah, as long as its something we can work into the CI. 

The first of the build errors above was in linux tho, so need to resolve that also.

**Comment by smk762** [comment]
https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/337de85f30e84dc4ed334e60cbd9f0720567be08 should fix it. 
ref: https://stackoverflow.com/questions/69407237/qt-moc-errorusr-include-c-10-bits-fs-fwd-39-parse-error-at-std
it is a qt bug, filesystem includes need to go after Qxxx includes

**Comment by smk762** [comment]
To test:
- Confirm able to launch app on all OS (portable and installer)
- Leave a comment to indicate which OS etc you have confirmed working.

**Comment by cipig** [comment]
works fine on Linux

**Review by cipig — APPROVED** [review]

**Comment by SirSevenG** [comment]
Win portable/installer [Windows 11] ✅ 
Fedora 37 build&run ✅ 
@smk762 I don't see MacOS builds in CI and there's an error with artifact not being found in workflow run logs, please recheck that.

**Comment by smk762** [comment]
@SylEze `https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/3623565505/jobs/6109577723#step:19:1232`
` fatal error: 'path' is unavailable: introduced in macOS 10.15`

We have deployment target set to 10.14
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/ci_tools_atomic_dex/ci_scripts/osx_script.sh#L26
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/ci_tools_atomic_dex/src/generate.nim#L20
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/.github/workflows/atomicdex-desktop-ci.yml#L237

@tonymorony are we still supporting MacOS 10.14 or can we update this to 10.15 (or 11)?

It appears to be EOL/no longer supported for security updates etc. ref: https://endoflife.date/macos

**Review by SirSevenG — COMMENTED** [review]
OSX installer/dmg ✅

**Review by SirSevenG — APPROVED** [review]

**Review by cipig — APPROVED** [review]

**Pull request merged**
