### PR TITLE
Change Calendar style

### LINKED ISSUE #1728: [BUG]: weird calendar
1. there are problems with displaying the calendar animation:

https://user-images.githubusercontent.com/77272165/162024928-a006dfa8-6d63-4112-9203-60500077daf7.mp4

**********************

2. long dates don't fit in and out of the window

image

**********************

3. shower effect on the selected date hard to read

image

but in light theme looks good:
image

**********************

4. would be good to add space between month and year

image

**********************

5. here is the extra empty space:

image

### PR DESCRIPTION
**Pull request by SylEze**
Closes #1728 

@Canialon @smk762

### CODE REVIEW

**Review by smk762 — COMMENTED** [review]
no overflows or weird animation detected here on linux. Is it possible to change colors to match the rest of the app?

**Comment by Canialon** [comment]
@SylEze could you apply these changes to the simple mod as well? ^^

image

******************

Also, there are a few small fixes:

- change the color of arrows for a light theme 
IMAGE 2022-05-29 18:20:56


- fix alignment for shower effect
Screenshot 2022-05-29 at 18 06 01
Screenshot 2022-05-29 at 18 06 19


tested on macOS, later will recheck on Windows

**Comment by SylEze** [comment]
^ @Canialon @smk762

**Comment by smk762** [comment]
I like the new colors - couple of quirks tho:
- no hover effect on lite mode over dates or top arrows.
- no hover effect on dark mode over dates.
- - no "current date" tooltip

**Comment by SylEze** [comment]
>     * no "current date" tooltip

Let's not add it for the moment, I think it was not there before ?

**Comment by SylEze** [comment]
> I like the new colors - couple of quirks tho:
> 
>     * no hover effect on lite mode over dates or top arrows.
> 
>     * no hover effect on dark mode over dates.

Fixed! @Canialon @smk762

**Review by smk762 — APPROVED** [review]

**Pull request merged**
