### PR TITLE
Frontend: Fix wallet cursor not refreshing when switching of coins

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1897#pullrequestreview-1109986391
https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1897#issuecomment-1256314444

### CODE REVIEW

**Review by Canialon — CHANGES_REQUESTED** [review]
still broken D':
same steps to reproduce

**Comment by SylEze** [comment]
Finally reproduced it, it's not just cursor but the whole GUI events that become buggy (see the two buttons on right of the navbar)

Capture d’écran 2022-10-13 à 9 49 51 PM

**Comment by Canialon** [comment]
Similar moment:

image
yeah looks like all interface become buggy :c

**Comment by smk762** [comment]
Closing - I've not seen this recently. If it reappears we can create a new PR for it.

**Pull request closed without merging**
