### PR TITLE
remove duplicate coincolor code

### PR DESCRIPTION
**Pull request by cipig**
the same list is already in atomic_defi_design/Dex/Constants/Style.qml

### CODE REVIEW

**Comment by smk762** [comment]
To test:
- launch app
- confirm coin text / tags displays correctly in all pages (enable, wallet, transaction confirmation, transaction history, portfolio, dex simple, dex pro, addressbook, swap confirmation, swap status, swap history etc).

**Comment by Canialon** [comment]
@cipig can you please marge `dev` into this branch to trigger CI builds 🙏

**Comment by cipig** [comment]
> @cipig can you please marge `dev` into this branch to trigger CI builds pray

done... but MacOS will not build, since i have done this PR from my own repo... forgot that MacOS is not built when i do that, sorry

**Comment by cipig** [comment]
oh, guess that wasn't the best idea... i merged dev into it, but this PR was moved to 0.5.8 branch
looks weird atm... maybe merging dev to 0.5.8 will clear it up again

**Review by endrilickollari — COMMENTED** [review]
Is it okay that `Arbitrum` has same color as `ERC-20`: 

image

image

**Comment by endrilickollari** [comment]
> Is it okay that `Arbitrum` has same color as `ERC-20`:
> 
> image
> 
> image

Text color is okay: 
BEP-20 != others: 

image

**Comment by cipig** [comment]
the colors of the chains were not modified in this PR, i just removed the duplicate definition of coin colors
we should actually remove that thing completely and replace it with chain specific colors, so we don't have to define a color for each coin in part... if we want to keep colors for each coin, we should move the config into coins repo
but i think use chain colors will be better... would also give us the option to remove the chain suffix from tickers in some places if the different chains are differentiated by different colors

**Comment by endrilickollari** [comment]
> the colors of the chains were not modified in this PR, i just removed the duplicate definition of coin colors we should actually remove that thing completely and replace it with chain specific colors, so we don't have to define a color for each coin in part... if we want to keep colors for each coin, we should move the config into coins repo but i think use chain colors will be better... would also give us the option to remove the chain suffix from tickers in some places if the different chains are differentiated by different colors

Beside that, everything looks okay to me.

**Review by smk762 — APPROVED** [review]

**Pull request merged**
