### PR TITLE
Add additional electrum servers for EFL

### PR DESCRIPTION
**Pull request by AmazingDreams**

### CODE REVIEW

**Comment by cipig** [comment]
SSL with IPs doesn't work, it needs to be a hostname

**Comment by AmazingDreams** [comment]
Thanks, I updated the config and added additional servers

**Comment by cipig** [comment]
thanks, those are working fine

**Review by cipig — APPROVED** [review]

**Comment by AmazingDreams** [comment]
@cipig I got an email stating there is a failed build, anything that is related to these changes?

**Comment by cipig** [comment]
@AmazingDreams all good, the failed build doesn't mean anything :-)

**Pull request merged**
