### PR TITLE
Visual fixes

### PR DESCRIPTION
**Pull request by smk762**
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1808
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1810
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1811 
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1812
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1813
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1815

### CODE REVIEW

**Review by cipig — APPROVED** [review]

**Review by SirSevenG — CHANGES_REQUESTED** [review]
Custom protection overlaps fee details:

image

**Comment by smk762** [comment]
> Custom protection overlaps fee details:
> 
> image



> Custom protection overlaps fee details:
> 
> image

I am not able to replicate this
image

image

**Review by SylEze — APPROVED** [review]

**Comment by smk762** [comment]
@SirSevenG can you please confirm the changes you requested are resolved?

**Comment by Canialon** [comment]
`simple` button overflow on big window size

wider window -> wider button -> button overflow
image

https://user-images.githubusercontent.com/77272165/176861560-39676859-4edb-4944-938b-1eeb5ab677c5.mov

repeated on mac and windows CI build

**Pull request closed without merging**
