### PR TITLE
Design tweaks

### PR DESCRIPTION
**Pull request by SylEze**
closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1461
closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1453
closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1427
closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1431

This pr changes/affects:

- ComboBox style
- Sidebar behaviour on hover line icon
- Sidebar behaviour in shrunk mode: hovering makes it to expand
- Pro view design
- Startup screen design

### CODE REVIEW

**Comment by tonymorony** [comment]
That's a cool idea with menu moving @SylEze ! sometimes it bugging on my side tho (check 00:30) :

https://user-images.githubusercontent.com/24797699/141510780-6c180191-106f-4eac-9918-94f96be85ae4.mov

**Comment by smk762** [comment]
Thanks for fixing text overflow on expand with fade in and removing fiat tooltip. I can replicate the icon overflow also 
image
Possible to only display full icon when in fully expanded state?

**Comment by smk762** [comment]
Overflow issue appears fixed here. There is a small quirk, looks like there is tiny text sometimes, otherwise ok

https://user-images.githubusercontent.com/35845239/141766217-f9d2b5c5-ca87-42a6-97c2-76aec3ec6eb3.mp4

**Comment by Milerius** [comment]
I think there is almost ever hover effect that are missing right now on the pro view

**Comment by tonymorony** [comment]
after login logo showing in the not correct state - reproducing 10/10 on my side

https://user-images.githubusercontent.com/24797699/143507479-475126fe-3573-46c0-ab36-62a653a7f304.mov

**Comment by smk762** [comment]
image
Button when in "buy coin" state is hard to read text

**Comment by tonymorony** [comment]
fields background disappeared

Screenshot 2021-11-27 at 22 47 18

**Comment by tonymorony** [comment]
regards pro-view

1) tradingview graph disappeared (I think @polevin forgot to draw it in figma design)

2) trading information part is not fit on all tabs in case of not full hd window

Screenshot 2021-11-27 at 22 52 32
 
image

on hd screen, there is a lot of empty space tho

Screenshot 2021-11-27 at 22 57 03

3) all these grey fonts don't have enough contrast 

Screenshot 2021-11-27 at 22 55 08

**Comment by tonymorony** [comment]
I see this panel even I'm not logged in

Screenshot 2021-11-27 at 23 16 24

**Comment by Milerius** [comment]
> regards pro-view
> 
> 1. tradingview graph disappeared (I think @polevin forgot to draw it in figma design)
> 2. trading information part is not fit on all tabs in case of not full hd window
> 
> Screenshot 2021-11-27 at 22 52 32
> 
> image
> 
> on hd screen, there is a lot of empty space tho
> 
> Screenshot 2021-11-27 at 22 57 03
> 
> 3. all these grey fonts don't have enough contrast
> 
> Screenshot 2021-11-27 at 22 55 08

I would like to add the fact that we can not resize panel part anymore, that's frustrating, would be nice to still be able to resize as we want each part, and fulfil by default

**Comment by smk762** [comment]
Data within the `Exchange rates | Orders | History ` tabs area are overflowing.

Suggest here, we use a line break between the crypto value and the fiat value
image
image


Here the exchange rate bleeds over into the orders tab
image
image

**Comment by SylEze** [comment]
> after login logo showing in the not correct state - reproducing 10/10 on my side
> Screen.Recording.2021-11-26.at.06.26.21.mov

Fixed in db840410925aae57e102783ec95d31500ea400e5

**Comment by SylEze** [comment]
> fields background disappeared
> 
> Screenshot 2021-11-27 at 22 47 18

Fixed in 2289ba09aa5925024e4b5f49e10f38de5d188c4b

**Comment by Milerius** [comment]
Capture d’écran 2021-12-04 à 05 45 12

Nan values for min_orders

**Comment by tonymorony** [comment]
thank you for the feedback @Milerius, created an issue https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1475 so we'll consider it in the future iterations

@SylEze @smk762  could you please have a look at the `NaN values for the min_orders` problem?

**Comment by smk762** [comment]
> NaN values for min_orders

Seems to be only where coin has no previous transactions, and a coin without history has not previously been selected for side of pair.

https://user-images.githubusercontent.com/35845239/144701395-7b296b67-2347-4c47-8a57-fc75e14b789c.mp4

**Comment by SylEze** [comment]
> thank you for the feedback @Milerius, created an issue #1475 so we'll consider it in the future iterations
> 
> @SylEze @smk762 could you please have a look at the `NaN values for the min_orders` problem?

I know where the bug is, let me few minutes

**Comment by smk762** [comment]
I seem to be having a problem deleting wallets now.

https://user-images.githubusercontent.com/35845239/144798489-6782ccf9-2150-4abb-8294-63643755ed45.mp4

checked on latest dev, no problem.

**Review by smk762 — APPROVED** [review]
built locally to test on all OS. Basic launch and trade ok. Outstanding visual tweaks moved to https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1485

**Comment by Milerius** [comment]
Thanks for the big pr @ssakone @smk762 @tonymorony @SylEze

**Review by Milerius — APPROVED** [review]

**Pull request merged**
