### PR TITLE
Update qt.settings.page.cpp

### PR DESCRIPTION
**Pull request by Milerius**

### CODE REVIEW

**Comment by tonymorony** [comment]
is it related to https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1329 ?

**Comment by Milerius** [comment]
> is it related to #1329 ?

Yes! Did it from mobile sorry

**Comment by tonymorony** [comment]
thanks for the clarification @Milerius !

@smk762 test plan is custom ERC20/BEP20 tokens adding. it would be great to include this fix into 0.5.2 release

**Comment by smk762** [comment]
Should we add inputs for coinpaprika too? Is it needed for new pricing service?

**Comment by smk762** [comment]
Added custom ERC / QRC / BEP without error
image

Note: on restart and coin activating, parent chain does not activate (see image, no QTUM or BNB). User has to add them manually afterwards.

**Comment by Milerius** [comment]
> Note: on restart and coin activating, parent chain does not activate (see image, no QTUM or BNB). User has to add them manually afterwards.

This should be the case in the slp branch

**Comment by Milerius** [comment]
> Should we add inputs for coinpaprika too? Is it needed for new pricing service?

Custom tokens cannot have price anymore due to our new service, the new service is not aware of custom tokens.

**Review by smk762 — APPROVED** [review]

**Pull request merged**
