### PR TITLE
Use master coins file and official latest release API

### PR DESCRIPTION
**Pull request by smk762**
To test:
- Reset assets config, and confirm all protocols are able to activate and perform swaps.
- Confirm all icons preset for all coins
- Confirm Tendermint coins (ATOM/IRIS/ATOM-IRIS_IBC) are not present

### CODE REVIEW

**Review by cipig — APPROVED** [review]

**Comment by smk762** [comment]
Ready for review / merge

**Review by cipig — APPROVED** [review]

**Review by tonymorony — APPROVED** [review]

**Comment by tonymorony** [comment]
something is wrong with these changes:

image

```
Please check your internet connection (e.g. VPN service or firewall might block it).

{
    "error": "rpc:212] dispatcher_legacy:160] lp_commands_legacy:102] lp_coins:2310] utxo_standard:53] utxo_coin_builder:133] Coin should be activated with Hardware Wallet. Please consider using `\"priv_key_policy\": \"Trezor\"` in the activation request"
}
```

BTC, KMD not activating

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by cipig** [comment]
afaik, it needs a more recent version of mm2

**Comment by smk762** [comment]
I checked in CLI using same version. `{"result":"2.1.8673_mm2.1_1e1338d2d_Linux_Release","datetime":"2022-11-07T22:52:27+07:00"}`

curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"KMD\",\"servers\":[{\"url\":\"electrum1.cipig.net:10001\"},{\"url\":\"electrum2.cipig.net:10001\"}], \"tx_history\":true, \"priv_key_policy\": \"Iguana\"}"

`{"error":"rpc:212] dispatcher_legacy:160] lp_commands_legacy:102] lp_coins:2309] utxo:1262] unknown variant `Iguana`, expected `IguanaPrivKey` or `Trezor`"}`

curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"KMD\",\"servers\":[{\"url\":\"electrum1.cipig.net:10001\"},{\"url\":\"electrum2.cipig.net:10001\"}], \"tx_history\":true, \"priv_key_policy\": \"IguanaPrivKey\"}"

`{"error":"rpc:212] dispatcher_legacy:160] lp_commands_legacy:102] lp_coins:2310] utxo_standard:53] utxo_coin_builder:133] Coin should be activated with Hardware Wallet. Please consider using `\"priv_key_policy\": \"Trezor\"` in the activation request"}`

Looks to be API related. There is no change to methods in this PR, only changes to parsing the coins json file to conform to structure requested by air_dex team to include `gui_auth`.

For comparison I ran the above with a recent mm2 dev build which returned expected result without `priv_key_policy` field - though dev branch also has the zhtlc changes in it. 

cc: @sergeyboyko0791 can you please confirm the commit which resolved this issue? I recall mentioning it in chat when I first encountered it, and we will need it for next desktop release.

**Comment by smk762** [comment]
After checking desktop dev branch and seeing no errors,  compared the coins repo branches referenced in the branch and in dev.
Seems we can avoid this error by removing entries like 
```
    "derivation_path": "m/44'/0'",
    "trezor_coin": "Bitcoin"
```
in https://github.com/KomodoPlatform/coins/blob/desktop-0.5.7/coins#L1723-L1724

**Comment by tonymorony** [comment]
I don't think it's good approach to have separate coins file branch for specific release of specific interface. Interface should be compatible with master branch (and actually this PR calling "Use `master` coins"

**Comment by tonymorony** [comment]
`{"error":"rpc:212] dispatcher_legacy:160] lp_commands_legacy:102] lp_coins:2309] utxo:1262] unknown variant Iguana, expected IguanaPrivKey or Trezor"}`

@smk762 the error is extra clear: you have to use `IguanaPrivKey` param instead of `Iguana` in `"priv_key_policy"` field

**Comment by smk762** [comment]
Initially it was, but we can use master and this version of api if it has the fields mentioned in it.
This PR originally used master branch, but I created the `desktop-0.5.7` branch in coins repo to exclude tendermint assets.
I've updated the `desktop-0.5.7` branch now to remove the trezor related entries, an have kicked off the CI again for further testing.

**Comment by sergeyboyko0791** [comment]
Unfortunately, it won't help because when I worked on HW integration, I expected that there will be `KMD`, `KMD-HW` coins, so the first had not to contain `derivation_path` field, and the second had to contain `derivation_path`.
> @smk762 the error is extra clear: you have to use IguanaPrivKey param instead of Iguana in "priv_key_policy" field

If we shouldn't have multiple versions of the coins file, I can prepare a hot fix into `mm2.1` that will be present until `dev` is merged.
cc: @tonymorony

**Comment by tonymorony** [comment]
> Unfortunately, it won't help because when I worked on HW integration, I expected that there will be `KMD`, `KMD-HW` coins, so the first had not to contain `derivation_path` field, and the second had to contain `derivation_path`.
> 
> > @smk762 the error is extra clear: you have to use IguanaPrivKey param instead of Iguana in "priv_key_policy" field
> 
> If we shouldn't have multiple versions of the coins file, I can prepare a hot fix into `mm2.1` that will be present until `dev` is merged. cc: @tonymorony

Since we are not using `-HW` prefix its definitely needs to be hotfixed imo 

Wondering now why it works fine in atomicdex web/mobile atm @yurii-khi 😊

**Comment by sergeyboyko0791** [comment]
air_dex uses our `dev` branch where we've changed this behaviour already
> Wondering now why it works fine in atomicdex web

**Review by cipig — DISMISSED** [review]

**Review by SirSevenG — DISMISSED** [review]
We have ATOM-BEP20 and ATOM-PLG20 available, but that should not be an issue.

**Review by Canialon — APPROVED** [review]

**Review by SirSevenG — APPROVED** [review]
lgtm

**Review by Canialon — APPROVED** [review]

**Review by SylEze — APPROVED** [review]

**Review by SirSevenG — APPROVED** [review]

**Review by tonymorony — APPROVED** [review]

**Pull request merged**
