### PR TITLE
fix(BestOrder & Wallet SwapButton): fix  bug  (trading page)

### PR DESCRIPTION
**Pull request by ssakone**

### CODE REVIEW

**Comment by tonymorony** [comment]
@ssakone Thanks for the PR!
The error message is not fully visible on my side (you can check the video below).

Also, when I'm starting to input low volume,  in a few seconds volume jumping to `MAX`
To reproduce:
- select some order
- input `0.` into volume
- wait 1-2 seconds

Video:
https://drive.google.com/file/d/1sbvyhuveYRfk2xLYBEl-dsPdLcnFX3VH/view?usp=sharing

**Comment by ssakone** [comment]
@tonymorony  please whats your screen size?

**Comment by smk762** [comment]
confirm https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/796 fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/750250005

**Comment by smk762** [comment]
> @ssakone Thanks for the PR!
> The error message is not fully visible on my side (you can check the video below).
> 
> Also, when I'm starting to input low volume, in a few seconds volume jumping to `MAX`
> To reproduce:
> 
> * select some order
> * input `0.` into volume
> * wait 1-2 seconds
> 
> Video:
> https://drive.google.com/file/d/1sbvyhuveYRfk2xLYBEl-dsPdLcnFX3VH/view?usp=sharing

I get this too, also if entering `0.0000` (any number of zeros as long as no other digit)

**Pull request merged**
