### PR TITLE
Make tx history better again

### LINKED ISSUE #1849: [BUG]: Assets switch in wallet section is blocked if transactions loading
If asset is in "Fetching transactions" state you are not able to switch to another coin what is not good behaviour.

We do use centralised endpoint for EVM assets tx history so app can became unusable if endpoint is down.

Expected behaviour is timeout on loading and/or possibility to switch between assets during tx history fetching

### PR DESCRIPTION
**Pull request by SylEze**
Closes #1849 

**Please do not merge until SLP PR is merged**

### CODE REVIEW

**Comment by tonymorony** [comment]
@SylEze old bug returned: if you switch between assets fast, then history for another coin displaying (in video below history from KMD is displaying for BCH)

https://user-images.githubusercontent.com/24797699/182200729-cfede93c-750a-43f4-b0cc-5e381697fd40.mov

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by smk762** [comment]
It seems now that when I switch quick in the coins menu it just gets stuck on "fetching transactions"

**Comment by tonymorony** [comment]
Yeah, right now it's totally broken: if you starting switch fast it's became in "fetching transactions" spinner status until I restart the app

https://user-images.githubusercontent.com/24797699/183542369-557fa71c-25a6-4308-9335-a305094e1e16.mov

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Review by Canialon — CHANGES_REQUESTED** [review]
Confirm the issue above (just in case to remove this pr from my review list for now)

**Comment by SylEze** [comment]
Please retest this PR

(cc. @Canialon @tonymorony @smk762)

**Comment by smk762** [comment]
This seems to be working here in terms of the current history on wallet page for the correct coin without things locking up. I can;t see history for anything that is not a utxo coin though.

@Canialon @SirSevenG please note that when testing this PR with an existing wallet, it might crash due to json conflicts. This issue has been resolved elsewhere, but you might need to manually delete your wallet's local coins file.

**Review by SirSevenG — CHANGES_REQUESTED** [review]
Was able to see non-utxo coins transaction history.

There's visual bug when switching coins in Wallet, light theme provides better visibility of it:
Screenshot 2022-09-16 040109

Just switch a few coins view and see how coin-selection panel changes highlights here.

**Review by Canialon — APPROVED** [review]
@SirSevenG I was unable to reproduce the issue above (I tried Windows 10 and macOS), so I approve.

**Review by SirSevenG — APPROVED** [review]
Yep, thanks @SylEze That fixed it for me

**Comment by smk762** [comment]
Looks good here too :+1: 
I"ll wait for SLP branch to merge, then approve / merge this one.

**Review by Canialon — CHANGES_REQUESTED** [review]
this time I have reproduced this dug XD

100% way to reproduce (works for me on mac and windows):
1. create new or import wallet
2. click add assests
3. choose select all -> enable
4. wait until all coins are activated
5. go to wallet tab and choose one coin by one

image

Tab hover effect also breaks
image

**Review by Canialon — DISMISSED** [review]
> Just synced again with SLP PR which contains some enabling coin fixes so it might fix your problem

oh I just have seen a comment about it above

**Comment by Canialon** [comment]
> this time I have reproduced this dug XD
> 
> 100% way to reproduce (works for me on mac and windows):
> 
> 1. create new or import wallet
> 2. click add assests
> 3. choose select all -> enable
> 4. wait until all coins are activated
> 5. go to wallet tab and choose one coin by one
> 
> image
> 
> Tab hover effect also breaks image

Looks like it is not this branch bag, I was able to reproduce it on other branches. So will create an issue

**Comment by smk762** [comment]
Good catch @Canialon !
Confirmed here by manually deleting wallet's Transaction json files in `/.atomic_qt/mm2/DB/<walletID_hash>/TRANSACTIONS`
and logging in again. 
@SylEze it looks like previous selection reverts to "clicked" state for highlight instead of default (no highlight). I'll take a look this weekend and see if I can resolve.

**Comment by SylEze** [comment]
Will be fixed in another PR since it's unrelated with the work done here: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1985


> > this time I have reproduced this dug XD
> > 100% way to reproduce (works for me on mac and windows):
> > 
> > 1. create new or import wallet
> > 2. click add assests
> > 3. choose select all -> enable
> > 4. wait until all coins are activated
> > 5. go to wallet tab and choose one coin by one
> > 
> > image
> > Tab hover effect also breaks image
> 
> Looks like it is not this branch bag, I was able to reproduce it on other branches. ~ So will create an issue ~

**Review by smk762 — APPROVED** [review]

**Review by Canialon — APPROVED** [review]

**Pull request merged**
