### PR TITLE
show contract address

### PR DESCRIPTION
**Pull request by smk762**
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1415

Before:
image
image

After:
image
image

If no price / contract:
image

If no balance:
image

### CODE REVIEW

**Review by SylEze — APPROVED** [review]

**Comment by tonymorony** [comment]
thank you for the PR! 

As I think this way we show too much information to the user in one shot, also it duplicating receive button content right now

I do propose such pane arrangement:

image

With contract addy clickable with opening in explorer similar to CMC (e.g.https://coinmarketcap.com/currencies/ethereum/):

Screenshot 2022-02-16 at 14 04 57

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by smk762** [comment]
> thank you for the PR!
> 
> As I think this way we show too much information to the user in one shot, also it duplicating receive button content right now
> 
> I do propose such pane arrangement:
> 
> image
> 
> With contract addy clickable with opening in explorer similar to CMC (e.g.https://coinmarketcap.com/currencies/ethereum/):
> 
> Screenshot 2022-02-16 at 14 04 57

In cases where no contract address, how do we want the alignment of the remaining elements & horizontal lines?
Do we want to indicate network/protocol (beyond icon above contract)? e.g. `KMD-BEP20` above balance, or `BEP20 Contarct address` as label?

**Comment by tonymorony** [comment]
`In cases where no contract address, how do we want the alignment of the remaining elements & horizontal lines?`

I think display like this is fine in such case: 

image

`Do we want to indicate network/protocol (beyond icon above contract)? e.g. KMD-BEP20 above balance, or BEP20 Contarct address as label?`

Imo it worth to do both - indicate with binance icon near the smart contract addy and add suffix to ticker near the balance to ensure that user understand whats going on

**Comment by smk762** [comment]
@tonymorony 
in cases where coin has long full name, how do we want to handle it?
image

I think the ticker might be better under the coin icon in terms of being closer to icon width. Demo below - 
image

example with longer ticker:
image

**Comment by smk762** [comment]
Current iteration:

image
image
image
image
image
image
image
image

**Comment by tonymorony** [comment]
great progress @smk762 !

`I think the ticker might be better under the coin icon in terms of being closer to icon width. Demo below -` thats definitely looks better

could you please cut contract address the way same as https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1612#issuecomment-1041179504 ? (4 symbols after 0x and 7 last symbols)

**Comment by smk762** [comment]
> could you please cut contract address the way same as [#1612 (comment)](https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1612#issuecomment-1041179504) ? (4 symbols after 0x and 7 last symbols)

Looks like this now:

image

For the `elide` options, qt only has left | right | middle, though if you want I should be able to do a function to replicate first 4 after 0x and last 7.

**Review by tonymorony — APPROVED** [review]
lgtm, thanks!

**Review by SylEze — APPROVED** [review]

**Pull request merged**
