### PR TITLE
Change startup screen style

### PR DESCRIPTION
**Pull request by SylEze**
This PR is an attempt to fix https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1383#issuecomment-953699623

### CODE REVIEW

**Comment by smk762** [comment]
Fails to launch here- 
```
[13:44:01] [warning] [main.prerequisites.hpp:92] [4101573]: QQmlApplicationEngine failed to load component
[13:44:01] [warning] [main.prerequisites.hpp:92] [4101573]: qrc:/Dex/main.qml:375:5: Type App unavailable
[13:44:01] [warning] [main.prerequisites.hpp:92] [4101573]: qrc:/Dex/App.qml:69:9: Type Startup.Main unavailable
[13:44:01] [warning] [main.prerequisites.hpp:92] [4101573]: qrc:/Dex/Screens/Startup/Main.qml: No such file or directory
```

**Comment by SylEze** [comment]
> Fails to launch here-
> 
> ```
> [13:44:01] [warning] [main.prerequisites.hpp:92] [4101573]: QQmlApplicationEngine failed to load component
> [13:44:01] [warning] [main.prerequisites.hpp:92] [4101573]: qrc:/Dex/main.qml:375:5: Type App unavailable
> [13:44:01] [warning] [main.prerequisites.hpp:92] [4101573]: qrc:/Dex/App.qml:69:9: Type Startup.Main unavailable
> [13:44:01] [warning] [main.prerequisites.hpp:92] [4101573]: qrc:/Dex/Screens/Startup/Main.qml: No such file or directory
> ```

Fixed

**Review by smk762 — APPROVED** [review]

**Review by smk762 — APPROVED** [review]

**Comment by tonymorony** [comment]
all screens for the login/import process looks not good now in light theme

Screenshot 2021-11-08 at 17 57 19
Screenshot 2021-11-08 at 17 57 02
Screenshot 2021-11-08 at 17 55 02

there is UI for the light theme, also you can use colors from the same screen webdex design.
if necessary @polevin will make figma screens especially for desktop

**Comment by smk762** [comment]
> all screens for the login/import process looks not good now in light theme
> 
> Screenshot 2021-11-08 at 17 57 19
> 
> Screenshot 2021-11-08 at 17 57 02
> 
> Screenshot 2021-11-08 at 17 55 02
> 
> there is UI for the light theme, also you can use colors from the same screen webdex design. if necessary @polevin will make figma screens especially for desktop


converted to issue at https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1412

**Pull request merged**
