### PR TITLE
Send coins from a fiat input

### LINKED ISSUE #1548: [FEATURE REQUEST]: Possibility to specify send amount in fiat (if fiat rate is available)
user story: let's say I want to send 300$ (or another fiat) worth in crypto, right now I have to use a calculator to determine how much it is in the desired crypto (e.g. if KMD price is 0.75$ I have to 300/0.75 and send 400 KMD)

solution: two input fields for sending amount: coins amount and fiat amount

at first, both fields value is 0
 if you modify a value in one input field (e.g. set coins amount) second adjust accordingly (if you set 5 KMD and current KMD price is 0.75$/KMD fiat field will be set on 3.75$, and vice versa) 

image

### LINKED ISSUE #1587: No cursor on input fields selection in send modal
https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1550

### PR DESCRIPTION
**Pull request by SylEze**
Closes #1548 
Closes #1587

### CODE REVIEW

**Comment by SylEze** [comment]
I need UI review on this one please

(cc. @tonymorony)

Capture d’écran 2022-01-10 à 12 39 40 PM

**Comment by tonymorony** [comment]
Thank you for PR!

I think we should specify ticker also somewhere, e.g.

image

@polevin could you please advise on the UX of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1548 implementation?

**Comment by smk762** [comment]
can we pls also include fiat row in the tx details?
image

**Comment by smk762** [comment]
Perhaps for coins with no price, the fiat input can be hidden, or have a static value of zero
image

**Comment by tonymorony** [comment]
update from my side: we are still working on this feature UX design with @polevin, should be done soon :)

**Comment by tonymorony** [comment]
current design option: 

paste (29)

described mechanics in a call

**Review by smk762 — DISMISSED** [review]

**Comment by tonymorony** [comment]
@smk762 on Friday's sync call we've discussed UX changes (https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1550#issuecomment-1013067252)

@SylEze you can find all screens of this modal flow in Figma -> Dark theme page (these new frames are highlighted by green)

**Comment by smk762** [comment]
Looking good. One request - I can't see the `|` cursor indicator on the input field when selected for input, can we add that?

**Comment by tonymorony** [comment]
There is no cursor on input fields selection for me, @smk762 could you please try on your side?

**Comment by smk762** [comment]
no cursor here either, might have something to do with placeholder text as once you enter a space or char it shows up.
as a workaround, just to indicate the active field, I have a commit I'm testing locally and will push soon

https://user-images.githubusercontent.com/35845239/152148715-fb94087a-073e-45cd-a306-ee5a5e9000ba.mp4

.

**Comment by tonymorony** [comment]
Besides the bug: I think it might be good to add a fiat sign to the fiat amount (since now it's might be a bit confusing)
and also set alignment to input fields

Screenshot 2022-02-02 at 19 23 38

**Review by tonymorony — CHANGES_REQUESTED** [review]
@SylEze ^^

**Comment by tonymorony** [comment]
The cursor is still not visible @SylEze

**Comment by SylEze** [comment]
> The cursor is still not visible @SylEze

I already tried to fix that problem and could not find where the issue is, last friday I told smk we should make another issue for that, I'll fix later

Sorry forgot to tell you about it

**Comment by smk762** [comment]
I'll add issue now. I also tried to fix this but was not successful. It is strange, same component not in these modals has the cursor. Even a test copy/paste of same component used in simple dex page for coin search put into modal resulted in no cursor.

**Comment by tonymorony** [comment]
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1587

**Comment by tonymorony** [comment]
converted to draft for now to prevent merging

**Review by tonymorony — CHANGES_REQUESTED** [review]
it doesn't work correctly when using MAX button (the bottom amount don't refresh at all, as well as validation)

**Review by tonymorony — DISMISSED** [review]
its good now I think, thanks @SylEze 

could you please also re-test @smk762 ?

**Comment by smk762** [comment]
Should we perhaps have the fiat `$` symbol to the right of the numbers?
image

Alignment?
image

Perhaps could make address / txid here a hyperlink (can add to other issue if you want)
image

Select address from addressbook - maybe can make columns width so full address visible (can create other issue if you want)
image

**Comment by smk762** [comment]
Fiat values a bit different in confirmation screen
image
image

ok with AUD tho

**Comment by SylEze** [comment]
> Fiat values a bit different in confirmation screen image image
> 
> ok with AUD tho

Yeah it's because calculations are made by the frontend on the prepare page and by the backend on the send page, that's why fiat values might be different

**Review by smk762 — APPROVED** [review]
works well here

**Review by tonymorony — APPROVED** [review]

**Pull request merged**
