### PR TITLE
Standardise password length limit

### PR DESCRIPTION
**Pull request by smk762**
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2054
To test:
- go thru wallet creation processes to confirm new length req message is shown.
- try to input a 256 char password into every password input field in the app, then click eyeball icon to confirm input not cut shorter
- confirm creating camouflage password still allows a single char.

### CODE REVIEW

**Review by SirSevenG — CHANGES_REQUESTED** [review]
New req messages are correct ✅ 
Password fields are cut on 257th symbol, 256 fit just right ✅
Able to create 1 character camouflage pass ✅ 
Able to create 400 char camouflage pass 🛑

**Comment by smk762** [comment]
The cammo password field is not governed by the same constraints, but will not work if too long (including regular passwork) for login input to accept. 
For this reason, perhaps we should limit standard password to 250 char, and limit cammo suffix to 6 char for total of 256.
@tonymorony is this reasonable? If so will implement today.

**Comment by tonymorony** [comment]
> For this reason, perhaps we should limit standard password to 250 char, and limit cammo suffix to 6 char for total of 256.

@smk762 perhaps it breaks backward compatibility if user set longer camo password on previous version?

**Comment by smk762** [comment]
I'm open to suggested numbers. This fix arose from an issue where user had 47 char password but privacy password input was capped at 40. 
Should I just open the limit up to 256 for both (512 total)? This would cover most users I assume.

**Comment by tonymorony** [comment]
> Should I just open the limit up to 256 for both (512 total)? This would cover most users I assume.

Yep, lets do it this way to let the user decide on how to use this feature

**Comment by smk762** [comment]
max input for:
- wallet creation: 256
- camo password: 256
- delete wallet: 256
- disable privacy: 256
- view seeds: 256
- Log in to wallet: 512 (to allow for standard password + camo suffix)

**Review by SirSevenG — APPROVED** [review]
lgtm

**Review by Canialon — APPROVED** [review]

**Pull request merged**
