### PR TITLE
Startup (import wallet) improvement

### PR DESCRIPTION
**Pull request by ssakone**
CheckList

- [x] #1165 
- [ ] It was possible to enable allow custom seed with keyboard (navigation beetween widget and toggle space) now fixed

### CODE REVIEW

**Comment by tonymorony** [comment]
What do we need to test here / what issues this PR related to @ssakone ?

**Comment by ssakone** [comment]
> What do we need to test here / what issues this PR related to @ssakone ?

sorry i update description

**Comment by smk762** [comment]
Confirm that trying to create a wallet with an existing name using "Import wallet" will throw warning and not allow overwrite prior to entering password and confirmation :heavy_check_mark: 

Big problem with creating a new seed/wallet using an existing name tho. There is no warning and nothing to stop you from overwriting your old seed linked to the wallet name.

https://user-images.githubusercontent.com/35845239/129172000-3a2224e8-9eac-457c-830f-fc711ea81cc7.mp4

**Review by smk762 — APPROVED** [review]
Working as expected, thanks!

**Comment by tonymorony** [comment]
thanks for the PR!

a) on import please do name validation on the previous screen where the user set wallet name, otherwise, she wasting time on password creation

b) validation error displaying twice

image

**Review by tonymorony — CHANGES_REQUESTED** [review]
please check comment below

**Comment by tonymorony** [comment]
thanks for the PR!

a) on wallet creation and import please do wallet name validation on the previous screen where the user set wallet name, otherwise, she wasting time on password creation 

b) validation error displaying twice

image

**Comment by ssakone** [comment]
@tonymorony its already done

**Comment by smk762** [comment]
Working here
image

**Review by tonymorony — APPROVED** [review]
it looks like I've tried not on the latest commit by mistake, lgtm thank you

**Pull request merged**
