### PR TITLE
Update window

### PR DESCRIPTION
**Pull request by ssakone**
### Application window improvement

* This pull request should fix window left sidebar positioning
* New window radius (feature: we remark currently on window os & macos they have radius window)

### CODE REVIEW

**Comment by Milerius** [comment]
I haven't seen any issue in the current roadmap mentioning this feature, what is it? Is it for the next split? Can you link the issues related to this PR and explain what to test?

**Comment by ssakone** [comment]
> I haven't seen any issue in the current roadmap mentioning this feature, what is it? Is it for the next split? Can you link the issues related to this PR and explain what to test?

You mention it lot of time, but we can just skip its, if its not required currently.

**Comment by smk762** [comment]
@ssakone is it ok to close this PR?

**Comment by ssakone** [comment]
> @ssakone is it ok to close this PR?

yes

**Pull request closed without merging**
