### PR TITLE
Add a way to get public key and modals restyle

### PR DESCRIPTION
**Pull request by SylEze**
Closes [#1302](https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1302)

This PR also applies huge changes regarding modals

### CODE REVIEW

**Comment by smk762** [comment]
Can we remove these dots? Should give more space for the list at the bottom.
image

I can see pubkey now and confirm it's matching expected.

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by smk762** [comment]
Modal padding seems excessive, has cause some cut-off issues.

notes button cut off
image

coin icons cut off
image

edge of button / input cut off
image

exchange rate text misaligned / missing
image

coin icons missing, text cuts off 
image

coin icons redacted
image

Alignment breaks with long error message on send modal
image

and stays broke once error resolved
image

address overlaps addressbook icon in send modal
image

Cut off on simple mode swap confirmation
image

message cut off
image

There is also issue with "show seed and private keys. To cutting off, but looks like text is wrapping in the middle of a word (or private key)
image

**Comment by smk762** [comment]
tx detail modal ok, tho we could maybe reduce margin or fontsize to avoid wrapping
image

swap confirm modal still has cut off text at bottom and overlap near coins (which has wierd background now)
PRO
image
SIMPLE
image


swap status also squashed
image

image

image


Send error shift issue fixed, looks nice. Still adresbbok icon overlap
image


order no longer available message still cut off
image

**Comment by smk762** [comment]
- Tx details modal ok
- swap history looks ok
- unmatched maker swap detail has different  alignment on buttons, doesn't need scrollbar
image
- swap confirmation modal still has some cutoff on east side (and radio button west side) Maybe add a little padding between coins and "exchange rate" text
image
- Some cut off on transaction complete
image
- send address/icon overflow moved to https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1644
- Rewards fees display issue moved to https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1647

**Comment by smk762** [comment]
selecting from addressbook via sendmodal also a bit uneven aligned and cut off
image
image

related: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1608

**Comment by SylEze** [comment]
> selecting from addressbook via sendmodal also a bit uneven aligned and cut off image image
> 
> related: #1608

Let's fix that one in another PR

**Comment by smk762** [comment]
- swap/trade/order matching/status modal look ok now
- receive modal shows full address ok

**Comment by smk762** [comment]
Undefined in claim rewards (can move to other issue)
image

**Comment by smk762** [comment]
Addressbook related: 

Something weird with select wallet button
image

address selection has no scroll and searchbar goes missing
image

`[warning] [main.prerequisites.hpp:92] [3994192]: file:///home/smk762/Downloads/atomicdex-desktop-ubuntu-qt-5-15-2-fdad333.zip/atomicdex-desktop-linux-fdad333/AntaraAtomicDexAppDir/usr/qml/QtQuick/Controls/Private/ScrollBar.qml:100: TypeError: Cannot read property 'hitTest' of null`

error cut off on east side
image

Validation for address fails if address not enabled
`resp validateaddress: [{"error":"rpc:211] dispatcher_legacy:160] lp_coins:1362] No such coin: DEX"}]`

Actions column cut off
image

**Comment by smk762** [comment]
`View private keys` modal:

If we can reduce margin/padding a tiny bit, privkeys will fit on single line without wrap. Most are ok but ETH keys have 3 char wrapped to second line.

seed words wrapping is breaking words in half on line break

**Comment by smk762** [comment]
With the above issues triaged to be dealt with separately, I'm content to approve this PR, but we will need to fix the addressbook and rewards claim issues before release @tonymorony

**Comment by SylEze** [comment]
> Validation for address fails if address not enabled
> `resp validateaddress: [{"error":"rpc:211] dispatcher_legacy:160] lp_coins:1362] No such coin: DEX"}]`

This one should also be an issue on dev

**Comment by smk762** [comment]
> > Validation for address fails if address not enabled
> > `resp validateaddress: [{"error":"rpc:211] dispatcher_legacy:160] lp_coins:1362] No such coin: DEX"}]`
> 
> This one should also be an issue on dev

confirmed - if coin not enabled, wont let you add addressbook entry.
we can either auto-enable, or maybe like on simple view give user pop up to say  "not enabled, do you want to?"

e.g.
image

**Review by smk762 — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
