### PR TITLE
Font system : Fix Language text overflow & Add some feature

### PR DESCRIPTION
**Pull request by ssakone**
- Add Font choice in settings
- Add languageDensity to automaticaly scale sidebar text
- change some text element to support font changement.

### CODE REVIEW

**Comment by Milerius** [comment]
image

In french i still get some overflow as in the above image

**Comment by ssakone** [comment]
its only french, all other language is done?

**Comment by ssakone** [comment]
image
verry strange

**Comment by Milerius** [comment]
> image
> verry strange

Really strange indeed, do i need to change anything locally ? reset a configuration maybe ?

**Comment by smk762** [comment]
On mine for linux, Russian is almost overflowing
image

And French does overflow also.
image

**Comment by smk762** [comment]
I've also found a restart loop situation when toggling the Settings > User Interface > Use QtTextRendering or NativeTextRendering button.


https://user-images.githubusercontent.com/35845239/117420331-0f11c780-af50-11eb-9e30-bac0fb7bc400.mp4


This can only be exited by running a different commit version of the app.

**Comment by ssakone** [comment]
> I've also found a restart loop situation when toggling the Settings > User Interface > Use QtTextRendering or NativeTextRendering button.
> 
>  restart_loop.mp4 
> This can only be exited by running a different commit version of the app.

i just see it, i m fixing it

**Comment by ssakone** [comment]
@smk762 can check in windows?

**Comment by ssakone** [comment]
> I've also found a restart loop situation when toggling the Settings > User Interface > Use QtTextRendering or NativeTextRendering button.
> 
>  restart_loop.mp4 
> This can only be exited by running a different commit version of the app.
Fixed, need to click apply to make changement, because every time, when component is created the value is automaticaly changed to settings value.
https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/895/commits/fffff255e194af50f3df8d13b39fbac5d0b95e59

**Comment by smk762** [comment]
Yes, also happening in windows on https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/819252681

**Comment by Milerius** [comment]
> Yes, also happening in windows on https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/819252681

You mean the restart loop or the font overflow ?

**Comment by smk762** [comment]
> > Yes, also happening in windows on https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/819252681
> 
> You mean the restart loop or the font overflow ?

reset loop. No font overflow issue on windows.

**Comment by Milerius** [comment]
> > > Yes, also happening in windows on https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/819252681
> > 
> > 
> > You mean the restart loop or the font overflow ?
> 
> reset loop. No font overflow issue on windows.

Ok so the font stuff problem seems to occured only on linux/osx ? Is that correct ?

**Comment by smk762** [comment]
On linux for me yes - it overflows on  https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/819252681.
On mac with https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/819641169 it does not overflow, but there is little to no padding on one of the French menu items. Text also looks a bit fuzzy.
image

**Comment by smk762** [comment]
Still an issue in linux in https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/819641169

https://user-images.githubusercontent.com/35845239/117459585-24054f80-af7e-11eb-943b-ec190fdbfe81.mp4

**Comment by ssakone** [comment]
> Still an issue in linux in https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/819641169

not this wait, i resolve conflic, its not my last commit.

**Comment by smk762** [comment]
Still a slight overflow in French
image

Russian is good, reasonable padding now.
image

Turkish and English still good.

**Comment by ssakone** [comment]
@smk762 can make last test for french lang in linux and macos?

**Comment by smk762** [comment]
some shadow / duplication of selected menu item in linux/Mac (only on French; windows ok).
image

**Review by Milerius — APPROVED** [review]

**Pull request merged**
