### PR TITLE
Redesign atomicDex from Figma.

### PR DESCRIPTION
**Pull request by ssakone**
## This PR is about fixing lot of design tweaks in different AtomicDex Part

* Startup & Login form [Comment](https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1427#issue-1053383827)

 ### Additionnal

- [ ] Language switcher update
- [ ] Eula Model update

### CODE REVIEW

**Comment by tonymorony** [comment]
@ssakone Login functionality lgtm, the only problem I noticed is that part of EULA text became bold:

Screenshot 2021-12-03 at 19 36 35

**Comment by ssakone** [comment]
> @ssakone Login functionality lgtm, the only problem I noticed is that part of EULA text became bold:
> 
> Screenshot 2021-12-03 at 19 36 35

strange

**Comment by ssakone** [comment]
@tonymorony  fixed

**Comment by tonymorony** [comment]
@ssakone 

Screenshot 2021-12-03 at 20 19 39

Screenshot 2021-12-03 at 20 18 46

**Review by tonymorony — APPROVED** [review]

**Review by SylEze — APPROVED** [review]

**Pull request merged**
