### PR TITLE
Add fujicoin

### PR DESCRIPTION
**Pull request by fujicoin**
Please add fujicoin.
However, I don't think that this information alone can make a wallet. 
What else should I do?

### CODE REVIEW

**Comment by lightspeed393** [comment]
Add Fujicoin to [KomodoPlatform/coins](https://github.com/komodoplatform/coins) repo with all the required information.

**Comment by fujicoin** [comment]
Ty
I made PR to  KomodoPlatform/coins

**Comment by fujicoin** [comment]
My PR for  KomodoPlatform/coins was merged.
https://github.com/KomodoPlatform/coins/pull/217

**Review by Milerius — APPROVED** [review]

**Comment by Milerius** [comment]
Thanks for youre contribution @fujicoin

**Comment by cipig** [comment]
@fujicoin getting this error from FJC electrum server when swapping
```
18 02:26:59, rpc_clients:161] Error JsonRpcError { client_info: "coin: FJC", request: JsonRpcRequest { jsonrpc: "2.0", id: "881", method: "blockchain.transaction.get", params: [String("1a271979beb0642123cfb62cabc1e94ec616fa81fcdd0787d5aacaa9bf91c623"), Bool(true)] }, error: Response(electrumx2.fujicoin.org:50003, String("verbose transactions are currently unsupported")) } getting the transaction 1a271979beb0642123cfb62cabc1e94ec616fa81fcdd0787d5aacaa9bf91c623, retrying in 10 seconds
```
`verbose transactions are currently unsupported`

**Comment by fujicoin** [comment]
@cipig
We are using Blockstream-electrs instead of electrum-X.
The response `verbose transactions are currently unsupported` occurs in the following code.
https://github.com/Blockstream/electrs/blob/a33e97e1a1fc63fa9c20a116bb92579bbf43b254/src/electrum/server.rs#L347

What should we do?

**Comment by cipig** [comment]
use https://github.com/spesmilo/electrumx instead, it has FJC support

**Comment by fujicoin** [comment]
@cipig
I haven't used electrum-X for a while. 
I'm currently investigating the latest electrum-X, so it will take some time to launch. 
I will contact you when it is completed.

**Comment by fujicoin** [comment]
@cipig
I launched electrum-X (version: 1.15.0).
Please test.

**Comment by cipig** [comment]
works fine now with electrumX
image
thanks for setting it up

**Pull request merged**
