### PR TITLE
add KIP0001, update app version

### PR DESCRIPTION
**Pull request by smk762**
- Adds `KIP0001` as a default coin (wallet only)
- Updates version to `0.5.7.1`

To test:
- Log in to existing wallet. KIP0001 should be activated in your portfolio.
- Create new wallet. KIP0001 should be automatically activated.
- Confirm version number is correct in settings.
- Ping @smk to receive a tiny amount of KIP0001. Confirm balance / history displays as expected. Send funds to one of the vote addresses: `RReduceRewardsXXXXXXXXXXXXXXUxPxuC` or `RKeepRewardsXXXXXXXXXXXXXXXXYKRSuF` 
- Confirm block explorer link works (should go to https://kip0001.explorer.kmd.io/)
- Confirm KIP0001 does not display in the DEX pages.
- Confirm swap button on KIP0001 wallet page is disabled.

### CODE REVIEW

**Comment by SirSevenG** [comment]
image

Release archive for win doesn't look good, can't be opened on download.

**Review by SirSevenG — CHANGES_REQUESTED** [review]
^^

**Comment by smk762** [comment]
```
-- command is: [C:\Qt/Tools/QtInstallerFramework/4.5/bin/archivegen.exe atomicdex-desktop.7z .]
Cannot write entry header for "D:/a/atomicDEX-Desktop/atomicDEX-Desktop/b/bin/atomicdex-desktop.7z": Can't add archive to itself: No error.
-- archivegen output:  Cannot write entry header for "D:/a/atomicDEX-Desktop/atomicDEX-Desktop/b/bin/atomicdex-desktop.7z": Can't add archive to itself: No error.
```
Wierd CI error, will look into it

**Comment by smk762** [comment]
@SirSevenG windows missing icons should be fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/4315146057

**Comment by SirSevenG** [comment]
@smk762 
Portables are still missing icons, installers for win are broken. They install... installer only? No app in expected folder after installation process finishes.

**Comment by smk762** [comment]
> @smk762 Portables are still missing icons, installers for win are broken. They install... installer only? No app in expected folder after installation process finishes.

Thanks, I'll focus on fixing this today.

**Comment by smk762** [comment]
Closing in favour of addressing these issues in smaller, more specific PRs.

**Pull request closed without merging**
