### PR TITLE
0.3.0

### PR DESCRIPTION
**Pull request by ca333**
# Features: 

* Added `BTCH`, `HODL`, `KOIN`, `MSHARK`, `WLC`, `ZILLA`, `NMC`, `MONA`, `GLEEC` and `SPACE`
* Removed `HUSH`
* Multi-tickers order #387 
* Custom ERC-20 tokens adding
* QRC-20 support (wallet functionality)
* Filters and CSV export for swaps history and orders
* Transactions notes
* Balance change notifications
* Band oracle price feed
* Reworked DEX market selector with search bar 
* Hand cursor icons when passing your mouse over different clickable elements
* Add Russian support
* Trading view charts

# Enhancements:

* Async request (async_buy, async_sell, async_claiming etc...)
* Updated layout
* Updated API core
* Better policy when internet is disconnected
* Market selectors new format
* Generic modals  for the layout
* Adjust scrollbars position
* Unlimited tx history
* Generic global price provider
* Show toast for withdraw error
* Hover effects for all buttons/clickable elements
* Visual effects and Transitions effects
* Set current base in the dex selector when clicking on `swap` from wallet page
* Stacktrace support on Linux
* MM2 logs into a separate file on OSX/Linux
* Restart application functionality
* Rewrite the README.md
* Add basic support for conan package manager

# Fixes:

* Fixed a crash when starting the application on Linux
* Fix shadow clipping at modals
* Fix update when selected coin balance changes
* Fix crash on OSX startup

### CODE REVIEW

**Comment by CHMEX** [comment]
if there is stil time also remove RFOX Utxo coin and add new RFOX ETH Coin if contract addr is known. _WLC_ is a legacy chain. **WLC21** is the swapped to chain

**Comment by cipig** [comment]
>_WLC_ is a legacy chain. **WLC21** is the swapped to chain

WLC is the correct coin, https://github.com/KomodoPlatform/coins/blob/master/coins#L3609, it has symbol WLC and asset WLC21

**Comment by ca333** [comment]
> if there is stil time also remove RFOX Utxo coin and add new RFOX ETH Coin if contract addr is known. _WLC_ is a legacy chain. **WLC21** is the swapped to chain

yes feel free to execute the update as it is just a config matter

**Comment by naezith** [comment]
We probably want this in 0.3.0  https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/530

**Review by Milerius — DISMISSED** [review]

**Review by smk762 — DISMISSED** [review]
MultiOS tests complete and identified issues resolved.
Great work guys!

**Review by naezith — DISMISSED** [review]

**Review by tonymorony — APPROVED** [review]

**Comment by ca333** [comment]
698b4b0 is this included in PR approvals? 
`Milerius dismissed stale reviews from tonymorony, naezith, smk762, and themself via 80f68cc`

**Review by tonymorony — APPROVED** [review]

**Review by naezith — APPROVED** [review]

**Review by Milerius — APPROVED** [review]

**Pull request merged**
