### PR TITLE
Rework Dex page & Application design.

### PR DESCRIPTION
**Pull request by ssakone**
Preview 
image

### CODE REVIEW

**Comment by tonymorony** [comment]
Thanks for the PR @ssakone ! the layout arrangement looks good on the small screen now

1) order book/best orders font too small, requires eyes strain on both small mac and full HD display, could you please try to increase it (ideally to system font size)?

on the right side of the screenshot, I put system fonts for comparison

Screenshot 2021-05-31 at 18 47 28


2) this title can be changed to something like a "Swap setup" or "Swap details" (maybe @smk762 got better suggestions)

Screenshot 2021-05-31 at 18 40 15

3) when minimizing this widget label doubling:

Screenshot 2021-05-31 at 19 09 11

4) what is the plan for this icon? (atm nothing happens on click):

Screenshot 2021-05-31 at 19 11 01

**Comment by ssakone** [comment]
@tonymorony  hello, not finish yet i m still working on it, i will list later checklist.

**Comment by tonymorony** [comment]
there is also a visual flickering bug when you selecting the order (top part of the order book scrolls to beginning) 
please check the video: https://drive.google.com/file/d/1CAbpqJwmd2ytqWU_yA9cbXTROd3zL1sW/view?usp=sharing

**Comment by tonymorony** [comment]
> @tonymorony hello, not finish yet i m still working on it, i will list later checklist.

hello! sure, I know 👍  it's just my feedback on the current state/iteration

**Comment by smk762** [comment]
> this title can be changed to something like a "Swap setup" or "Swap details" (maybe @smk762 got better suggestions)

"Place Order" sounds like good fit (other headers all have 'order' in them).

I'd change this bit too - 
image

The only options there are filtering the history / swaps lists. Change to "Trading Information".

"Chart View" could be just "Chart"
image

Swap amount not showing up on confirmation screen 
image

or at value in fiat / other coin at bottom of form
image

**Comment by Milerius** [comment]
> > this title can be changed to something like a "Swap setup" or "Swap details" (maybe @smk762 got better suggestions)
> 
> "Place Order" sounds like good fit (other headers all have 'order' in them).
> 
> I'd change this bit too -
> image
> 
> The only options there are filtering the history / swaps lists. Change to "Trading Information".
> 
> "Chart View" could be just "Chart"
> image
> 
> Swap amount not showing up on confirmation screen
> image
> 
> or at value in fiat / other coin at bottom of form
> image

Capture d’écran 2021-05-31 à 15 24 44
i'm able to see the amount on osx, is that on linux ? any warnings in the log from your side ?

**Comment by smk762** [comment]
tried to replicate and was fine - will see if I can catch glitch again.

**Comment by Milerius** [comment]
> tried to replicate and was fine - will see if I can catch glitch again.

ok ty, same for fiat values, i'm able to see it, maybe you had one problem with gecko provider for some times and now it's gone

**Comment by tonymorony** [comment]
great progress @ssakone , thanks!

1) The main problem for me at the moment is the view for coins without a graph:
selector stick to the top so eyes not focusing on it and the `Trading Information` widget is giant so there is a lot of empty space. We should brainstorm on how to re-arrange the layout in such cases:

Screenshot 2021-06-04 at 15 22 22

Screenshot 2021-06-04 at 15 22 22

2) Could you please not display this label if the `Place order` widget is minimized?

Screenshot 2021-06-04 at 15 22 22

**Comment by ssakone** [comment]
@smk762 , @tonymorony , @Milerius 
Need to test
Test list;

- [ ] Dex page correctly layout.
- [ ] Dex page text & icon correctly visible
- [ ] Dex page itemBox work well (close, reduice, expand, hide)
- [ ] Dex page new settings header work.
- [ ] Global header change & display correct balance, display well wallet name and disconnect work.

**Comment by tonymorony** [comment]
The volume field is confusing now in the case of long numbers because it's sticking to the right part of a number and displaying it not from the beginning (same with price field when you input manually). In the example below actual volume is 110.xxxx but I can see only 10.xxxx because the field sticks to a number end:

Screenshot 2021-06-06 at 22 22 38

Screenshot 2021-06-06 at 22 22 48

interesting that I can see some dot with russian translation:

Screenshot 2021-06-06 at 22 23 03

**Comment by tonymorony** [comment]
> there is also a visual flickering bug when you selecting the order (top part of the order book scrolls to beginning)
> please check the video: https://drive.google.com/file/d/1CAbpqJwmd2ytqWU_yA9cbXTROd3zL1sW/view?usp=sharing

this bug is still there

**Comment by tonymorony** [comment]
It's also possible to mess with fields when input is huge. I think it's worth to ensure that fields with numbers are fixed size to not overlay with text:

Screenshot 2021-06-07 at 15 11 33

**Comment by ssakone** [comment]
@tonymorony  i believe this commit will the two bug you tag
[befe240](https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/951/commits/befe2409b8def4c2640f9eb40a51fd455935938c)

**Comment by tonymorony** [comment]
> @tonymorony i believe this commit will solve the two bug you tag
> [befe240](https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/951/commits/befe2409b8def4c2640f9eb40a51fd455935938c)

@ssakone Price and volume fields don't work for me on this commit - shows 0, 0 on order select

image

can see values after press "Start swap"

image

**Review by tonymorony — APPROVED** [review]
it looks like bugs are resolved, let's wait for @smk762 smoke test and merge then

**Comment by smk762** [comment]
Some overflow in dex page coin dropdown with larger balances 
image

blank space for pairs without chart looks a bit wierd, maybe we can fill it with an alt graphic or graph with fiat/btc price of each coin (with pricing data)? For coins with no pricing API, maybe something like last swaps for pair?
Another option might be to extend swap history panel to fill it (and default to that). 
image

Price / volume fields working ok here. 

Header display and logout etc working ok.

No titles in minimised panels (except "Place Order")
image

Eyeball icon works as expected, and does the close icon. the minimise/maximise sometimes does nothing for some itemboxes
image

https://user-images.githubusercontent.com/35845239/121149126-f9f0c700-c874-11eb-8516-ce8f55246450.mp4

**Review by Milerius — APPROVED** [review]

**Review by tonymorony — CHANGES_REQUESTED** [review]
orderbook is "dancing" again: https://drive.google.com/file/d/1eqKlvzW57_l10piEZnHmRrzQa4sAqxkU/view?usp=sharing

**Comment by tonymorony** [comment]
@ssakone jfyi issue https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/951#pullrequestreview-679325415 still persists on my side, despite on  `Fix Orderbook Dancing.` 94dff50 commit

https://drive.google.com/file/d/1QxlncBdwDg8HAN8GRAzqa2cVSGlWYn_m/view?usp=sharing

**Comment by tonymorony** [comment]
noticed minor problem `History` should be from capital letter:

Screenshot 2021-06-09 at 19 16 36

**Comment by smk762** [comment]
Eyeball icon is open in some panes and closed in others, does not change on click and no relation to whether panel is visible or hidden (except the "Place Order" panel it looks a bit bolder when shut)

**Review by tonymorony — APPROVED** [review]
orderbook flickering a little bit on orders switch but not so much now

@smk762 could you please create a separate issue for the eyes problem?

**Pull request merged**
