### PR TITLE
fix(project): Installer scripts not compliant with project.metadata.cmake

### PR DESCRIPTION
**Pull request by SylEze**
Some installer scripts like `installscript.qs` are still hardcoded, thus it cannot work on dexes with custom names

### CODE REVIEW

**Comment by Milerius** [comment]
@smk762 please check if installer work correctly on windows/osx (that doesn't solve the DLL problems but should solve the shortcut problem on windows, and name of maintenance tool on osx)

**Comment by smk762** [comment]
Windows Installer working on PC where I have dlls. Maintenance tool shortcut is pointing to wrong path tho:
image

Manually created `"C:\Program Files\AtomicDex Desktop\AtomicDex Desktop Maintenance Tool.exe"`
Created by installer `"C:\Users\smk\AtomicDex Desktop\AtomicDEX Maintenance Tool.exe"`

On Mac, I get `zsh: segmentation fault`

**Comment by smk762** [comment]
working on mac now.
on windows, maintenance tool link not showing up in start menu, but exists in 
`C:\Users\smk\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\AtomicDex Desktop`
 and shortcut path works to launch tool. 
 Not sure why not in start menu, assume if in that path it should be.

**Comment by SylEze** [comment]
> working on mac now.
> on windows, maintenance tool link not showing up in start menu, but exists in
> `C:\Users\smk\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\AtomicDex Desktop`
> and shortcut path works to launch tool.
> Not sure why not in start menu, assume if in that path it should be.

I guess your Windows did not correctly refresh, did you restart your session/system and try again if it appears correctly in start menu ?

**Comment by smk762** [comment]
after rebooting, uninstalling and reinstalling it shows up - likely a quirk of windows

**Review by smk762 — APPROVED** [review]

**Pull request merged**
