### PR TITLE
fix import wallet login issue

### PR DESCRIPTION
**Pull request by smk762**
ref: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1461

### CODE REVIEW

**Comment by smk762** [comment]
closed https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1466 as it was a PR to a closed branch.

**Comment by tonymorony** [comment]
Let's keep it open for now, @ssakone will open clean PR with https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1466 changes, then we'll check if the problem actual on it and change PR target if needed

**Comment by smk762** [comment]
> Let's keep it open for now, @ssakone will open clean PR with #1466 changes, then we'll check if the problem actual on it and change PR target if needed

Reopened https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1466

**Comment by ssakone** [comment]
https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1468 cc [ @smk762  @tonymorony ]

**Review by tonymorony — APPROVED** [review]

**Review by SylEze — APPROVED** [review]

**Pull request merged**
