### PR TITLE
feat(portfolio): Use more performant assets list view

### PR DESCRIPTION
**Pull request by SylEze**
- [x] Make balance sort working
- [ ] Make it look exactly as previous assets list (or improve it ?)
- [x] Fix swap ongoing notification

### CODE REVIEW

**Comment by Milerius** [comment]
Thanks for the push, in addition to the pending list the alignment of the headers is also incorrect (full screen):

image

**Comment by tonymorony** [comment]
not tested PR yet but can see from screenshot that there is no zebra color in dashboard now, please return it :)

**Comment by Milerius** [comment]
I've checked the last commit @tonymorony and i really like the new effect, can you take a look too ?

**Comment by tonymorony** [comment]
> I've checked the last commit @tonymorony and i really like the new effect, can you take a look too ?

sure, will test tonight or tomorrow

**Comment by Milerius** [comment]
Recording of the new effetc:
https://user-images.githubusercontent.com/21139416/132089842-c276e8ee-2ea4-46c1-9e65-b2dff1cefdbf.mov

**Comment by tonymorony** [comment]
> Recording of the new effetc:
> 
>  Enregistrement.de.l.ecran.2021-09-04.a.11.31.44.mov

it looks good in dark theme but the color is not correct in light theme (it should be the same as in pia diagram area and as in search field)

**Comment by Milerius** [comment]
Would also be nice to align those one:

Capture d’écran 2021-09-05 à 06 33 22
Capture d’écran 2021-09-05 à 06 33 24

**Comment by tonymorony** [comment]
receiving "too many opened files" and network dying on 70 coins activation:

Screenshot 2021-09-06 at 14 26 11

[2021-09-06-07-16-52.mm2.log](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/7114079/2021-09-06-07-16-52.mm2.log)


```
06 07:17:44, utxo_common:2422] Error "tx_cache:19] common:1499] Can't open \"/Users/antonlysakov/Library/Application Support/AtomicDex Desktop/mm2/DB/a19f7aa254dced0a17920ab1c2acf698841f67f6/TX_CACHE/2074dd7ad1d4a09a49dfe99bacbe7af45c4e060f91812b62a511a13bfdc41d34\": Too many open files (os error 24)" loading the 2074dd7ad1d4a09a49dfe99bacbe7af45c4e060f91812b62a511a13bfdc41d34 transaction. Try request tx using Rpc client
```

**Review by smk762 — APPROVED** [review]

**Pull request merged**
