### PR TITLE
Filtering enhance

### PR DESCRIPTION
**Pull request by ssakone**

### CODE REVIEW

**Review by ssakone — COMMENTED** [review]
operand fixed!

**Review by smk762 — DISMISSED** [review]
Nice, thanks!

**Comment by ssakone** [comment]
> Nice, thanks!

not finished yet, need some basic improvement in proview, soon :)

**Comment by smk762** [comment]
ah ok.. btw pro view has little bug also - https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1041

**Comment by Milerius** [comment]
let's solve #1041 first too

**Comment by Milerius** [comment]
Capture d’écran 2021-06-28 à 06 23 44

Still uncorrect for me (cannot see the date properly)

**Comment by Milerius** [comment]
@ssakone the pr is conflicting

**Comment by smk762** [comment]
coins and dates are visible ok here on pro and simple views. Spotted a new over flow though -
image

**Comment by ssakone** [comment]
> coins and dates are visible ok here on pro and simple views. Spotted a new over flow though -
> image
> 
> This is only on Pro view, not on simple.

yes this bug is here long time, i will fix it in the week in Qaterial Repo.

**Review by smk762 — APPROVED** [review]
Calendar overflow bug is non-blocking

**Pull request merged**
