### PR TITLE
Fix enable coins modal

### LINKED ISSUE #1730: [FEATURE REQUEST]: windows size in user interface settings
It would be nice to make this selection box a bit larger in order to remove the scroll and show all the choices.
Because the user may simply not see the third parameter and may get confused about the way to scroll.

image

image

### LINKED ISSUE #1735: [FEATURE REQUEST]: enable assets window upgrade
think the "enable assets" window needs some upgrade:
image

### PR DESCRIPTION
**Pull request by SylEze**
Closes #1735 
Closes #1730

### CODE REVIEW

**Comment by smk762** [comment]
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1730 :heavy_check_mark: 

Text color for enable coin filter doesn't change based on theme, so is hard to see in dark mode. Same issue seems to affect the "busy" spinning circles also in dark mode (seen when logging in etc).

`change assets limit` / `add custom assets` buttons could do with a little more margin at top.

Preview modal for custom QRC20 exceeds app window, cant see buttons at the bottom.

Some errors seen in log while adding custom - 
```[21:06:58] [warning] [main.prerequisites.hpp:92] [3367546]: qrc:/Dex/Components/MultipageModalContent.qml:43:9: QML ColumnLayout: Possible anchor loop detected on centerIn.
[21:06:58] [warning] [main.prerequisites.hpp:92] [3367546]: qrc:/Dex/Components/MultipageModalContent.qml:32:5: QML DefaultFlickable: Binding loop detected for property "contentHeight"
[21:06:58] [warning] [main.prerequisites.hpp:92] [3367546]: qrc:/Dex/Components/MultipageModal.qml:114:9: QML StackLayout: Binding loop detected for property "height"
```

**Comment by smk762** [comment]
@Canialon ready for review

**Comment by cipig** [comment]
when i go to settings and want to change the max number of enabled coins, logs are spammed with this errors and i need to kill the app
```
[23:28:13] [warning] [main.prerequisites.hpp:92] [19455]: qrc:/Dex/Components/DexComboBox.qml:122:22: QML DexListView: possible QQuickItem::polish() loop
[23:28:13] [warning] [main.prerequisites.hpp:92] [19455]: qrc:/Dex/Components/DexComboBox.qml:122:22: QML DexListView: DexListView called polish() inside updatePolish() of DexListView
```

**Comment by cipig** [comment]
can't select any coin in the coins enable window, idk if related to the number (have > 100 enabled, but max. setting is at 50 because i can't change that any more) or related to something else

**Comment by smk762** [comment]
> can't select any coin in the coins enable window, idk if related to the number (have > 100 enabled, but max. setting is at 50 because i can't change that any more) or related to something else

Should be good now :crossed_fingers:

**Review by cipig — APPROVED** [review]

**Pull request merged**
