### PR TITLE
enhance(ItemBox): add ItemBox manager & make sure only itemBox is resized

### PR DESCRIPTION
**Pull request by ssakone**

### CODE REVIEW

**Comment by ssakone** [comment]
One more bug to fix. not ready.

**Comment by smk762** [comment]
Not 100% sure what I'm testing here?
Anyways, here's a video of the best orders/orderbook toggle buttons and what they do (or don't)

https://user-images.githubusercontent.com/35845239/118597023-b8717c80-b7de-11eb-80a2-f16837758b4c.mp4

Eyeball icon works ok - but best orders not completely filling space if orderbook hidden.
The expand / contract icon seems to expand ok, but generally does not contract when clicking again.
Expand / contract button for exchange rate / swaps / history panel does nothing at all.

**Comment by tonymorony** [comment]
@ssakone could you please share a test checklist similar to https://github.com/KomodoPlatform/atomicDEX-API/pull/915#pullrequestreview-640997994 ?

**Comment by Milerius** [comment]
> @ssakone could you please share a test checklist similar to [KomodoPlatform/atomicDEX-API#864 (comment)](https://github.com/KomodoPlatform/atomicDEX-API/issues/864#issuecomment-822423391) ?

or this way too: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/935#issue-650620408

**Comment by ssakone** [comment]
> @ssakone could you please share a test checklist similar to [KomodoPlatform/atomicDEX-API#864 (comment)](https://github.com/KomodoPlatform/atomicDEX-API/issues/864#issuecomment-822423391) ?

Sure, not totally ready yet, I have to make some change, 
- Visual bug when its expand, and user change application window size (from maximizing to normal), component is not correctly resized.

**Pull request closed without merging**
