### PR TITLE
add GRMS

### PR DESCRIPTION
**Pull request by smk762**
Replaces https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1243

### CODE REVIEW

**Comment by Miner113** [comment]
It worked without any errors

**Comment by Miner113** [comment]
Снимок

**Comment by Milerius** [comment]
Thanks for the pr @smk762  and @Miner113 - i'm merging it

**Comment by cipig** [comment]
@Miner113 both GRMS electrums are currently down

**Pull request merged**
