### PR TITLE
add loading spinners

### PR DESCRIPTION
**Pull request by smk762**
re: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1283#issuecomment-919981251
closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1283

before:

https://user-images.githubusercontent.com/35845239/154217873-cc29c9ed-b0cf-4092-89a2-303fa1d024e8.mp4

after:

https://user-images.githubusercontent.com/35845239/154225189-e4a58bca-1106-433b-818a-ccfc6197fc09.mp4

### CODE REVIEW

**Comment by tonymorony** [comment]
lgtm 👍

lets just unify spinners colour please (on top it's green, on bottom blue)

I do propose to use blue everywhere

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by tonymorony** [comment]
```
-- Build files have been written to: /Users/runner/work/atomicDEX-Desktop/atomicDEX-Desktop/ci_tools_atomic_dex/build-Release
ninja: error: '../../atomic_defi_design/Dex/Components/DexBusyIndicator.qml', needed by 'src/atomicdex-desktop_autogen/5VGQ2LHQ6Y/qrc_qml.cpp', missing and no known rule to make it
```

@smk762 your latest changes not compiling

**Comment by smk762** [comment]
Oops, was compiling locally but I left a file out in last commit.

**Review by tonymorony — APPROVED** [review]

**Comment by smk762** [comment]
Latest commit fixes a bug where parent chain gas is too low for swap. Previously, in this case no error was detected (unless parent balance was zero).
@Milerius not sure if this might be better handled in another way by adding or tweaking the for `TradingError` list. Not sure if this error can be determined until after trade_preimage completes, so I tapped into that in the back end to communicate error.

**Review by Milerius — APPROVED** [review]
I approve for the backend part!

**Review by tonymorony — APPROVED** [review]

**Review by SylEze — APPROVED** [review]

**Pull request merged**
