### PR TITLE
feat(recover_funds): more precise recover funds, and use good http st…

### PR DESCRIPTION
**Pull request by Milerius**
…atus

### CODE REVIEW

**Comment by smk762** [comment]
image

I get same as before. Should I try and simulate a new failed swap?

**Comment by tonymorony** [comment]
jfyi: PR got conflict with translation now also
`atomic_defi_design/assets/languages/atomic_defi_fr.ts`

**Comment by tonymorony** [comment]
@smk762 for my old swaps it printing valid message (not very user-friendly tho):
image

**Comment by Milerius** [comment]
> image
> 
> I get same as before. Should I try and simulate a new failed swap?

Yes it's expected for this one

**Comment by Milerius** [comment]
> @smk762 for my old swaps it printing valid message (not very user-friendly tho):
> image

In the future with mm2 2.0 rpc call error message will be improved because it's will be separated into different field and easier to translate for example.

**Comment by tonymorony** [comment]
`In the future with mm2 2.0 rpc call error message will be improved because it's will be separated into different field and easier to translate for example.`

I meant not the error message itself but error decoration, print plain JSON is not a good practice in GUI. Unlikely you'll see in production-ready desktop application error in plain text. But yeah, it's unrelated to this PR

**Review by smk762 — APPROVED** [review]

**Pull request merged**
