### PR TITLE
Disallow disabing of parent while token active

### PR DESCRIPTION
**Pull request by smk762**
To Test:
- Activate a token for every EVM protocol.
- Ensure parent coin activates alongside it
- Try to disable parent coin in wallet and portfolio page while token is enabled. It should be greyed out.
- Disable all the tokens for the EMV protocol but keep parent coin enabled.
- Try to disable parent coin in wallet and portfolio page while no token is enabled. It should possible.

### CODE REVIEW

**Review by cipig — DISMISSED** [review]

**Review by Canialon — CHANGES_REQUESTED** [review]
>Try to disable parent coin in wallet and portfolio page while token is enabled. It should be greyed out.

I guess it makes sense to add some info about why the user cant deactivates the parent coin. Now it is just unclear. need some info wny user cant deactivate it
image

_______

Also, some parents cant be deactivated even if there are no active tokens. At least  bnb, avax and ftm(upd: can deactivate ftm after double token activation and diactivation)
image

**Comment by Canialon** [comment]
>Disable all the tokens for the EMV protocol but keep parent coin enabled.

Parent coin deactivates with all tokens 


https://user-images.githubusercontent.com/77272165/201622512-ba68db86-7ba2-4739-9e6c-4a290e23e6ba.mov

**Comment by smk762** [comment]
> > Disable all the tokens for the EMV protocol but keep parent coin enabled.
> 
> Parent coin deactivates with all tokens
> 
>  Screen.Recording.2022-11-14.at.09.20.15.mov

This as the previous result also perhaps we can improve the message to say "Disable BNB and ALL BEP20 assets". BNB is tagged as "type:BEP-20" so internally it is considered a BEP20 asset. I'm not sure if we want the EVM parent to not disable in this case.

**Comment by smk762** [comment]
> I guess it makes sense to add some info about why the user cant deactivates the parent coin. Now it is just unclear. need some info why user cant deactivate it 

Lets add this as an issue for later. There is some existing code which would show a pop up saying "cant deativate default coin" which I dont think is in use at the moment, but that is a bad ux flow. Maybe we ca have a tooltip in the context menu :thinking: 

> Also, some parents cant be deactivated even if there are no active tokens. At least bnb, avax and ftm(upd: can deactivate ftm after double token activation and deactivation) 

I'll check to replicate here - there may be a slight delay before app knows tokens are inactive so if its just like that for a few seconds after, that might explain it.

**Comment by SirSevenG** [comment]
> Parent coin deactivates with all tokens

It makes sense to me at least. We my change deactivation phrase tho, to make it more clear for enduser.

**Comment by Canialon** [comment]
okay it make sense
but this moment is still here, cant deactivate avax and bnb:
image

**Comment by smk762** [comment]
Thanks for feedback @Canialon - the BNB AVX FTM problems should now be fixed

**Comment by smk762** [comment]
Good question. I think we can leave that for next iteration, because at the moment is has been a bit hybrid while guis have had slightly different coins file requirements. for 0.5.8 we can resolve that more accurately in the back end.

**Review by Canialon — APPROVED** [review]

**Review by SirSevenG — APPROVED** [review]

**Pull request merged**
