### PR TITLE
Fix webengineview crash

### LINKED ISSUE #1119: [BUG]: Crash on MacOS (M1)
**Describe the bug**
Caught a crash on my mac, happened on tabs switching (from the dashboard to DEX if I remember correctly)

end of app log contains crash backtrace:
[2021-07-19-01-30-29.log](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/6837790/2021-07-19-01-30-29.log)

` 2# QQuickWebEngineViewPrivate::~QQuickWebEngineViewPrivate() in /Applications/atomicdex-desktop.app/Contents/Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine`

maybe it was a switch from wallet to dex, that correlates with reports of crashes with white screen on place of coin graph

### LINKED ISSUE #1248: [BUG]: QWebEngine view and loader may cause crashing
**Describe the bug**

Each time we switch between dashboard page's we use a qml `Loader`

Every object inside this loader is being reconstruct-ed each time.

and this may cause the QWebEngine to crash when the loading time take longer than expected (many coins activated for example): 

```
QQuickWebEngineViewPrivate::~QQuickWebEngineViewPrivate() qscopedpointer.h:118
QQuickWebEngineViewPrivate::~QQuickWebEngineViewPrivate() 0x00007f9a8aa860ca
QQuickWebEngineViewPrivate::~QQuickWebEngineViewPrivate() 0x00007f9a8aa86469
QQuickWebEngineView::~QQuickWebEngineView() qscopedpointer.h:60
QQuickWebEngineView::~QQuickWebEngineView() qscopedpointer.h:107
QQuickWebEngineView::~QQuickWebEngineView() 0x00007f9a8aa82acc
QQmlPrivate::QQmlElement<QQuickWebEngineView>::~QQmlElement() qqmlprivate.h:144
QQmlPrivate::QQmlElement<QQuickWebEngineView>::~QQmlElement() qqmlprivate.h:144
QQmlObjectCreator::clear() 0x00007f9a81654ef0
QQmlIncubatorPrivate::clear() 0x00007f9a815e36da
QQmlIncubator::clear() 0x00007f9a815e37ea
QQmlIncubatorPrivate::clear() 0x00007f9a815e3715
QQmlIncubator::clear() 0x00007f9a815e37ea
QQuickLoaderPrivate::clear() 0x00007f9a81f201a7
QQuickLoader::setSourceComponent(QQmlComponent*) 0x00007f9a81f21227
QQuickLoader::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) 0x00007f9a81f22268
QObjectPointerBinding::write(QV4::Value const&, bool, QFlags<QQmlPropertyData::WriteFlag>) qqmlpropertydata_p.h:375
QObjectPointerBinding::write(QV4::Value const&, bool, QFlags<QQmlPropertyData::WriteFlag>) 0x00007f9a81646f91
QQmlNonbindingBinding::doUpdate(QQmlJavaScriptExpression::DeleteWatcher const&, QFlags<QQmlPropertyData::WriteFlag>, QV4::Scope&) 0x00007f9a8164884f
QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) 0x00007f9a81645363
QQmlBinding::refresh() 0x00007f9a8164562e
QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) 0x00007f9a8161de18
QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) 0x00007f9a815cd5c6
void doActivate<false>(QObject*, int, void**) 0x00007f9a80169c36
QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) 0x00007f9a815c79d9
QV4::QObjectWrapper::setProperty(QV4::ExecutionEngine*, QObject*, QQmlPropertyData*, QV4::Value const&) 0x00007f9a8150a780
QV4::QObjectWrapper::setQmlProperty(QV4::ExecutionEngine*, QQmlContextData*, QObject*, QV4::String*, QV4::QObjectWrapper::RevisionMode, QV4::Value const&) 0x00007f9a8150b31d
QV4::QObjectWrapper::virtualPut(QV4::Managed*, QV4::PropertyKey, QV4::Value const&, QV4::Value*) 0x00007f9a8150b487
QV4::Lookup::setterFallback(QV4::Lookup*, QV4::ExecutionEngine*, QV4::Value&, QV4::Value const&) qv4object_p.h:318
QV4::Lookup::setterFallback(QV4::Lookup*, QV4::ExecutionEngine*, QV4::Value&, QV4::Value const&) 0x00007f9a81493ad6
<unknown> 0x00007f99a47c0a3a
QV4::Moth::VME::exec(QV4::CppStackFrame*, QV4::ExecutionEngine*) 0x00007f9a815286a9
QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*) 0x00007f9a814bd1e5
QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) 0x00007f9a8163e43a
QQmlBoundSignalExpression::evaluate(void**) 0x00007f9a815e9d4c
QQmlBoundSignal_callback(QQmlNotifierEndpoint*, void**) 0x00007f9a815eb613
QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) 0x00007f9a8161de18
QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) 0x00007f9a815cd5c6
void doActivate<false>(QObject*, int, void**) 0x00007f9a80169c36
QMetaObject::activate(QObject*, QMetaObject const*, int, void**) 0x00007f9a80163479
QQuickMouseArea::clicked(QQuickMouseEvent*) 0x00007f9a81f0f0f2
QQuickMouseArea::setPressed(Qt::MouseButton, bool, Qt::MouseEventSource) 0x00007f9a81f106cb
QQuickMouseArea::mouseReleaseEvent(QMouseEvent*) 0x00007f9a81f116c4
QQuickItem::event(QEvent*) 0x00007f9a81eb0f5e
QApplicationPrivate::notify_helper(QObject*, QEvent*) 0x00007f9a7f53e43c
QApplication::notify(QObject*, QEvent*) 0x00007f9a7f544f20
QCoreApplication::notifyInternal2(QObject*, QEvent*) 0x00007f9a80131808
QQuickWindowPrivate::deliverMouseEvent(QQuickPointerMouseEvent*) 0x00007f9a81ec8d67
QQuickWindowPrivate::deliverPointerEvent(QQuickPointerEvent*) 0x00007f9a81ec9f74
QQuickWindowPrivate::handleMouseEvent(QMouseEvent*) 0x00007f9a81ecaf05
QWindow::event(QEvent*) 0x00007f9a8080463b
QQuickWindow::event(QEvent*) 0x00007f9a81ecc3b9
QApplicationPrivate::notify_helper(QObject*, QEvent*) 0x00007f9a7f53e43c
QApplication::notify(QObject*, QEvent*) 0x00007f9a7f544f20
QCoreApplication::notifyInternal2(QObject*, QEvent*) 0x00007f9a80131808
QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) 0x00007f9a807f956d
QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) 0x00007f9a807fa955
QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x00007f9a807d68ab
::xcbSourceDispatch(GSource *, GSourceFunc, gpointer) 0x00007f9a6485469a
g_main_context_dispatch 0x00007f9a7b8c917d
<unknown> 0x00007f9a7b8c9400
g_main_context_iteration 0x00007f9a7b8c94a3
QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x00007f9a8018d1cc
QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) 0x00007f9a8013021a
QCoreApplication::exec() 0x00007f9a801391d3
run_app(int, char**) main.prerequisites.hpp:497
main main.cpp:38
__libc_start_main 0x00007f9a7ea520b3
_start 0x00000000004347fe
```

Usage:

```
➜  atomic_defi_design git:(re-enable-notifications) ✗ grep -Hrn "WebEngineView" .
./qml/Wallet/Main.qml:570:                WebEngineView {
./qml/Portfolio/SmartChartView.qml:135:                                 WebEngineView {
./qml/Exchange/Trade/CandleStickChart.qml:132:        WebEngineView {
./qml/Components/Blank.qml:49:                        WebEngineView {
```

Please remove the occurence that are not used, what is the component Blank ? is it dead code ? 

Please have only 2 global webengineview object, one for the dex page, and one for the wallet, and manipulate those objects when needed

Please be sure to respect the following approach for the QWebEngineView that are currently used:

https://doc.qt.io/qt-5/qtqml-javascript-dynamicobjectcreation.html

We want them to be only created once at the first login, and never get destroyed afterwards.

### PR DESCRIPTION
**Pull request by SylEze**
Might close #1119
Might close #1248

### CODE REVIEW

**Comment by smk762** [comment]
Seeing this in logs for wallet chart - 
```
[15:27:27] [warning] [main.prerequisites.hpp:92] [1003327]: qrc:/atomic_defi_design/qml/Wallet/Main.qml:516: ReferenceError: chart is not defined
```
Stuck on 
image

No crash during tests (rapid change from wallet to DEX where selections both have chart) on Linux. 

LMK how best to test this otherwise - Was this mostly an issue on M1 Macs? I cant cover that test case here.

**Comment by SylEze** [comment]
> Seeing this in logs for wallet chart -
> 
> ```
> [15:27:27] [warning] [main.prerequisites.hpp:92] [1003327]: qrc:/atomic_defi_design/qml/Wallet/Main.qml:516: ReferenceError: chart is not defined
> ```
> 
> Stuck on
> image
> 
> No crash during tests (rapid change from wallet to DEX where selections both have chart) on Linux.
> 
> LMK how best to test this otherwise - Was this mostly an issue on M1 Macs? I cant cover that test case here.

Indeed it was mostly present on M1 Macs, but @Milerius told me that he was able to reproduce on Linux

**Comment by smk762** [comment]
No crashes detected here yet. 

Any chance we can avoid the white defualt white background flickering on change in dark mode (lite mode is ok)?
https://user-images.githubusercontent.com/35845239/132842890-bf190823-e5ba-499c-97f0-f817fc90d83c.mp4

**Comment by SylEze** [comment]
> No crashes detected here yet, seeing chart on wallet now.
> 
> Any chance we can avoid the white defualt white background flickering on change in dark mode (lite mode is ok)?
> https://user-images.githubusercontent.com/35845239/132842890-bf190823-e5ba-499c-97f0-f817fc90d83c.mp4

Yeah sure, I can make the web view hidden until it's fully loaded

**Comment by smk762** [comment]
Just got a crash on Windows , logs attached.
[2021-09-10-11-05-38.log](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/7143369/2021-09-10-11-05-38.log)

**Comment by smk762** [comment]
Just noticed that on wallet page, if switching to a different coin that has no chart (e.g. RICK/MORTY), the previously loaded chart is still displayed.
In earlier versions, it would display as below instead
image

**Comment by smk762** [comment]
On dex page if switching from pair with chart to pair without, can we extend the lower section?
image

vs
image

**Review by smk762 — APPROVED** [review]

**Pull request merged**
