### PR TITLE
Min vol bug

### PR DESCRIPTION
**Pull request by smk762**
closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2183

To test:
- go to pro view with a pair which you have low balance (< minvol / 4)
- If balance at 25, 50 or 100 % would be less than min vol, these buttons should show as "min" (and if 50% of balance is < minvol, there should only be "min" or "max" button"
- Confirm clicking buttons returns sane values.

### CODE REVIEW

**Comment by smk762** [comment]
hold off on review for a bit - we shouldnt let user click 25% or 50% and not have the value returned be something different to 35% or 50%

**Comment by smk762** [comment]
ready for review

**Comment by cipig** [comment]
i have a coin with a balance of 0.00154

if i click on sell, input a price of 1 i see this (because i can sell 25% of 0.00154 at a price of 1 and the other coins is also 0.00154)
image

if i change the price to 0.1 i see this (25% and 50% disappeared because i can't sell 25% of 0.00154 at a price of 0.1, the other coins volume would be less then 0.0001)
image

if i then change price again to 1, the 25% and 50% buttons don't come back... i have to switch to "buy" and back to "sell" to see them again
just a minor thing though

**Comment by SirSevenG** [comment]
> if i then change price again to 1, the 25% and 50% buttons don't come back... i have to switch to "buy" and back to "sell" to see them again

Got the same thing, pressin' on checkbox for custom min Volume also returns 25% and 50% buttons.

**Comment by cipig** [comment]
image
getting this error when i want to start a swap
it is shown after i click on "start swap" button
is it related? is the error from mm2 or from GUI? looks like a rounding error...

**Comment by smk762** [comment]
> image getting this error when i want to start a swap it is shown after i click on "start swap" button is it related? is the error from mm2 or from GUI? looks like a rounding error...
> 
> i get the same error even if i lower the volume in the selected order, which results in fewer VRSC needed for the swap, but still same error

Error message has changed so not sure if this still exists, but other feedback issues have been resolved.

**Comment by SirSevenG** [comment]
Had an issue with existing wallet.
So, updated to this branch, started app - all loaded just fine, selected existing wallet, enter password to it, got crash.
```
[20:19:33] [info] [qt.addressbook.page.cpp:66] [8032]: post_login: filling addressbook from cfg
[20:19:33] [info] [addressbook.cfg.cpp:44] [8032]: Addressbook configuration file read.
[20:19:33] [warning] [main.prerequisites.hpp:93] [8032]: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

[20:19:33] [error] [main.prerequisites.hpp:99] [8032]: Object 0x235ab59ce60 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/Dex/Screens/Startup/Login.qml:74: function() { [native code] }
[20:19:33] [error] [main.prerequisites.hpp:107] [8032]: sigabort received, cleaning mm2
[20:19:33] [error] [cpprestsdk.utilities.cpp:51] [7556]: pplx task error: WinHttpSendRequest: 12007: The server name or address could not be resolved
```

And again and agian... removed that wallet, re-imported same seed, app works with no issues. Can't reproduce 2nd time for now.
@smk762 should i just repost this to crashes issue and ignore it for current pr?

**Comment by smk762** [comment]
> Had an issue with existing wallet. So, updated to this branch, started app - all loaded just fine, selected existing wallet, enter password to it, got crash.
> 
> ```
> [20:19:33] [info] [qt.addressbook.page.cpp:66] [8032]: post_login: filling addressbook from cfg
> [20:19:33] [info] [addressbook.cfg.cpp:44] [8032]: Addressbook configuration file read.
> [20:19:33] [warning] [main.prerequisites.hpp:93] [8032]: Qt has caught an exception thrown from an event handler. Throwing
> exceptions from an event handler is not supported in Qt.
> You must not let any exception whatsoever propagate through Qt code.
> If that is not possible, in Qt 5 you must at least reimplement
> QCoreApplication::notify() and catch all exceptions there.
> 
> [20:19:33] [error] [main.prerequisites.hpp:99] [8032]: Object 0x235ab59ce60 destroyed while one of its QML signal handlers is in progress.
> Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
> This behavior is NOT supported!
> qrc:/Dex/Screens/Startup/Login.qml:74: function() { [native code] }
> [20:19:33] [error] [main.prerequisites.hpp:107] [8032]: sigabort received, cleaning mm2
> [20:19:33] [error] [cpprestsdk.utilities.cpp:51] [7556]: pplx task error: WinHttpSendRequest: 12007: The server name or address could not be resolved
> ```
> 
> And again and agian... removed that wallet, re-imported same seed, app works with no issues. Can't reproduce 2nd time for now. @smk762 should i just repost this to crashes issue and ignore it for current pr?

Thanks for report. Please add log to https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2143
The changes here don't touch that area of code so unrelated to this PR.

**Review by SirSevenG — CHANGES_REQUESTED** [review]
> Error message has changed so not sure if this still exists, but other feedback issues have been resolved.

This might be related:
image

Same order, but with coins swapped around can be matched:
image

And I stil lcan reproduce this:
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2183#issuecomment-1346416654

**Comment by smk762** [comment]
> image getting this error when i want to start a swap it is shown after i click on "start swap" button is it related? is the error from mm2 or from GUI? looks like a rounding error...
> 
> i get the same error even if i lower the volume in the selected order, which results in fewer VRSC needed for the swap, but still same error

Confirmed this also still present - couldn't find the string in code, looks like it comes direct from API. Will detect and modify so message is readable, then figure out how to tweak max vol calc to avoid it.

**Comment by cipig** [comment]
> Confirmed this also still present - couldn't find the string in code, looks like it comes direct from API. Will detect and modify so message is readable, then figure out how to tweak max vol calc to avoid it.

If it's from API, then it's related to the volume you pass to the `buy`/`sell` call... afaik it should be the volume in rational, not in decimal

**Comment by smk762** [comment]
> > Confirmed this also still present - couldn't find the string in code, looks like it comes direct from API. Will detect and modify so message is readable, then figure out how to tweak max vol calc to avoid it.
> 
> If it's from API, then it's related to the volume you pass to the `buy`/`sell` call... afaik it should be the volume in rational, not in decimal

yeah its from `trade_preimage` response. I checked the code - we're still using the v1 method - I'll update it to v2

**Comment by smk762** [comment]
> > Error message has changed so not sure if this still exists, but other feedback issues have been resolved.
> 
> This might be related: image
> 
> Same order, but with coins swapped around can be matched: image
> 
> And I still can reproduce this: [#2183 (comment)](https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2183#issuecomment-1346416654)

There is a lag on the orderbook sometimes where it shows "not enough balance" while waiting for backend updates. I've looked into reducing this (or putting up a spinner until ready), but will handle it in a separate PR.

**Review by cipig — APPROVED** [review]

**Comment by cipig** [comment]
trying to sell JMXN for JEUR on PLG20... i have 220 JMXN
i select the bid in orderbook and click on 25%, it sets the volume at 55 JMXN, with 50% it sets it to 21 JMXN and with and with max it is 220 JMXN
the 50% button is wrong... should be 110 JXMN... max and 25% are fine

**Comment by smk762** [comment]
closing - will address issue in separate PR. This one has become too large / out of scope, and should only be used as reference for the fix.

**Pull request closed without merging**
