### PR TITLE
0.5.7 -> 0.5.7.1

### PR DESCRIPTION
**Pull request by smk762**
Updates version to 0.5.7.1

### CODE REVIEW

**Comment by smk762** [comment]
To test: launch app and check in settings that the following values are present
image

**Comment by smk762** [comment]
CI builds at https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/4331570383

**Review by SirSevenG — APPROVED** [review]

**Review by Canialon — CHANGES_REQUESTED** [review]
`Coins file does not exist!` :'(

image

**Comment by smk762** [comment]
replicated here on one wallet (others are ok). Will fix asap.
```
[19:46:02] [debug] [mm2.service.cpp:200] [657451]: retrieve_coins_informations
[19:46:02] [debug] [mm2.service.cpp:54] [657451]: checking for reconfiguration
[19:46:02] [info] [mm2.service.cpp:66] [657451]: opening file: /home/smk762/.atomic_qt/config/0.5.7.1-coins.EGGS.json
[19:46:02] [info] [mm2.service.cpp:63] [657451]: There is a precedent configuration file, upgrading the new one with precedent settings
[19:46:02] [info] [mm2.service.cpp:75] [657451]: opening file: /home/smk762/.atomic_qt/config/0.5.7.1-coins.EGGS.json
[19:46:02] [info] [mm2.service.cpp:100] [657451]: closing file: /home/smk762/.atomic_qt/config/0.5.7.1-coins.EGGS.json
[19:46:02] [info] [mm2.service.cpp:102] [657451]: closing file: /home/smk762/.atomic_qt/config/0.5.7.1-coins.EGGS.json
[19:46:02] [info] [mm2.service.cpp:106] [657451]: opening file: /home/smk762/.atomic_qt/config/0.5.7.1-coins.EGGS.json
[19:46:02] [info] [mm2.service.cpp:119] [657451]: closing file: /home/smk762/.atomic_qt/config/0.5.7.1-coins.EGGS.json
[19:46:02] [info] [mm2.service.cpp:207] [657451]: Retrieving Wallet information of /home/smk762/.atomic_qt/config/0.5.7.1-coins.EGGS.json
[19:46:02] [debug] [mm2.service.cpp:237] [657451]: Coins file does not exist!
[19:46:02] [info] [qt.global.coins.cfg.model.cpp:210] [657451]: Initializing global coin cfg model with size 1
[19:46:02] [debug] [mm2.service.cpp:237] [657451]: Coins file does not exist!
```

**Review by Canialon — APPROVED** [review]
coin file back:) version `0.5.7.1-beta`
Thanks!

**Review by tonymorony — APPROVED** [review]

**Pull request merged**
