### PR TITLE
fix(wallet): Chart was displayed on a ticker without supported pair

### LINKED ISSUE #1306: [BUG]: Wallet might show chart on a ticker with no chart
How to reproduce: switch from a ticker with a chart to a ticker with no chart when the chart has not started loading yet

### PR DESCRIPTION
**Pull request by SylEze**
Closes #1306 

The bug was reproduced by switching from a ticker with a chart to a ticker with no chart when the chart has not started loading yet

### CODE REVIEW

**Comment by tonymorony** [comment]
The issue with chats seems to be fixed, but I do have another pb with this build (not cute tx syncing spinner appear after I switch coin page back and forth):

https://user-images.githubusercontent.com/24797699/133835766-86f30a85-840a-4620-bde9-1b5a21fa5c44.mov

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by SylEze** [comment]
> The issue with chats seems to be fixed, but I do have another pb with this build (not cute tx syncing spinner appear after I switch coin page back and forth):
> Screen.Recording.2021-09-18.at.01.18.56.mov

I cannot reproduce this behaviour even with dozens of tries and it is not related to any modification I made on this PR

Are you sure you can reproduce it every time you start the application ?
Does it happen also on dev ?

**Review by tonymorony — APPROVED** [review]

**Comment by tonymorony** [comment]
thank you for pointing @SylEze , I've re-checked with a fresh mind and it behaves the same way on the dev
I've opened an issue ref this spinner: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1308

**Pull request merged**
