### PR TITLE
feat(trade_improvements): start improving ux experience on trading page

### PR DESCRIPTION
**Pull request by Milerius**

### CODE REVIEW

**Comment by smk762** [comment]
Looks nice!
Some minor GUI tweaks (linux):
- in history tab right side icons are a little cut-off
image
- in orders tab, swap arrows for in-progress trades are a bit too large, and the top / bottom arrows seem to be different line weights
image
- Filter functionality inconsistent between orders and history tab. In orders tab, filter is applied when drop down changes. In history tab, you need to click "apply filter" before it takes effect. Searchable dropdowns would be a nice enhancement.

Will use a bit and check on mac / windows over next day or two and see if anything else pops out.

**Comment by ssakone** [comment]
Thanks.
i Just fix issue 1 & 2 : [Commit](https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/4d2670e5143e8792d06be5acfb97efc33cea55f3)

for the search bar in combobox, i will do it in the day.

**Comment by smk762** [comment]
Confirmed icon alignment fix, and arrows now look much better. Searchable dropdowns in filters are very convenient, thanks.
Spoke to Slyris about "apply filter" button - no change needed as it is related to backend / mm2 api. 

Only minor gui tweaks I can see now are 
- remove "cancel all" button under orders tab if there are no orders listed
- perhaps later a checkbox could be added to select a subset for cancel, but not a high priority. 
- the AXE logo looks like the "x" to cancel orders! Perhaps a small hourglass icon for in-progress swaps aligned  with the "x" for cancelling at the right of the swap row could be added? 

Nice work!

**Comment by ssakone** [comment]
@smk762  first and third point is Okay, i will do checkable item soon. 
githubGif

**Comment by ssakone** [comment]
Last thing for this PR
githubGif2

**Review by smk762 — APPROVED** [review]
Awesome, looking good here thanks.

**Pull request merged**
