### PR TITLE
feat(price_service): transition to komodo price service

### PR DESCRIPTION
**Pull request by Milerius**
This pr introduce the komodo price service and replace the coingecko one

Everything related to price in general need to be tested

### CODE REVIEW

**Comment by smk762** [comment]
Slight overlap on price source icon (when set to other currencies like AUD. HKD, IDR etc)
image
image

Instead of "Price provider is: {coin}", can we set to "Price source: {coin}

Is Band oracle still being used for some things?
image
image
image

**Comment by Milerius** [comment]
> Slight overlap on price source icon (when set to other currencies like AUD. HKD, IDR etc)
> image
> image
> 
> Instead of "Price provider is: {coin}", can we set to "Price source: {coin}
> 
> Is Band oracle still being used for some things?
> image
> image
> image

Good catch. The text need to be changed, likely for the band source. It's only used for BAND now.

**Comment by tonymorony** [comment]
Supernet assets should be availiable on simple trading view:

https://user-images.githubusercontent.com/24797699/133214614-5fbafecb-0168-40ba-8766-d5ace4de9905.mov

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by Milerius** [comment]
> Supernet assets should be available on simple trading view:
> 
>  Screen.Recording.2021-09-14.at.14.30.27.mov

You mean shouldn't be?

**Comment by tonymorony** [comment]
@SylEze @Milerius there is a conflict with dev atm

```
Conflicting files
atomic_defi_design/qml/Portfolio/AssetsList.qml
```

so CI not triggered

**Review by tonymorony — APPROVED** [review]

**Pull request merged**
