### PR TITLE
Tweak trade errors

### PR DESCRIPTION
**Pull request by smk762**
closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2113
To test:
- Warning messages/tooltips for pro and simple mode should be the same 
- zhtlc coins partially activated will display progress percentage
- error messages should make sense 
- selecting a sell coin with zero balance shows placeholder and no spinning busy indicator visible
- sell coin volume input is disabled unless coin has balance and busy indicator not spinning

### CODE REVIEW

**Review by SirSevenG — APPROVED** [review]
lgtm

**Comment by smk762** [comment]
Thanks for the catch - BTC should not have anything to do with gas! I'll revisit the logic and see where it went wrong.

**Comment by smk762** [comment]
@Canialon should be fixed now

**Review by Canialon — DISMISSED** [review]

**Comment by SirSevenG** [comment]
On selecting coin with 0 balance in simple form as trade From, there're no error for it and infinite spinner on top of the form.
```
[13:14:48] [warning] [qt.trading.page.cpp:908] [4079]: last_trading_error is BalanceIsLessThanTheMinimalTradingAmount
[13:14:48] [info] [qt.orderbook.model.cpp:388] [4079]: full orderbook initialization initial size: 0 target size: 1, orderbook_kind: 1
[13:14:48] [info] [qt.orderbook.model.cpp:388] [4079]: full orderbook initialization initial size: 0 target size: 6, orderbook_kind: 2
[13:14:48] [info] [qt.orderbook.cpp:113] [4079]: selected best orders have a value - set preffered order
[13:14:48] [warning] [qt.trading.page.cpp:1473] [4079]: Spurious min_diff detected - (not) overriding immediately (using get_orderbook_wrapper()->get_current_min_taker_vol())
```

**Comment by smk762** [comment]
> On selecting coin with 0 balance in simple form as trade From, there're no error for it and infinite spinner on top of the form.
> 
> ```
> [13:14:48] [warning] [qt.trading.page.cpp:908] [4079]: last_trading_error is BalanceIsLessThanTheMinimalTradingAmount
> [13:14:48] [info] [qt.orderbook.model.cpp:388] [4079]: full orderbook initialization initial size: 0 target size: 1, orderbook_kind: 1
> [13:14:48] [info] [qt.orderbook.model.cpp:388] [4079]: full orderbook initialization initial size: 0 target size: 6, orderbook_kind: 2
> [13:14:48] [info] [qt.orderbook.cpp:113] [4079]: selected best orders have a value - set preffered order
> [13:14:48] [warning] [qt.trading.page.cpp:1473] [4079]: Spurious min_diff detected - (not) overriding immediately (using get_orderbook_wrapper()->get_current_min_taker_vol())
> ```

Thanks for the feedback - should be fixed now.

**Review by SirSevenG — APPROVED** [review]

**Review by Canialon — APPROVED** [review]

**Pull request merged**
