### PR TITLE
Fix various issue

### PR DESCRIPTION
**Pull request by ssakone**
I make a fix for 4 issue in this pull request

Check List:

- [x]  #1083
- [x]  #1090
- [x]  #1084
- [x]  #1085

### CODE REVIEW

**Comment by smk762** [comment]
-  #1083 :heavy_check_mark: 

-  #1090 :orange_circle: 
image
Needs one more char visible when not hidden. 16 dots when hidden is ok.
image

-  #1084 :heavy_check_mark: 
Looks good on linux, will check windows soon.

-  #1085 :heavy_check_mark: 
Looks good on linux, will check windows soon.

**Comment by ssakone** [comment]
@smk762 i add in login input field new dynamic size can you check if its good, i will apply to all the other password field.

**Comment by tonymorony** [comment]
needs to be synced with dev (https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1097) for CI build pass

**Comment by smk762** [comment]
Still 1 char short in linux when not hidden. Can we just increase the input 20%?

**Comment by Milerius** [comment]
image

not looking good for me @smk762 @ssakone

**Comment by Milerius** [comment]
Looking good for me now on my Linux high dpi high skill machine, how about you @smk762

**Review by smk762 — APPROVED** [review]
Look good here

**Pull request merged**
