### PR TITLE
Implement new dex view design

### LINKED ISSUE #1342: [BUG]: Long coin names doesn't fit selectors in pro view
cf:  https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1303

Screenshot 2021-09-28 at 15 48 05

### LINKED ISSUE #1463: [FEATURE REQUEST]: DEX pro view enhancement
cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1454
Issue placeholder, the goal is to make it closer to figma design

### LINKED ISSUE #1488: [BUG]: values in orderbook are not comparable because of wrong alignment
image

please change, so they are right-aligned, like it was before

### PR DESCRIPTION
**Pull request by SylEze**
Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1268
Closes #1342 
Closes #1488

### CODE REVIEW

**Comment by smk762** [comment]
When sidebar expanded, orderform overflows. Seems extra whitespace next to sidebar.
image
image

history data clipped
image

**Comment by tonymorony** [comment]
There is no chart at the moment

Figma:

image

`history data clipped`  ref such cases I think we should ask @polevin to draw pro view for minimal app size, that should help. right now it drawn for maximised window

@SylEze what is the min screen size you need design for?

**Comment by smk762** [comment]
It is also clipped at full screen size @ 3840*1080
image

**Comment by smk762** [comment]
Overflow issue is solved in latest build.
I still see cutoff on the history table though.
image

Also seems there is some extra whitespace between sidebar and dex page panels and between simple/pro selector and panels.
margin between panels themselves is inconsistent (x-axis vs y-axis widths) and dont fill to near the app edge.
image

**Comment by tonymorony** [comment]
updated mocks for minimised screen size (can be also found in figma), date representation as on mockup should allow to fit history: 

iMac - 2
paste

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by tonymorony** [comment]
Great progress! 

1) It would be great if you can display the date in history/orders same way as on mockups, this way data might be shown without cut as now:

image

image


2) Best orders widget is always empty now

image

3) Please align Place order widget bottom with others:

image

mockup: 

image

will perform another testing session tomorrow

**Comment by tonymorony** [comment]
P.S. lets try to solve in this rework as many small issues related to this view as possible:

https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1488
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1473
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1462
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1342
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1315
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1326
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1268
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/858

**Comment by tonymorony** [comment]
order history card info arrangement option to not cut stuff on small screens:

order_history_card

**Comment by tonymorony** [comment]
looks good so far on my side, great job!

@Canialon could you please carefully test DEX -> Pro view?

the only pb I noticed so far is a small glitch on modal:

Screenshot 2022-03-28 at 23 56 46

**Comment by smk762** [comment]
> Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1463 :grey_question:
- Need to test this on a different monitor

> Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1268 :x:
 - No tooltip seen for insufficient gas error
 - There is now whitespace where tooltip used to be - we should re-align columns so price is closer to left edge of line.
image

> Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1342 :heavy_check_mark:
- Overflow no longer visible, and ellipses visible in both light/dark
- We could improve this  with more linebreaks or "mouseover ticker shows fullname" & "mouseover balance shows fiat value", but will leave that for a future PR
image
image

> Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1473 :x:
- I still see some chart dancing when sidebar expands if the orderbook / form is hidden. It's ok when everything shown tho.

https://user-images.githubusercontent.com/35845239/160567997-13739ec9-e9dd-4001-a14c-25ed7bb02402.mp4

> Closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1488 :heavy_check_mark:
- Aligned right as requested

**Comment by smk762** [comment]
> P.S. lets try to solve in this rework as many small issues related to this view as possible:
> 
> #1488 
- Comment above, fixed in current CI build for this branch
> #1473
- Comment above
> #1462
- Awaiting figma design
> #1342
- Comment above, fixed in current CI build for this branch
> #1315
- Still unable to replicate locally (no stablecoins in my bestorders list, even when creating one externally. Potential bug, should relegate to new issue)
> #1326
- being worked on in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1688
> #1268
- Comment above
> #858 
- Closed by https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1666

**Comment by SylEze** [comment]
> > P.S. lets try to solve in this rework as many small issues related to this view as possible:
> > #1488
> 
>     * Comment above, fixed in current CI build for this branch
> 
> 
> > #1473
> 
>     * Comment above
> 
> 
> > #1462
> 
>     * Awaiting figma design
> 
> 
> > #1342
> 
>     * Comment above, fixed in current CI build for this branch
> 
> 
> > #1315
> 
>     * Still unable to replicate locally (no stablecoins in my bestorders list, even when creating one externally. Potential bug, should relegate to new issue)
> 
> 
> > #1326
> 
>     * being worked on in [Show full coin name (including protocol) in a best orders row #1688](https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1688)
> 
> 
> > #1268
> 
>     * Comment above
> 
> 
> > #858
> 
>     * Closed by [redraw bars when data changes #1666](https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1666)

I will not fix every issue mentionned in this PR, only the issues I put in the description

It has already sufficient changes: those ones will be fixed in another pull requests

**Comment by smk762** [comment]
@SylEze  @tonymorony suggest we merge this in current state address the following issues separately (or move to new issues):

- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1473 -> https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1420
- Custom confirmation settings layout
- more linebreaks or "mouseover ticker shows fullname" & "mouseover balance shows fiat value" for dex combo box selectors 
- No tooltip seen for insufficient gas error on orderbook hover
- better orderbook left column alignment
- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1326 (currently PR'd to this branch, better to PR to dev once missing bestorders issue is merged https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1698/commits/2cbb91f8af4f7b5d95aa5d75f8e3f49bc8c3dc37 
- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1463
- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1462

**Review by smk762 — APPROVED** [review]
Approving, outstanding issues to be dealt with separately. @SylEze please remove incomplete issue numbers # from your comment before merging so they don't close prematurely

**Review by tonymorony — APPROVED** [review]

**Pull request merged**
