### PR TITLE
Add TKL

### PR DESCRIPTION
**Pull request by smk762**

### CODE REVIEW

**Comment by tonymorony** [comment]
@Milerius  there is a special feature request for this one: please add a temporary "IDO" label for TOKEL (similar to smart chain, utxo, etc)

**Comment by tonymorony** [comment]
tested build from the latest commit but don't see label IDO anywhere (tried reset assets configuration):

image

**Comment by smk762** [comment]
I still see same in https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/1125625552

**Comment by tonymorony** [comment]
> I still see same in https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/1125625552

yep, same. @ssakone could you please help with this one?

I think it's fine to leave the smart chain category for Tokel when adding

Just draw "IDO" label here:

Screenshot 2021-08-12 at 18 23 57

**Comment by tonymorony** [comment]
yep, same. @ssakone could you please help with this one?

I think it's fine to leave the smart chain category for Tokel when adding

Just draw "IDO" label here:

Screenshot 2021-08-13 at 16 13 43

**Comment by Milerius** [comment]
I'm not able to enable tkl neither i or @SylEze

**Comment by tonymorony** [comment]
> I'm not able to enable tkl neither i or @SylEze

works fine on my side, can you try with VPN?

**Comment by smk762** [comment]
> I'm not able to enable tkl neither i or @SylEze

reset assets config?

**Comment by smk762** [comment]
image
image
image
image
image


I can see it in a few places now.
In pro swaps view, the TKL text contrast is not so good.

**Comment by Milerius** [comment]
On the dashboard it's seems that no tags are shown is that intended ?

**Comment by smk762** [comment]
"IDO" sighted in Dashboard and "enable assets" selection
Do we want to see it on the DEX / Wallet pages also?

**Review by tonymorony — APPROVED** [review]
lgtm, thanks!
I think it's fine to show it only in dashboard

**Pull request merged**
