### PR TITLE
fix(wallet): Windows 2FA when sending funds does not work

### PR DESCRIPTION
**Pull request by SylEze**
Partially solves #544 

Linux 2FA will still be missing.

### CODE REVIEW

**Comment by smk762** [comment]
Still not asking me for a password here on windows

**Comment by SylEze** [comment]
> 
> 
> Still not asking me for a password here on windows

Are you sure the option to enable 2FA is toggled as the below screenshot:
foodkfj

I got everything working as expected on my side:
pw

**Comment by SylEze** [comment]
> 
> 
> Still not asking me for a password here on windows

I pushed a logging message which should be displayed if the option is enabled when sending funds.
You should be able to see:
`[21:08:36] [info] [qt.wallet.page.cpp:568] [11016]: EVALUATE AUTH`

Tell me if you got the same output.

**Comment by SylEze** [comment]
> 
> 
> Still not asking me for a password here on windows

Sorry can you try again ? I forgot to commit something.

**Review by smk762 — APPROVED** [review]
Working now, thanks

**Pull request merged**
