### PR TITLE
Add vertical resizing feature to Widget component

### LINKED ISSUE #1733: [BUG]: orderbook does not expand when resizing window
image
resizing the window (in order to be able to see more orderbook entries without scrolling) changes size of  "best orders", but orderbook stays at max 6 entries, no matter how big i make the window
would be nice if orderbook would resize too, the space in "best orders" is unused when there are no other best orders
can "best orders" be changed so it uses 1/3 of the height while orderbook uses 2/3?
making both resizable or separating them from each other would be even better

### PR DESCRIPTION
**Pull request by SylEze**
Closes #1733

### CODE REVIEW

**Comment by smk762** [comment]
Still in draft - ready to test? If so what's the best way to test?

**Comment by SylEze** [comment]
> Still in draft - ready to test? If so what's the best way to test?

Not ready for testing, still buggy
I'll complete the PR once it's ready

**Comment by SylEze** [comment]
rdy @smk762

**Review by cipig — APPROVED** [review]
if you make orderbook smaller, "best orders" does not expand to full height automatically
image
but idk if that is important, works as expected else

**Comment by SylEze** [comment]
> if you make orderbook smaller, "best orders" does not expand to full height automatically image but idk if that is important, works as expected else

It's doesn't expand to full height when you resize the window ?

**Comment by cipig** [comment]
> It doesn't expand to full height when you resize the window ? @cipig

It does, but it doesn't if you make only orderbook smaller

**Comment by SylEze** [comment]
> > It doesn't expand to full height when you resize the window ? @cipig
> 
> It does, but it doesn't if you make only orderbook smaller oh, and it does too when you change resize window afterwards

Yeah it's like that beause the height is bind to your window's height by default - so if you change manually the size of your widget, it's not bind anymore to the window's height

Please note if you also resize the window and if the widgets are too long for the current window size, their height should be automatically reset

**Comment by tonymorony** [comment]
right now it's possible to minimise widgets to such state, what is imo not cool

It would be great to assign minimal size for every widget (e.g. 2 bids/2asks min for orderbook, 2 orders for best orders)

image

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by SylEze** [comment]
@tonymorony

**Review by cipig — APPROVED** [review]

**Review by tonymorony — APPROVED** [review]

**Pull request merged**
