### PR TITLE
0.4.3

### PR DESCRIPTION
**Pull request by ca333**
### Release Notes

**Features:** 

* :moneybag:  Add the following utxo coins: `LCC`, `DIMI`, `FUJI`
* :moneybag: Add the following pegged tokens: `FIRO-BEP20`, `stFIRO`
* :moneybag: Add the following BEP-20/ERC-20 tokens: `ANKR`, `XLM`, `TRON`, `BTT`, `FTM`, `SMTF`
* :closed_lock_with_key: Add 2FA in the settings (experimental on windows/osx)
* 🥇 Custom BEP20 tokens addition
* 🔢 Settings to change the limit number of simulateneous coins enabled

**Enhancements:**

* :apple: Use adaptive custom header for mac os (native look window)
* :up: Update to the last version of Atomicdex API
* :up: Add 4 AUR electrums
* :open_mouth: Improve various min volume usage for pro trading view
* :ru: Extend Russian translations
* :fr: Extend French translations
* :closed_lock_with_key: SSL electrums for ABY
* :muscle: use our own BSC nodes
* :diamond_shape_with_a_dot_inside: Installer for forked project now correctly set the name of the maintenance tool
* :nail_care: beautify notifications modal
* :heavy_check_mark: More checks when sending coins if parent chain are non enabled or zero balance
* :heavy_check_mark: More checks for the trading page when trading tokens with parent chain handling
* :paintbrush: New icons for various coins
* 🎨 Add new themes (reset assets config to be able to see the new themes)
 
**Fixes:**

* :rescue_worker_helmet:  Fix various text overflow in the app
* :balance_scale: Remove table frame in contact edition modal (addressbook)
* :bookmark_tabs: Fix icon position in addressbook
* :dollar: Fix fees display for transactions
* :rescue_worker_helmet: Fix minimize window on windows/osx
* 😞 disable wallet charts (Turn it back to WIP / CPU consumption)
* 💻 Add network retry, use komodo fiat rates api

**BREAKING CHANGE**

Ubuntu 16.04 is no longer supported: `Ubuntu Linux 16.04 LTS is no longer supported
Ubuntu Linux 16.04 LTS reached the end of its five-year LTS window on April 30th 2021 and is no longer supported by its vendor, Canonical except through a paid annual Extended Security Maintenance`

If you want to still use AtomicDEX Desktop on 16.04 you need to compile manually from the wiki build instructions page.

### CODE REVIEW

**Comment by smk762** [comment]
Linux:
 - All artefacts launching ok. :heavy_check_mark:
 - LCC sighted :heavy_check_mark:
 - addressbook frame fixed; icon alignment ok :heavy_check_mark:
 - large balance in combobox not overflowing :heavy_check_mark:
 - best order padding ok :heavy_check_mark:
 - fees fiat value and parent coin display ok. :heavy_check_mark:
 - no overflow in sidebar with all languages :heavy_check_mark:
 - desktop notifications toggle working as expected :heavy_check_mark:
 - test swaps completed without issue. :heavy_check_mark:
 - confirm send button disabled where no funds or no parent chain funds for fee. :heavy_check_mark:
 - confirm send button disables/enables when send max or funds received as expected. :heavy_check_mark:
 - confirm default coins == KMD/LTC/BTC :heavy_check_mark:
 
 Windows:
 - minimise to taskbar working as expected.
 - 2FA toggle is not forcing entering password before send :x:

**Review by Milerius — COMMENTED** [review]
Waiting for #886  and #906 to be merged/implemented before merging 0.4.3

**Comment by Milerius** [comment]
> Linux:
> 
> * All artefacts launching ok. heavy_check_mark
> * LCC sighted heavy_check_mark
> * addressbook frame fixed; icon alignment ok heavy_check_mark
> * large balance in combobox not overflowing heavy_check_mark
> * best order padding ok heavy_check_mark
> * fees fiat value and parent coin display ok. heavy_check_mark
> * no overflow in sidebar with all languages heavy_check_mark
> * desktop notifications toggle working as expected heavy_check_mark
> * test swaps completed without issue. heavy_check_mark
> * confirm send button disabled where no funds or no parent chain funds for fee. heavy_check_mark
> * confirm send button disables/enables when send max or funds received as expected. heavy_check_mark
> * confirm default coins == KMD/LTC/BTC heavy_check_mark
> 
> Windows:
> 
> * minimise to taskbar working as expected. heavy_check_mark
> * LCC sighted heavy_check_mark
> * 2FA toggle is not forcing entering password before send x
> * Windows installer not working on fresh systems x
> * Windows zip launches ok  heavy_check_mark
> * no overflow in sidebar with all languages heavy_check_mark
> * addressbook frame fixed; icon alignment ok heavy_check_mark
> * desktop notifications toggle working as expected heavy_check_mark
> * test swaps completed without issue. heavy_check_mark
> * best order padding ok heavy_check_mark
> * confirm send button disables/enables when send max or funds received as expected. heavy_check_mark
> * confirm default coins == KMD/LTC/BTC heavy_check_mark
> 
> Mac:
> 
> * minimise /maximise working as expected. heavy_check_mark
> * best order padding ok heavy_check_mark
> * confirm default coins == KMD/LTC/BTC heavy_check_mark
> * DMG and installer launching ok  heavy_check_mark
> * 2FA toggle is forcing entering password before send heavy_check_mark
> * LCC sighted heavy_check_mark
> * desktop notifications toggle working as expected heavy_check_mark
> * no overflow in sidebar with all languages heavy_check_mark (French font size is tiny!)
> * addressbook frame fixed; icon alignment ok heavy_check_mark
> * test swaps completed without issue. heavy_check_mark
> * confirm send button disables/enables when send max or funds received as expected. heavy_check_mark
> 
> Other Notes:
> 
> * in Settings > User Interface, there is a button for changing themes, with the text "Apply Changement" on all languages except French. In English, this should be "Apply Changes". exclamation
> * French text overflow in settings confirmation buttons on all OS x
> 
> image

> Windows installer not working on fresh systems 

Still waiting for a fix from Qt side

> 2FA toggle is not forcing entering password before send x

@SylEze will be nice to check with @smk762 why he have this specific behaviour on windows

> in Settings > User Interface, there is a button for changing themes, with the text "Apply Changement" on all languages except > French. In English, this should be "Apply Changes". exclamation
> French text overflow in settings confirmation buttons on all OS x

@ssakone is already checking at this part i believe

**Comment by SirSevenG** [comment]
> 2FA toggle is not forcing entering password before send ❌
> Windows installer not working on fresh systems ❌
Installer works just fine on fresh systems for me.
Can confirm 2FA does not work on Win.

No application icon on Ubuntu taskbar (AppIamge run)
изображение


Didn't find anything more than mentioned above and french locale overflowing buttons in settings.

**Comment by Milerius** [comment]
> > 2FA toggle is not forcing entering password before send x
> > Windows installer not working on fresh systems x
> 
> Installer works just fine on fresh systems for me.
> Can confirm 2FA does not work on Win.
> 
> No application icon on Ubuntu taskbar (AppIamge run)
> изображение
> 
> Didn't find anything more than mentioned above and french locale overflowing buttons in settings.

You need to install the appimage first if you want the icon with: https://github.com/TheAssassin/AppImageLauncher/releases

proof_1
proof_2

**Comment by Milerius** [comment]
still waiting for a small overflow fix from @ssakone and then i'm ready to approve

**Review by Milerius — DISMISSED** [review]

**Comment by smk762** [comment]
Logging out works ok, but the settings panel remains visible after action completed.

https://user-images.githubusercontent.com/35845239/118243696-4b55a280-b4d1-11eb-9d0c-af5bb617dcdf.mp4

Also happens when deleting a wallet.

**Comment by Milerius** [comment]
> Logging out works ok, but the settings panel remains visible after action completed.
> 
>  logout_linger.mp4 
> Also happens when deleting a wallet.

thanks you for the report, i informed @ssakone we will fix shortly

**Comment by smk762** [comment]
I seem unable to reset assets config on latest CI https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/844354778
`[15:16:32] [warning] [main.prerequisites.hpp:125] [466983]: qrc:/atomic_defi_design/qml/Settings/SettingModal.qml:0: ReferenceError: restart_modal is not defined
`

**Comment by smk762** [comment]
Seeing this in `Settings > Version`
image

**Comment by smk762** [comment]
I can see version on Linux now, and reset assets again.

**Review by Milerius — DISMISSED** [review]

**Comment by Milerius** [comment]
> I can see version on Linux now, and reset assets again.

will approve after your review of current app status tommorow

**Comment by smk762** [comment]
Linux looking good all previous mentioned issues resolved.
Windows no problem, except for 2FA toggle not forcing system password on send.
Will spend some time and Mac now and report back

**Comment by Milerius** [comment]
> Linux looking good all previous mentioned issues resolved.
> Windows no problem, except for 2FA toggle not forcing system password on send.
> No problems experienced on Mac.

Would like #915 to be included in the release, fix various crash

**Review by Milerius — APPROVED** [review]

**Review by smk762 — APPROVED** [review]

**Pull request merged**
