### PR TITLE
Fees view

### PR DESCRIPTION
**Pull request by smk762**
closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1252
partially solves: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/997

before:
image

after:
image

### CODE REVIEW

**Comment by Milerius** [comment]
Be careful, you have one scientific notation for one if the fees

**Comment by tonymorony** [comment]
Screenshot 2022-02-15 at 13 48 34

yep, scientific notation appears (circle)

also could you please add newline (red line) to separate visually total and detailed fees blocks?

**Review by tonymorony — CHANGES_REQUESTED** [review]
^^

**Comment by smk762** [comment]
updated:
image

**Review by tonymorony — APPROVED** [review]
works fine now

lets wait for @SylEze code review before merging

**Comment by SylEze** [comment]
@smk762 soon QML expert 🙏 

Merging...

**Pull request merged**
